Repository googleapis/google-cloud-java, pull requests merged in 2018-07, with the labels that each got.

#3421 Adding region tags to the README file
  README.md
Labels: cla: yes

#3422 Removing the region tags
  README.md
Labels: cla: yes

#3406 Requester-Pays bucket support.
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageConfiguration.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystem.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannel.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannelTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Labels: cla: yes

#2838 RFC: new approach for snippet injection
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageReceiver.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/MessageReceiverSnippets.java
  utilities/snippets.go
  utilities/snippets_test.go
Labels: cla: yes

#3428 Creating batch_generate_apis.py
  .gitignore
  utilities/batch_generate_apis.py
  utilities/generate_api.py
Labels: cla: yes

#3435 Bump maven-source-plugin to 3.0.1
  google-api-grpc/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#3388 Update READMEs for Compute
  README.md
  google-cloud-clients/google-cloud-compute/README.md
  google-cloud-examples/pom.xml
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/deprecated/ComputeExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/v1/ComputeExample.java
Labels: cla: yes

#3434 Fix the error when calling Timestamp.of(Date date) when date is pre epoch
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/Timestamp.java
  google-cloud-clients/google-cloud-core/src/test/java/com/google/cloud/TimestampTest.java
Labels: cla: yes

#3439 Bump gax versions to 1.29.0/0.46.0
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#3440 Fix appveyor CI by using TLS 1.2 for Java 7
  appveyor.yml
Labels: cla: yes

#3445 Add IoT, KMS and Tasks to batch generation
  utilities/batch_generate_apis.py
Labels: cla: yes

#3444 Regenerating proto/grpc/gapic code
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CreateExclusionRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CreateLogMetricRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CreateSinkRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/DeleteExclusionRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/DeleteLogMetricRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/DeleteLogRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/DeleteSinkRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/GetExclusionRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/GetLogMetricRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/GetSinkRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListExclusionsRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListExclusionsResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogEntriesRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogEntriesResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogMetricsRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogMetricsResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogsRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogsResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListMonitoredResourceDescriptorsRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListMonitoredResourceDescriptorsResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListSinksRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListSinksResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogEntry.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogEntryOperation.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogEntrySourceLocation.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogExclusion.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogMetric.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogSink.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/UpdateExclusionRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/UpdateLogMetricRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/UpdateSinkRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/WriteLogEntriesPartialErrors.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/WriteLogEntriesRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/WriteLogEntriesResponse.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechProto.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechRecognitionResult.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechRecognitionResultOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognitionResult.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognitionResultOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/WordInfo.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/WordInfoOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
Labels: cla: yes

#3446 Ignore deprecated Compute integration test
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/deprecated/it/ITComputeTest.java
Labels: cla: yes

#3447 bump grpc version
  google-cloud-clients/pom.xml
Labels: cla: yes

#3433 Retry IOException: Error writing request body to server
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/BaseServiceException.java
Labels: cla: yes

#3452 ignore nio tests related to requester pays bucket
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Labels: cla: yes

#3451 Cleanup: generation instructions, version ordering
  utilities/generate_api.py
  versions.txt
Labels: cla: yes

#3449 Bump protobuf java to 3.6.0
  google-api-grpc/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#3453 Generation refresh - Cloud Tasks
  google-api-grpc/grpc-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/CloudTasksGrpc.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/CloudTasksProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/ListTasksRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/ListTasksRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/proto/google/cloud/tasks/v2beta2/cloudtasks.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/proto/google/cloud/tasks/v2beta2/queue.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/proto/google/cloud/tasks/v2beta2/target.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/proto/google/cloud/tasks/v2beta2/task.proto
  google-cloud-clients/google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta2/CloudTasksClient.java
Labels: cla: yes

#3456 Fix indentation in code example
  google-cloud-clients/google-cloud-pubsub/README.md
Labels: cla: yes

#3459 Fixing BigTable javadoc errors
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/TableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/GCRules.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/TableAdminResponses.java
Labels: cla: yes

#3464 Updating RELEASING.md
  RELEASING.md
Labels: cla: yes

#3465 Cleaning up client lists and API titles
  README.md
  google-cloud-clients/google-cloud-bigtable/README.md
  google-cloud-clients/google-cloud-container/README.md
  google-cloud-clients/google-cloud-redis/README.md
  google-cloud-clients/google-cloud-texttospeech/README.md
  google-cloud-clients/google-cloud-websecurityscanner/README.md
  google-cloud-clients/pom.xml
Labels: cla: yes

#3467 Fix Storage rewrite operation to support predefinedAcl on a copy
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#3454 Fix one test to work with the other unit tests
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Labels: cla: yes

#3471 bigtable: fix hardcoded admin test integration target
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/TableAdminClientIT.java
Labels: cla: yes

#3473 bigtable: fix integration test
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/TableAdminClientIT.java
Labels: cla: yes

#3469 Avoid listing table data for destination of CREATE VIEW DDL queries.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/EmptyTableResult.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatus.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITCloudSnippets.java
Labels: api: bigquery, cla: yes, priority: p1

#3477 Add new API versions
  utilities/batch_generate_apis.py
Labels: cla: yes

#3487 Speech is in beta
  README.md
Labels: cla: yes

#3481 update opencensus
  google-cloud-clients/pom.xml
Labels: cla: yes

#3495 Bigtable: remove regen scripts in favor of utilities/generate_api.py
  google-cloud-clients/google-cloud-bigtable/DEVELOPING.md
  google-cloud-clients/google-cloud-bigtable/autogen_files.lst
  google-cloud-clients/google-cloud-bigtable/handwritten_files.lst
  google-cloud-clients/google-cloud-bigtable/scripts/README.md
  google-cloud-clients/google-cloud-bigtable/scripts/regenerate.sh
  google-cloud-clients/google-cloud-bigtable/scripts/update-deps.sh
Labels: cla: yes

#3493 ci: don't JAR javadoc
  .circleci/config.yml
Labels: cla: yes

#3499 Fix pom urls
  google-cloud-clients/google-cloud-automl/pom.xml
  google-cloud-clients/google-cloud-bigquery/pom.xml
  google-cloud-clients/google-cloud-bigquerydatatransfer/pom.xml
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/google-cloud-compute/pom.xml
  google-cloud-clients/google-cloud-container/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-nio-examples/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/pom.xml
  google-cloud-clients/google-cloud-contrib/pom.xml
  google-cloud-clients/google-cloud-core-grpc/pom.xml
  google-cloud-clients/google-cloud-core-http/pom.xml
  google-cloud-clients/google-cloud-core/pom.xml
  google-cloud-clients/google-cloud-dataproc/pom.xml
  google-cloud-clients/google-cloud-datastore/pom.xml
  google-cloud-clients/google-cloud-dialogflow/pom.xml
  google-cloud-clients/google-cloud-dlp/pom.xml
  google-cloud-clients/google-cloud-dns/pom.xml
  google-cloud-clients/google-cloud-errorreporting/pom.xml
  google-cloud-clients/google-cloud-firestore/pom.xml
  google-cloud-clients/google-cloud-iot/pom.xml
  google-cloud-clients/google-cloud-kms/pom.xml
  google-cloud-clients/google-cloud-language/pom.xml
  google-cloud-clients/google-cloud-logging/pom.xml
  google-cloud-clients/google-cloud-monitoring/pom.xml
  google-cloud-clients/google-cloud-notification/pom.xml
  google-cloud-clients/google-cloud-os-login/pom.xml
  google-cloud-clients/google-cloud-pubsub/pom.xml
  google-cloud-clients/google-cloud-redis/pom.xml
  google-cloud-clients/google-cloud-resourcemanager/pom.xml
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/google-cloud-speech/pom.xml
  google-cloud-clients/google-cloud-storage/pom.xml
  google-cloud-clients/google-cloud-tasks/pom.xml
  google-cloud-clients/google-cloud-texttospeech/pom.xml
  google-cloud-clients/google-cloud-trace/pom.xml
  google-cloud-clients/google-cloud-translate/pom.xml
  google-cloud-clients/google-cloud-video-intelligence/pom.xml
  google-cloud-clients/google-cloud-vision/pom.xml
  google-cloud-clients/google-cloud-websecurityscanner/pom.xml
Labels: cla: yes

#3498 bump auth version
  google-cloud-clients/pom.xml
Labels: cla: yes

#3501 Minor fix on the comments in Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#3507 Using --aspect CODE from artman; supporting java_proto
  utilities/batch_generate_apis.py
  utilities/generate_api.py
Labels: cla: yes

#3415 BigQuery: Add Clustering support
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Clustering.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/WriteChannelConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/WriteChannelConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#3516 fixed Tasks client library link
  google-cloud-clients/google-cloud-tasks/README.md
Labels: cla: yes
