Repository googleapis/google-cloud-java, pull requests merged in 2018-06, with the labels that each got.

#3328 fix example links
  google-cloud-clients/google-cloud-bigquery/README.md
  google-cloud-clients/google-cloud-compute/README.md
  google-cloud-clients/google-cloud-contrib/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-nio-examples/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/README.md
  google-cloud-clients/google-cloud-datastore/README.md
  google-cloud-clients/google-cloud-dns/README.md
  google-cloud-clients/google-cloud-language/README.md
  google-cloud-clients/google-cloud-logging/README.md
  google-cloud-clients/google-cloud-pubsub/README.md
  google-cloud-clients/google-cloud-resourcemanager/README.md
  google-cloud-clients/google-cloud-spanner/README.md
  google-cloud-clients/google-cloud-speech/README.md
  google-cloud-clients/google-cloud-storage/README.md
  google-cloud-clients/google-cloud-translate/README.md
  google-cloud-clients/google-cloud-vision/README.md
Labels: cla: yes

#3339 add newBuilder() to logging.SourceLocation
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/SourceLocation.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/SourceLocationTest.java
Labels: cla: yes

#3323 GCS w/ KMS Samples
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: cla: yes

#3340 make storage batch request honor options.getHost()
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
Labels: cla: yes

#3341 Update README.md
  google-cloud-clients/google-cloud-pubsub/README.md
Labels: cla: yes

#3304 Spanner gapic migration error augmentation with interceptor
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/LoggingInterceptor.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerInterceptorProvider.java
Labels: cla: yes

#3332 Add a spanId field to the google-cloud-logging LogEntry class.
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/LogEntry.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/LogEntryTest.java
Labels: cla: yes

#3301 Logging: set Trace in trace instead of label
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/TraceLoggingEnhancer.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingHandlerTest.java
Labels: cla: yes

#3346 Add watchdog interceptor
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerInterceptorProvider.java
Labels: cla: yes

#3347 Add link to cpp doc page in google-cloud-clients/src/site/index.html
  google-cloud-clients/src/site/resources/img/icon-lang-cpp.svg
  google-cloud-clients/src/site/resources/index.html
Labels: cla: yes

#3317 Return Dates as com.google.cloud.Timestamps
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/CustomClassMapper.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Precondition.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/QueryDocumentSnapshot.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/QuerySnapshot.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/WriteResult.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/annotation/ServerTimestamp.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/CollectionReferenceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/WatchTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/WriteBatchTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#3357 Add support for PARQUET format in BigQuery load jobs.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FormatOptions.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/CloudSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITCloudSnippets.java
Labels: api: bigquery, cla: yes

#3320 Exposing TransportChannelProvider & CredentialsProvider
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1beta1/GrpcFirestoreRpc.java
Labels: cla: yes

#3361 Add samples for managing tables.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/CloudSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITBigQuerySnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITCloudSnippets.java
Labels: cla: yes

#3359 Batch sample now reflects Go and Python versions
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/CloudSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITCloudSnippets.java
Labels: cla: yes

#3352 Update websecurityscanner Readme
  google-cloud-clients/google-cloud-websecurityscanner/README.md
Labels: cla: yes

#3351 Bigtable: enable JWT tokens
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
Labels: cla: yes

#3287 Add support for struct-typed parameters in Cloud Spanner.
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractStructReader.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResultSets.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Struct.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/ValueBinder.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResultSetsTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/StructTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueBinderTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
Labels: cla: yes

#3364 Removes old sample
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/CloudSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITCloudSnippets.java
Labels: api: bigquery, cla: yes, documentation

#3366 Fix zipslip vulnerability
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/testing/BaseEmulatorHelper.java
Labels: cla: yes

#3365 Bumping monitoring-v3 to GA
  README.md
  versions.txt
Labels: cla: yes

#3374 bump grpc version
  google-cloud-clients/pom.xml
Labels: cla: yes

#3375 Bumping gax to 1.28.0 (bidi streaming updates)
  README.md
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#3379 Fixing nexus-staging:release from root
  google-cloud-examples/pom.xml
  google-cloud-testing/pom.xml
  google-cloud-util/pom.xml
  pom.xml
Labels: cla: yes

#3382 Fixing releasing instructions [ci skip]
  RELEASING.md
Labels: cla: yes

#3389 Creating generate_api.py
  utilities/generate_api.py
Labels: cla: yes

#3392 Moving Monitoring to GA section [ci skip]
  README.md
  google-cloud-clients/google-cloud-monitoring/README.md
Labels: cla: yes

#3395 Fluent DSL TableAdmin client
  google-cloud-clients/google-cloud-bigtable/handwritten_files.lst
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/TableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/GCRules.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/TableAdminRequests.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/TableAdminResponses.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/TableAdminClientTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/TableAdminClientIT.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/GCRulesTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/TableAdminRequestsTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/TableAdminResponsesTest.java
Labels: cla: yes

#3404 Bumping Speech from alpha to beta
  versions.txt
Labels: cla: yes

#3407 BigQuery: Document the behavior that streaming inserts are not present in destination output
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Table.java
Labels: cla: yes

#3408 Point ALPN not configured properly in TROUBLESHOOTING.md to the compatibility checker.
  TROUBLESHOOTING.md
Labels: cla: yes

#3411 Fixing versioning comments for GA clients [ci skip]
  google-cloud-clients/google-cloud-bigquery/README.md
  google-cloud-clients/google-cloud-core/README.md
  google-cloud-clients/google-cloud-language/README.md
  google-cloud-clients/google-cloud-monitoring/README.md
  google-cloud-clients/google-cloud-pubsub/README.md
  google-cloud-clients/google-cloud-translate/README.md
  google-cloud-clients/google-cloud-vision/README.md
Labels: cla: yes

#3413 Set project id from credentials
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java
  google-cloud-clients/google-cloud-core/src/test/java/com/google/cloud/ServiceOptionsTest.java
Labels: cla: yes
