Repository googleapis/google-cloud-java, pull requests merged in 2018-11, with the labels that each got.

#3895 Bigtable: fix admin tests to able to run concurrently
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
Labels: api: bigtable, cla: yes

#3886 Pub/Sub: update ApiFutures.addCallback()
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/PublisherSnippets.java
Labels: cla: yes

#3555 Move BOM info to right after Quick Start
  README.md
Labels: cla: yes

#3881 Spanner gapic migration
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Database.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Instance.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GrpcSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/LoggingInterceptor.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerInterceptorProvider.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerMetadataProvider.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/BatchClientImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/GceTestEnvConfig.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminClientImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/OperationFutureUtil.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITInstanceAdminTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/RequestMetadataTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/SpannerMetadataProviderTest.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/spanner/snippets/DatabaseAdminClientSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/spanner/snippets/InstanceAdminClientSnippets.java
Labels: cla: yes

#3915 Add a feature to list the buckets
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystem.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Labels: cla: yes

#3581 make pubsub use gapic client
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StatusUtil.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/StatusUtilTest.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
Labels: cla: yes

#3898 Stop leaving leftover buckets in ITGcsNIO
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/testing/RemoteStorageHelper.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/testing/RemoteStorageHelperTest.java
Labels: cla: yes

#3863 Add a traceSampled field to the google-cloud-logging LogEntry class.
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/LogEntry.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/LogEntryTest.java
Labels: cla: yes

#3856 Bigtable: add sync methods
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
Labels: cla: yes

#3913 New Client: Cloud Scheduler
  google-api-grpc/grpc-google-cloud-scheduler-v1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerGrpc.java
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/pom.xml
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineHttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineHttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineRouting.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineRoutingOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CreateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CreateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/DeleteJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/DeleteJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/GetJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/GetJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpMethod.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/Job.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/JobName.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/JobOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/JobProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsResponse.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/LocationName.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PauseJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PauseJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ProjectName.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PubsubTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PubsubTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ResumeJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ResumeJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RetryConfig.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RetryConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RunJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RunJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/SchedulerProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/TargetProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/UpdateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/UpdateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/cloudscheduler.proto
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/job.proto
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/target.proto
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-scheduler/README.md
  google-cloud-clients/google-cloud-scheduler/pom.xml
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClient.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerSettings.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/package-info.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStub.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStubSettings.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/GrpcCloudSchedulerCallableFactory.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/GrpcCloudSchedulerStub.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClientTest.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/MockCloudScheduler.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/MockCloudSchedulerImpl.java
  google-cloud-clients/google-cloud-scheduler/synth.py
  google-cloud-clients/pom.xml
  versions.txt
Labels: cla: yes

#3891 Exists method added in BigtableInstanceAdminClient
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTest.java
Labels: api: bigtable, cla: yes

#3900 Firestore: Validate that at least one argument is provided for Cursor
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/resources/test-suite.binproto
Labels: cla: yes

#3840 bigtable emulator
  google-cloud-bom/pom.xml
  google-cloud-testing/google-cloud-bigtable-emulator/README.md
  google-cloud-testing/google-cloud-bigtable-emulator/pom.xml
  google-cloud-testing/google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/BigtableEmulatorRule.java
  google-cloud-testing/google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/Emulator.java
  google-cloud-testing/google-cloud-bigtable-emulator/src/test/java/com/google/cloud/bigtable/emulator/v2/BigtableEmulatorRuleTest.java
  google-cloud-testing/google-cloud-bigtable-emulator/src/test/java/com/google/cloud/bigtable/emulator/v2/EmulatorTest.java
  google-cloud-testing/google-cloud-gcloud-maven-plugin/README.md
  google-cloud-testing/google-cloud-gcloud-maven-plugin/pom.xml
  google-cloud-testing/google-cloud-gcloud-maven-plugin/src/main/java/com/google/cloud/Component.java
  google-cloud-testing/google-cloud-gcloud-maven-plugin/src/main/java/com/google/cloud/DownloadComponentsMojo.java
  google-cloud-testing/pom.xml
  versions.txt
Labels: api: bigtable, cla: yes

#3269 Update README to suggest importing BOM
  README.md
Labels: cla: yes

#3923 Spanner: use WatchdogProvider
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerInterceptorProvider.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/WatchdogInterceptor.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/WatchdogInterceptorTest.java
Labels: cla: yes

#3696 Bigtable: be consistent and don't expose absolute table names
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
Labels: api: bigtable, cla: yes

#3925 Update container synth script for new artman config name
  google-cloud-clients/google-cloud-container/synth.py
Labels: cla: yes

#3935 New Client: BigQuery Storage
  google-api-grpc/grpc-google-cloud-bigquerystorage-v1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BigQueryStorageGrpc.java
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/pom.xml
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/AvroProto.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/ReadOptions.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/Storage.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/TableReferenceProto.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/avro.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/read_options.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/storage.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/table_reference.proto
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-bigquerystorage/README.md
  google-cloud-clients/google-cloud-bigquerystorage/pom.xml
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClient.java
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageSettings.java
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/package-info.java
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/BigQueryStorageStub.java
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/BigQueryStorageStubSettings.java
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/GrpcBigQueryStorageCallableFactory.java
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/GrpcBigQueryStorageStub.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClientTest.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/MockBigQueryStorage.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/MockBigQueryStorageImpl.java
  google-cloud-clients/google-cloud-bigquerystorage/synth.py
  google-cloud-clients/pom.xml
Labels: cla: yes

#3926 Add Kokoro nightly build configs
  .kokoro/nightly/bigquery-it.cfg
  .kokoro/nightly/bigtable-it.cfg
  .kokoro/nightly/bigtableadmin-it.cfg
  .kokoro/nightly/common.cfg
  .kokoro/nightly/compute-it.cfg
  .kokoro/nightly/datastore-it.cfg
  .kokoro/nightly/dns-it.cfg
  .kokoro/nightly/firestore-it.cfg
  .kokoro/nightly/java10.cfg
  .kokoro/nightly/java11.cfg
  .kokoro/nightly/java7.cfg
  .kokoro/nightly/java8-osx.cfg
  .kokoro/nightly/java8-win.cfg
  .kokoro/nightly/java8.cfg
  .kokoro/nightly/javadoc.cfg
  .kokoro/nightly/logging-it.cfg
  .kokoro/nightly/notification-it.cfg
  .kokoro/nightly/pubsub-it.cfg
  .kokoro/nightly/spanner-it.cfg
  .kokoro/nightly/speech-it.cfg
  .kokoro/nightly/storage-it.cfg
  .kokoro/nightly/translate-it.cfg
Labels: cla: yes

#3941 Add namespace and schema to settings.xml
  RELEASING.md
Labels: cla: yes

#3939 Regenerate bigquerystorage client
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/Storage.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/storage.proto
Labels: cla: yes

#3933 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionAudio.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionAudioOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechContext.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechContextOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechProto.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechRecognitionAlternative.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechRecognitionAlternativeOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognitionResult.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognitionResultOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognizeRequest.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognizeRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
Labels: cla: yes

#3980 Upgrade gax and guava dependencies
  google-api-grpc/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-bigquerystorage/pom.xml
  google-cloud-clients/pom.xml
  google-cloud-testing/pom.xml
Labels: cla: yes

#3984 Fix BigQuery NullPointerException when estimatedFields is empty
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java
Labels: cla: yes

#4020 Add synth metadata for many clients
  google-cloud-clients/google-cloud-asset/synth.metadata
  google-cloud-clients/google-cloud-automl/synth.metadata
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
  google-cloud-clients/google-cloud-bigtable-admin/synth.metadata
  google-cloud-clients/google-cloud-bigtable/synth.metadata
  google-cloud-clients/google-cloud-compute/synth.metadata
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
  google-cloud-clients/google-cloud-dataproc/synth.metadata
  google-cloud-clients/google-cloud-datastore/synth.metadata
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
  google-cloud-clients/google-cloud-dlp/synth.metadata
  google-cloud-clients/google-cloud-errorreporting/synth.metadata
  google-cloud-clients/google-cloud-firestore/synth.metadata
  google-cloud-clients/google-cloud-iot/synth.metadata
  google-cloud-clients/google-cloud-kms/synth.metadata
  google-cloud-clients/google-cloud-language/synth.metadata
  google-cloud-clients/google-cloud-logging/synth.metadata
  google-cloud-clients/google-cloud-os-login/synth.metadata
  google-cloud-clients/google-cloud-redis/synth.metadata
  google-cloud-clients/google-cloud-scheduler/synth.metadata
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
  google-cloud-clients/google-cloud-spanner/synth.metadata
  google-cloud-clients/google-cloud-speech/synth.metadata
  google-cloud-clients/google-cloud-tasks/synth.metadata
  google-cloud-clients/google-cloud-texttospeech/synth.metadata
  google-cloud-clients/google-cloud-trace/synth.metadata
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
  google-cloud-clients/google-cloud-websecurityscanner/synth.metadata
Labels: cla: yes

#3910 Storage: Added feature to change host name of signed url
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
Labels: api: storage, cla: yes

#4080 Regenerate websecurityscanner client
  google-cloud-clients/google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/stub/WebSecurityScannerStubSettings.java
Labels: cla: yes

#4102 Delay download of Bigtable emulator
  .kokoro/build.sh
  google-cloud-testing/google-cloud-gcloud-maven-plugin/src/main/java/com/google/cloud/DownloadComponentsMojo.java
Labels: cla: yes

#4079 Regenerate trace client
  google-cloud-clients/google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/TraceServiceStubSettings.java
Labels: cla: yes

#4077 Regenerate speech client
  google-cloud-clients/google-cloud-speech/src/test/java/com/google/cloud/speech/v1/SpeechClientTest.java
  google-cloud-clients/google-cloud-speech/src/test/java/com/google/cloud/speech/v1/SpeechSmokeTest.java
  google-cloud-clients/google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/SpeechClientTest.java
  google-cloud-clients/google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/SpeechSmokeTest.java
Labels: cla: yes

#4071 Regenerate language client
  google-cloud-clients/google-cloud-language/src/test/java/com/google/cloud/language/v1/LanguageServiceSmokeTest.java
  google-cloud-clients/google-cloud-language/src/test/java/com/google/cloud/language/v1beta2/LanguageServiceSmokeTest.java
Labels: cla: yes

#4093 Datastore: Add `skippedResults` in `QueryResults`
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResults.java
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResultsImpl.java
  google-cloud-clients/google-cloud-datastore/src/test/java/com/google/cloud/datastore/DatastoreTest.java
  google-cloud-clients/google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITDatastoreTest.java
Labels: cla: yes

#4105 Spanner: format fixes
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
Labels: cla: yes

#3869 Put new retry options in CloudStorageConfiguration
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageConfiguration.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannel.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageConfigurationTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannelTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandlerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Labels: cla: yes

#4058 Moving surefire-junit4 out of the dependency lists to allow others to better run tests.
  google-cloud-clients/google-cloud-bigtable-admin/pom.xml
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/google-cloud-logging/pom.xml
  google-cloud-util/pom.xml
Labels: cla: yes

#3911 Add helpers to convert core Date class with java.util.Date class
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/Date.java
  google-cloud-clients/google-cloud-core/src/test/java/com/google/cloud/DateTest.java
Labels: cla: yes

#4106 Bigtable: publish emulator to maven central
  google-cloud-testing/google-cloud-bigtable-emulator/pom.xml
Labels: api: bigtable, cla: yes

#4017 Firestore: Adding FieldMask support to GetAll()
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldMask.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#4112 changed TestServiceFactory and TestServiceRpcFactory to public
  google-cloud-clients/google-cloud-core/src/test/java/com/google/cloud/ServiceOptionsTest.java
Labels: cla: yes

#3821 Java 11 compatibility
  google-api-grpc/pom.xml
  google-cloud-clients/google-cloud-core/src/test/java/com/google/cloud/ServiceOptionsTest.java
  google-cloud-clients/pom.xml
  google-cloud-examples/pom.xml
  google-cloud-testing/google-cloud-appengineflexcompat/pom.xml
  google-cloud-testing/google-cloud-appenginejava8/pom.xml
  google-cloud-testing/pom.xml
  google-cloud-util/google-cloud-compat-checker/pom.xml
Labels: cla: yes

#4119 Add release profile to bigtable emulator
  google-cloud-testing/google-cloud-bigtable-emulator/pom.xml
Labels: cla: yes

#4114 Add lint test and format generated code
  .kokoro/build.sh
  .kokoro/continuous/lint.cfg
  .kokoro/nightly/lint.cfg
  .kokoro/presubmit/lint.cfg
  google-cloud-clients/google-cloud-asset/synth.py
  google-cloud-clients/google-cloud-automl/synth.py
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.py
  google-cloud-clients/google-cloud-bigquerystorage/synth.py
  google-cloud-clients/google-cloud-bigtable-admin/synth.py
  google-cloud-clients/google-cloud-bigtable/synth.py
  google-cloud-clients/google-cloud-compute/synth.py
  google-cloud-clients/google-cloud-container/synth.py
  google-cloud-clients/google-cloud-containeranalysis/synth.py
  google-cloud-clients/google-cloud-dataproc/synth.py
  google-cloud-clients/google-cloud-datastore/synth.py
  google-cloud-clients/google-cloud-dialogflow/synth.py
  google-cloud-clients/google-cloud-dlp/synth.py
  google-cloud-clients/google-cloud-errorreporting/synth.py
  google-cloud-clients/google-cloud-firestore/synth.py
  google-cloud-clients/google-cloud-iot/synth.py
  google-cloud-clients/google-cloud-kms/synth.py
  google-cloud-clients/google-cloud-language/synth.py
  google-cloud-clients/google-cloud-logging/synth.py
  google-cloud-clients/google-cloud-monitoring/synth.py
  google-cloud-clients/google-cloud-os-login/synth.py
  google-cloud-clients/google-cloud-pubsub/synth.py
  google-cloud-clients/google-cloud-redis/synth.py
  google-cloud-clients/google-cloud-scheduler/synth.py
  google-cloud-clients/google-cloud-securitycenter/synth.py
  google-cloud-clients/google-cloud-spanner/synth.py
  google-cloud-clients/google-cloud-speech/synth.py
  google-cloud-clients/google-cloud-tasks/synth.py
  google-cloud-clients/google-cloud-texttospeech/synth.py
  google-cloud-clients/google-cloud-trace/synth.py
  google-cloud-clients/google-cloud-video-intelligence/synth.py
  google-cloud-clients/google-cloud-vision/synth.py
  google-cloud-clients/google-cloud-websecurityscanner/synth.py
  pom.xml
Labels: cla: yes

#4115 BigQuery: Fix TableId behaviour for non default BigQueryClient project
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
Labels: cla: yes
