Repository googleapis/google-cloud-java, pull requests merged in 2018-12, with the labels that each got.

#4120 Pub/Sub: Update ApiFutures.addCallback() to take 3 arguments
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/CreateTopicAndPublishMessages.java
Labels: cla: yes

#4167 Update maven-javadoc-plugin to 3.0.1 and disable doclint.
  google-api-grpc/pom.xml
  google-cloud-clients/google-cloud-bigtable-admin/pom.xml
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/pom.xml
  google-cloud-testing/google-cloud-bigtable-emulator/pom.xml
Labels: cla: yes

#4163 Remove the old clients compatibility chart
  README.md
Labels: cla: yes

#4165 BigQuery: insertAll always retries operation
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
Labels: cla: yes

#4174 Update Spanner description for GA
  google-cloud-clients/google-cloud-spanner/README.md
Labels: cla: yes

#4116 Storage: Close response body after request
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#4173 Storage: Fixed link to StorageExamples page
  google-cloud-clients/google-cloud-storage/README.md
Labels: cla: yes

#4176 Integration test deflake
  .kokoro/build.sh
  .kokoro/presubmit/spanner-it.cfg
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#4177 Remove exclusions for guava-jdk5 and google-api-client
  google-cloud-clients/google-cloud-bigquery/pom.xml
  google-cloud-clients/google-cloud-compute/pom.xml
  google-cloud-clients/google-cloud-core-http/pom.xml
  google-cloud-clients/google-cloud-datastore/pom.xml
  google-cloud-clients/google-cloud-dns/pom.xml
  google-cloud-clients/google-cloud-resourcemanager/pom.xml
  google-cloud-clients/google-cloud-storage/pom.xml
  google-cloud-clients/google-cloud-translate/pom.xml
Labels: cla: yes

#4170 Storage: Give users the ability to disable gzip content encoding to increase throughput
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
Labels: cla: yes

#4181 Spanner: Handle AbortedExceptions that occur before commit
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java
Labels: cla: yes

#4164 Document purpose of test-jar and testlib dependencies
  google-cloud-clients/google-cloud-asset/pom.xml
  google-cloud-clients/google-cloud-automl/pom.xml
  google-cloud-clients/google-cloud-bigquery/pom.xml
  google-cloud-clients/google-cloud-bigquerydatatransfer/pom.xml
  google-cloud-clients/google-cloud-bigquerystorage/pom.xml
  google-cloud-clients/google-cloud-bigtable-admin/pom.xml
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/google-cloud-compute/pom.xml
  google-cloud-clients/google-cloud-container/pom.xml
  google-cloud-clients/google-cloud-containeranalysis/pom.xml
  google-cloud-clients/google-cloud-core-grpc/pom.xml
  google-cloud-clients/google-cloud-core-http/pom.xml
  google-cloud-clients/google-cloud-dataproc/pom.xml
  google-cloud-clients/google-cloud-datastore/pom.xml
  google-cloud-clients/google-cloud-dialogflow/pom.xml
  google-cloud-clients/google-cloud-dlp/pom.xml
  google-cloud-clients/google-cloud-dns/pom.xml
  google-cloud-clients/google-cloud-errorreporting/pom.xml
  google-cloud-clients/google-cloud-firestore/pom.xml
  google-cloud-clients/google-cloud-iot/pom.xml
  google-cloud-clients/google-cloud-kms/pom.xml
  google-cloud-clients/google-cloud-language/pom.xml
  google-cloud-clients/google-cloud-logging/pom.xml
  google-cloud-clients/google-cloud-monitoring/pom.xml
  google-cloud-clients/google-cloud-notification/pom.xml
  google-cloud-clients/google-cloud-os-login/pom.xml
  google-cloud-clients/google-cloud-pubsub/pom.xml
  google-cloud-clients/google-cloud-redis/pom.xml
  google-cloud-clients/google-cloud-resourcemanager/pom.xml
  google-cloud-clients/google-cloud-scheduler/pom.xml
  google-cloud-clients/google-cloud-securitycenter/pom.xml
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/google-cloud-speech/pom.xml
  google-cloud-clients/google-cloud-storage/pom.xml
  google-cloud-clients/google-cloud-tasks/pom.xml
  google-cloud-clients/google-cloud-texttospeech/pom.xml
  google-cloud-clients/google-cloud-trace/pom.xml
  google-cloud-clients/google-cloud-translate/pom.xml
  google-cloud-clients/google-cloud-video-intelligence/pom.xml
  google-cloud-clients/google-cloud-vision/pom.xml
  google-cloud-clients/google-cloud-websecurityscanner/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#4168 google-cloud-bom should not need google-cloud-core test-jar
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
  google-cloud-testing/pom.xml
Labels: cla: yes

#4183 BigQuery: Allow job to extract or load table across projects
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/CopyJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExtractJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/CopyJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExtractJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
Labels: cla: yes

#4189 Bigtable: fix emulator publishing
  google-cloud-testing/google-cloud-bigtable-emulator/pom.xml
Labels: api: bigtable, cla: yes, type: bug

#4193 Regenerate container client
  google-cloud-clients/google-cloud-container/synth.metadata
Labels: cla: yes

#4194 Regenerate pubsub client
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4199 [Storage/nio] Update variable naming.
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Labels: cla: yes

#4200 Update api-common-java javadoc link.
  google-cloud-clients/pom.xml
Labels: cla: yes

#4201 Regenerate compute client
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Address.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/AuditConfig.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/AuditLogConfig.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/AuthorizationLoggingOptions.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/BackendServiceClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Binding.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Condition.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Disk.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/DiskClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Expr.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Firewall.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/FirewallLogConfig.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/GlobalSetPolicyRequest.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/ImageClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InstanceClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/LogConfig.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/LogConfigCloudAuditOptions.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/LogConfigCounterOptions.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/LogConfigDataAccessOptions.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/NodeGroupClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Policy.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/RegionDiskClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/RegionSetPolicyRequest.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Rule.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/SnapshotClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/SubnetworkClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/ZoneSetPolicyRequest.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/AddressClientTest.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/DiskClientTest.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/GlobalAddressClientTest.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/RegionDiskClientTest.java
  google-cloud-clients/google-cloud-compute/synth.metadata
Labels: cla: yes

#4202 Regenerate dataproc client
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/WorkflowTemplateServiceClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/package-info.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/WorkflowTemplateServiceClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/package-info.java
  google-cloud-clients/google-cloud-dataproc/src/test/java/com/google/cloud/dataproc/v1/WorkflowTemplateServiceClientTest.java
  google-cloud-clients/google-cloud-dataproc/src/test/java/com/google/cloud/dataproc/v1beta2/WorkflowTemplateServiceClientTest.java
  google-cloud-clients/google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4182 NIO: Enabled blocked tests. Fixed testCantCreateWithoutUserProject test.
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Labels: cla: yes

#4092 Bigtable: readRow methods added with Query as argument
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
Labels: api: bigtable, cla: yes

#4196 BigQuery : Fix setProjectId for insertAll.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
Labels: cla: yes

#4214 Pubsub: Test for blocking push subscriptions for vpc-sc enabled projects
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/it/ITPubSubTest.java
Labels: cla: yes

#4217 Bump gax version to 1.35.1
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#4216 Add IamCredentials client
  google-api-grpc/grpc-google-cloud-iamcredentials-v1/pom.xml
  google-api-grpc/grpc-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/IAMCredentialsGrpc.java
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-iamcredentials-v1/pom.xml
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateAccessTokenRequest.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateAccessTokenRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateAccessTokenResponse.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateAccessTokenResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdTokenRequest.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdTokenRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdTokenResponse.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdTokenResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/IAMCredentialsCommonProto.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/IAMCredentialsProto.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/ServiceAccountName.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignBlobRequest.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignBlobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignBlobResponse.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignBlobResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignJwtRequest.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignJwtRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignJwtResponse.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignJwtResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/proto/google/iam/credentials/v1/common.proto
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/proto/google/iam/credentials/v1/iamcredentials.proto
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-iamcredentials/README.md
  google-cloud-clients/google-cloud-iamcredentials/pom.xml
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/IamCredentialsClient.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/IamCredentialsSettings.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/package-info.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/stub/GrpcIamCredentialsCallableFactory.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/stub/GrpcIamCredentialsStub.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStub.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStubSettings.java
  google-cloud-clients/google-cloud-iamcredentials/src/test/java/com/google/cloud/iam/credentials/v1/IamCredentialsClientTest.java
  google-cloud-clients/google-cloud-iamcredentials/src/test/java/com/google/cloud/iam/credentials/v1/MockIAMCredentials.java
  google-cloud-clients/google-cloud-iamcredentials/src/test/java/com/google/cloud/iam/credentials/v1/MockIAMCredentialsImpl.java
  google-cloud-clients/google-cloud-iamcredentials/synth.metadata
  google-cloud-clients/google-cloud-iamcredentials/synth.py
  google-cloud-clients/pom.xml
  versions.txt
Labels: cla: yes

#4227 BigQuery : Fix setProjectId
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableInfo.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/WriteChannelConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableInfoTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/WriteChannelConfigurationTest.java
Labels: cla: yes

#4230 BigQuery: Add BadRecords to LoadStatistics
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
Labels: cla: yes

#4111 Add script to help bootstrap new client libraries
  utilities/new_client.py
  utilities/requirements.txt
  utilities/templates/README.md
  utilities/templates/cloud_pom.xml
  utilities/templates/grpc_pom.xml
  utilities/templates/proto_pom.xml
  utilities/templates/synth.py
Labels: cla: yes

#4236 Update javadoc link for api-common-java.
  google-cloud-clients/pom.xml
Labels: cla: yes

#4238 IAMCredentials: Fix name/description in pom
  google-cloud-clients/google-cloud-iamcredentials/pom.xml
Labels: cla: yes

#4264 Bigtable: add a separate callable for point reads
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/ReadIT.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
Labels: api: bigtable, cla: yes

#4263 Spanner: closed watch-dog daemon threads spawned by Spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Labels: api: spanner, cla: yes
