Repository googleapis/google-cloud-java, pull requests merged in 2018-09, with the labels that each got.

#3569 Bigtable: add CRUD for instances
  google-cloud-clients/google-cloud-bigtable-admin/pom.xml
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateInstanceRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/Instance.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/PartialListInstancesException.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateInstanceRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequestTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/InstanceTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateInstanceRequestTest.java
Labels: cla: yes

#3570 Bigtable: clean up consistency token
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/ConsistencyToken.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/ConsistencyTokenTest.java
Labels: cla: yes

#3612 Bigtable: add CRUD for clusters
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/Cluster.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/PartialListClustersException.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/ClusterTest.java
Labels: cla: yes

#3619 Bigtable: add CRUD for AppProfiles
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/AppProfile.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateAppProfileRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateAppProfileRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/AppProfileTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateAppProfileRequestTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateAppProfileRequestTest.java
Labels: cla: yes

#3611 spanner: Add snippets for Spanner, BatchClient and BatchReadOnlyTransaction
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchReadOnlyTransaction.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Spanner.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/spanner/snippets/BatchClientSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/spanner/snippets/SpannerSnippets.java
Labels: cla: yes

#3557 google-cloud-nio: retry on 502 errors, and increase max depth when doing channel reopens
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java
Labels: cla: yes

#3546 Update signUrl documentation.
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
Labels: cla: yes, type: docs

#3624 Bigtable: add resource level IAM
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTest.java
Labels: cla: yes

#3387 make DatastoreBatchWriter public
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreBatchWriter.java
Labels: cla: yes

#3633 Pubsub: Clean up after message extension gives up
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDispatcherTest.java
Labels: cla: yes

#3574 [Storage] Bucket lock
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BlobInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes, do not merge

#3641 Fix logging integration test failure on when running on GCE
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/BaseSystemTest.java
Labels: cla: yes

#3645 [Storage] Replay GCS Bucket Lock
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BlobInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#3640 Bigtable: table model improvements
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/ClusterState.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/ColumnFamily.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/GCRules.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/Table.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/TableTest.java
Labels: cla: yes

#3638 Bigtable: cosmetic cleanup of table admin
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
Labels: cla: yes

#3639 Bigtable: improve list tables spooler
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
Labels: cla: yes

#3650 tell JVM to use less memory when testing
  .circleci/config.yml
Labels: cla: yes

#3652 Javadoc fixes for Bigtable client
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
Labels: cla: yes

#3643 Fix #3637 Bigtable RowMutation should allow passing of a Mutation
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowMutation.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/RowMutationTest.java
Labels: cla: yes

#3660 Adding integration test for Compute GAPIC
  google-cloud-clients/google-cloud-compute/pom.xml
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/it/ITComputeTest.java
Labels: cla: yes

#3654 Releasing.md instructions to uncomment nexus-staging-maven-plugin
  RELEASING.md
Labels: cla: yes

#3667 Fix ComputeIT tests
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/it/ITComputeTest.java
Labels: cla: yes

#3670 Add redis-v1 and video-intelligence-v1p2beta1 to batch
  utilities/batch_generate_apis.py
Labels: cla: yes

#3675 update gax to 1.31/0.48
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#3664 Add Kokoro CI config
  .kokoro/build.bat
  .kokoro/build.sh
  .kokoro/common.cfg
  .kokoro/continuous/bigquery-it.cfg
  .kokoro/continuous/bigtable-it.cfg
  .kokoro/continuous/bigtableadmin-it.cfg
  .kokoro/continuous/common.cfg
  .kokoro/continuous/compute-it.cfg
  .kokoro/continuous/datastore-it.cfg
  .kokoro/continuous/dns-it.cfg
  .kokoro/continuous/firestore-it.cfg
  .kokoro/continuous/java10.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/java8.cfg
  .kokoro/continuous/javadoc.cfg
  .kokoro/continuous/logging-it.cfg
  .kokoro/continuous/notification-it.cfg
  .kokoro/continuous/pubsub-it.cfg
  .kokoro/continuous/spanner-it.cfg
  .kokoro/continuous/speech-it.cfg
  .kokoro/continuous/storage-it.cfg
  .kokoro/continuous/translate-it.cfg
  .kokoro/presubmit/bigquery-it.cfg
  .kokoro/presubmit/bigtable-it.cfg
  .kokoro/presubmit/bigtableadmin-it.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/compute-it.cfg
  .kokoro/presubmit/datastore-it.cfg
  .kokoro/presubmit/dns-it.cfg
  .kokoro/presubmit/firestore-it.cfg
  .kokoro/presubmit/java10.cfg
  .kokoro/presubmit/java11.cfg
  .kokoro/presubmit/java7.cfg
  .kokoro/presubmit/java8-win.cfg
  .kokoro/presubmit/java8.cfg
  .kokoro/presubmit/javadoc.cfg
  .kokoro/presubmit/logging-it.cfg
  .kokoro/presubmit/notification-it.cfg
  .kokoro/presubmit/pubsub-it.cfg
  .kokoro/presubmit/spanner-it.cfg
  .kokoro/presubmit/speech-it.cfg
  .kokoro/presubmit/storage-it.cfg
  .kokoro/presubmit/translate-it.cfg
  .kokoro/trampoline.sh
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#3662 spanner: Add snippets for ReadContext
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/ReadContext.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/spanner/snippets/ReadContextSnippets.java
Labels: cla: yes

#3681 link to google-cloud-logging from README
  google-cloud-clients/google-cloud-contrib/README.md
Labels: cla: yes

#3671 [Storage Snippet] Include information on a bucket prefix
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
Labels: cla: yes

#3689 [Storage Snippets] Add downloadFile sample and reformat storage snippets
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: cla: yes

#3688 pubsub: add Publisher.awaitTermination
  google-cloud-clients/google-cloud-pubsub/README.md
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/it/ITPubSubTest.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/CreateTopicAndPublishMessages.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/PublisherSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/pubsub/snippets/ITPubSubSnippets.java
Labels: cla: yes

#3686 Expand test coverage for getDatabaseClient()
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
Labels: cla: yes

#3685 Kokoro additions
  .kokoro/continuous/java8-osx.cfg
  .kokoro/presubmit/java8-osx.cfg
  README.md
  google-cloud-clients/pom.xml
Labels: cla: yes

#3691 Bigtable: add enhanced stub for bigtable table admin client
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/stub/EnhancedBigtableTableAdminStub.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
Labels: cla: yes

#3659 Bigtable: wrap proto enums
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/Cluster.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateInstanceRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/Instance.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/StorageType.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/Table.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/ClusterTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequestTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/InstanceTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/StorageTypeTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/TableTest.java
Labels: cla: yes

#3694 Fixes GoogleCloudPlatform/google-cloud-java#3283.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableId.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableIdTest.java
Labels: cla: yes

#3695 Bigtable: limit mutation sizes in the client to avoid overloading the server
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Mutation.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/MutationTest.java
Labels: cla: yes

#3684 Clean up snippets for BatchClient and Spanner
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchReadOnlyTransaction.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Spanner.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/spanner/snippets/BatchClientSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/spanner/snippets/SpannerSnippets.java
Labels: cla: yes

#3700 Migrate Pub/Sub client to ApiFutures.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
Labels: cla: yes

#3628 Spanner: Block nested transactions
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunner.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionTest.java
Labels: cla: yes

#3705 [Storage] Add region tags around an informative upload sample.
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/CreateBlob.java
Labels: cla: yes

#3704 Add ArrayUnion/ArrayRemove conformance tests
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/resources/test-suite.binproto
Labels: cla: yes

#3718 bump proto version
  google-api-grpc/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#3709 [Storage] Bucket lock samples and bug fixes.
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/testing/RemoteStorageHelper.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: cla: yes

#3724 Remove dependency on vulnerable version of jackson, upgrade to jackson2
  google-cloud-clients/google-cloud-bigquery/src/benchmark/java/com/google/cloud/bigquery/benchmark/Benchmark.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/spi/v1/HttpComputeRpc.java
  google-cloud-clients/google-cloud-core-http/pom.xml
  google-cloud-clients/google-cloud-dns/src/main/java/com/google/cloud/dns/spi/v1/HttpDnsRpc.java
  google-cloud-clients/google-cloud-resourcemanager/src/main/java/com/google/cloud/resourcemanager/spi/v1beta1/HttpResourceManagerRpc.java
  google-cloud-clients/google-cloud-resourcemanager/src/main/java/com/google/cloud/resourcemanager/testing/LocalResourceManagerHelper.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-translate/src/main/java/com/google/cloud/translate/spi/v2/HttpTranslateRpc.java
  google-cloud-clients/pom.xml
Labels: cla: yes

#3723 Remove Circle CI and Travis configs
  .circleci/config.yml
  .circleci/firestore-it-service-account.json.enc
  .circleci/it-service-account.json.enc
  appveyor.yml
Labels: cla: yes

#3706 spanner: Options: Fix null dereference, expand test coverage
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/OptionsTest.java
Labels: cla: yes

#3732 Remove duplicated folders
  google-api-grpc/grpc-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/AssetServiceGrpc.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/Asset.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/AssetOrBuilder.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/AssetProto.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/AssetServiceProto.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/BatchGetAssetsHistoryRequest.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/BatchGetAssetsHistoryRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/BatchGetAssetsHistoryResponse.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/BatchGetAssetsHistoryResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ContentType.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ExportAssetsRequest.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ExportAssetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ExportAssetsResponse.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ExportAssetsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/GcsDestination.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/GcsDestinationOrBuilder.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/OutputConfig.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/OutputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ProjectName.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/Resource.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ResourceOrBuilder.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/TemporalAsset.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/TemporalAssetOrBuilder.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/TimeWindow.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/TimeWindowOrBuilder.java
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/proto/google/cloud/asset/v1beta1/asset_service.proto
  google-api-grpc/proto-google-cloud-cloudasset-v1beta1/src/main/proto/google/cloud/asset/v1beta1/assets.proto
  google-cloud-clients/google-cloud-cloudasset/src/main/java/com/google/cloud/asset/v1beta1/AssetServiceClient.java
  google-cloud-clients/google-cloud-cloudasset/src/main/java/com/google/cloud/asset/v1beta1/AssetServiceSettings.java
  google-cloud-clients/google-cloud-cloudasset/src/main/java/com/google/cloud/asset/v1beta1/package-info.java
  google-cloud-clients/google-cloud-cloudasset/src/main/java/com/google/cloud/asset/v1beta1/stub/AssetServiceStub.java
  google-cloud-clients/google-cloud-cloudasset/src/main/java/com/google/cloud/asset/v1beta1/stub/AssetServiceStubSettings.java
  google-cloud-clients/google-cloud-cloudasset/src/main/java/com/google/cloud/asset/v1beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-clients/google-cloud-cloudasset/src/main/java/com/google/cloud/asset/v1beta1/stub/GrpcAssetServiceStub.java
  google-cloud-clients/google-cloud-cloudasset/src/test/java/com/google/cloud/asset/v1beta1/AssetServiceClientTest.java
  google-cloud-clients/google-cloud-cloudasset/src/test/java/com/google/cloud/asset/v1beta1/MockAssetService.java
  google-cloud-clients/google-cloud-cloudasset/src/test/java/com/google/cloud/asset/v1beta1/MockAssetServiceImpl.java
Labels: cla: yes

#3703 Cloud Spanner DML & PartitionedDML support
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResultSet.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContext.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GrpcSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java
Labels: cla: yes

#3741 Revert "Cloud Spanner DML & PartitionedDML support (#3703)"
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResultSet.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContext.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GrpcSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java
Labels: cla: yes

#3690 Fix parent/child spans relationship in Spanner.
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResumableStreamIteratorTest.java
Labels: cla: yes

#3725 spanner: Expand test coverage for SpannerClient
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/SpannerClientTest.java
Labels: cla: yes

#3702 Expand test coverage for GrpcResultSet and runWithRetries()
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
Labels: cla: yes

#3727 [Storage] Bucket Lock
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/testing/RemoteStorageHelper.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BlobInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: api: storage, cla: yes
