Repository googleapis/google-cloud-java, pull requests merged in 2019-05, with the labels that each got.

#5041 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/RunAssetDiscoveryResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/RunAssetDiscoveryResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/RunAssetDiscoveryResponseOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/run_asset_discovery_response.proto
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4652 Firestore: Adding Collection Group queries
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: :rotating_light:, api: firestore, cla: yes

#5044 Pub/Sub: more refactoring
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#5003 Update maven-checkstyle-plugin and puppycrawl checkstyle
  .kokoro/build.sh
  google-cloud-clients/pom.xml
  google-cloud-util/google-cloud-compat-checker/pom.xml
Labels: :rotating_light:, cla: yes, type: cleanup

#4784 Logging: call flush before close
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java
Labels: :rotating_light:, cla: yes, do not merge

#5045 Add links to new and missing libraries to main README
  README.md
  google-cloud-clients/google-cloud-datacatalog/pom.xml
Labels: cla: yes, type: docs

#5049 Regenerate phishingprotection client
  google-cloud-clients/google-cloud-phishingprotection/synth.metadata
Labels: cla: yes

#5046 Adding resume publish.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
Labels: cla: yes

#5051 BigQuery Storage: Fix the URL of the client library documentation
  google-cloud-clients/google-cloud-bigquerystorage/README.md
Labels: cla: yes

#5042 Migrate from containsAllIn to containsAtLeastElementsIn.
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/gaxx/reframing/ReframingResponseObserverTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionTest.java
  google-cloud-clients/pom.xml
Labels: cla: yes, type: cleanup

#5052 bigquery: deprecate ambiguous usage of delete in BigQuery client.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
Labels: cla: yes

#5060 Spanner: fix possible thread leak in Spanner.close()
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: cla: yes

#5057 Monitoring: Regenerate VPCSC tests to include NotificationChannelService and UptimeCheckService.
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/VPCServiceControlTest.java
Labels: cla: yes

#5064 Regenerate video-intelligence client
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/package-info.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceClientTest.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceSmokeTest.java
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#5063 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#5056 Add 404 page which redirects to the new javadocs site
  .gitignore
  404.html
  package.json
  src/redirects.js
  test/redirects.js
Labels: cla: yes, type: docs

#5073 Regenerate containeranalysis client
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1beta1/ContainerAnalysisV1Beta1Client.java
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
Labels: cla: yes

#5074 Regenerate iot client
  google-cloud-clients/google-cloud-iot/src/main/java/com/google/cloud/iot/v1/DeviceManagerClient.java
  google-cloud-clients/google-cloud-iot/synth.metadata
Labels: cla: yes

#5075 Regenerate kms client
  google-cloud-clients/google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceClient.java
  google-cloud-clients/google-cloud-kms/synth.metadata
Labels: cla: yes

#5077 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClient.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#5078 Regenerate tasks client
  google-cloud-clients/google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2/CloudTasksClient.java
  google-cloud-clients/google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta2/CloudTasksClient.java
  google-cloud-clients/google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta3/CloudTasksClient.java
  google-cloud-clients/google-cloud-tasks/synth.metadata
Labels: cla: yes

#5072 Regenerate bigtable client
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BaseBigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable/synth.metadata
Labels: cla: yes

#5067 Cloud Scheduler beta
  README.md
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-bigquerystorage/pom.xml
  google-cloud-clients/google-cloud-scheduler/pom.xml
  versions.txt
Labels: cla: yes

#5062 Regenerate pubsub client
  google-api-grpc/grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublisherGrpc.java
  google-api-grpc/grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriberGrpc.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/CreateSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSnapshotsRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSnapshotsResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSnapshotsRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSnapshotsResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PushConfig.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SeekRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Snapshot.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriptionOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Topic.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UpdateSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/TopicAdminClientTest.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#5069 Promote Tasks client GA
  README.md
  google-api-grpc/grpc-google-cloud-tasks-v2/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-tasks-v2/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-tasks/README.md
  google-cloud-clients/google-cloud-tasks/pom.xml
  versions.txt
Labels: cla: yes

#5076 Regenerate scheduler client
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/HttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/HttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/Job.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/JobOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/JobProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/OAuthToken.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/OAuthTokenOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/OidcToken.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/OidcTokenOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/SchedulerProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/TargetProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/proto/google/cloud/scheduler/v1/cloudscheduler.proto
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/proto/google/cloud/scheduler/v1/job.proto
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/proto/google/cloud/scheduler/v1/target.proto
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#5110 Regenerate talent client
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Application.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ApplicationOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/EmploymentRecord.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/EmploymentRecordOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobQuery.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobQueryOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobResourceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Location.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/PersonName.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/PersonNameOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Profile.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileResourceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ResponseMetadata.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Resume.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ResumeOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/SearchProfilesRequest.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/SearchProfilesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/SpellingCorrection.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Tenant.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/TenantOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/TenantResourceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/application.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/common.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/filters.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/job.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/profile.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/profile_service.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/tenant.proto
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ApplicationServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompanyServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompletionStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/EventServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/JobServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ProfileServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/TenantServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/ProfileServiceClientTest.java
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#5104 Regenerate pubsub client
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#5124 update api docs link
  google-cloud-clients/google-cloud-tasks/README.md
Labels: cla: yes

#5128 Update apiary version dependencies
  google-cloud-clients/google-cloud-storage/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#5021 BigQuery: adds models API implementation.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Model.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ModelId.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ModelInfo.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/testing/RemoteBigQueryHelper.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ModelIdTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ModelInfoTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ModelTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: :rotating_light:, api: bigquery, cla: yes, do not merge

#5079 [Bigtable] CreateTableRequest equals and hashCode with unit test
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequestTest.java
Labels: api: bigtable, cla: yes

#5171 Regenerate video-intelligence client
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/package-info.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceClientTest.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceSmokeTest.java
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#5125 [Bigtable] Added StreamController cancel in readRowsAsync docs
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
Labels: cla: yes

#5174 Regenerate tasks client
  google-api-grpc/grpc-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CloudTasksGrpc.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CloudTasksProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/HttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/HttpRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListQueuesRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListQueuesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListTasksRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListTasksRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/OidcToken.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Queue.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/QueueOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/QueueProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/StackdriverLoggingConfig.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/StackdriverLoggingConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Task.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TaskOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/cloudtasks.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/queue.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/target.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/task.proto
  google-cloud-clients/google-cloud-tasks/src/test/java/com/google/cloud/tasks/v2beta3/CloudTasksClientTest.java
  google-cloud-clients/google-cloud-tasks/synth.metadata
Labels: cla: yes

#5176 Migrate from assertThat(foo).named("foo") to assertWithMessage("foo").that(foo).
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractStructReaderTypesTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TimestampBoundTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueBinderTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITReadTest.java
Labels: cla: yes

#5175 Regenerate vision client
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/InputConfig.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/InputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/image_annotator.proto
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#5170 Regenerate talent client
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ApplicationServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompanyServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompletionStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/EventServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/JobServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ProfileServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/TenantServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#5169 Regenerate pubsub client
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#5138 Regenerate datacatalog client
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/DataCatalogStubSettings.java
  google-cloud-clients/google-cloud-datacatalog/synth.metadata
Labels: cla: yes

#4734 Spanner: Re-create sessions that have been invalidated by the server
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingResultSet.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingStructReader.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionNotFoundException.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/BaseSessionPoolTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestWithClosedSessionsEnv.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java
Labels: api: spanner, cla: yes, needs work

#5173 Fix documentation around updating blob metadata
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
Labels: cla: yes

#5172 Migrate from isSameAs to isSameInstanceAs (and isNotSameAs to isNotSameInstanceAs).
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MutationTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TypeTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
Labels: cla: yes

#5066 [Bigtable] GCRules.GCRule Javadoc fix for createTable
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequest.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/GCRules.java
Labels: :rotating_light:, api: bigtable, cla: yes

#5184 Regenerate tasks client - comments reformatted
  google-api-grpc/grpc-google-cloud-tasks-v2/src/main/java/com/google/cloud/tasks/v2/CloudTasksGrpc.java
  google-api-grpc/grpc-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CloudTasksGrpc.java
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/java/com/google/cloud/tasks/v2/AppEngineHttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/java/com/google/cloud/tasks/v2/CloudTasksProto.java
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/java/com/google/cloud/tasks/v2/ListQueuesRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/java/com/google/cloud/tasks/v2/ListQueuesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/java/com/google/cloud/tasks/v2/ListTasksRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/java/com/google/cloud/tasks/v2/ListTasksRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/proto/google/cloud/tasks/v2/cloudtasks.proto
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/proto/google/cloud/tasks/v2/queue.proto
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/proto/google/cloud/tasks/v2/target.proto
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/proto/google/cloud/tasks/v2/task.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/HttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/HttpRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/OAuthToken.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/OidcToken.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/cloudtasks.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/target.proto
  google-cloud-clients/google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2/CloudTasksClient.java
  google-cloud-clients/google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta3/CloudTasksClient.java
  google-cloud-clients/google-cloud-tasks/synth.metadata
Labels: cla: yes

#5182 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionMetadata.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionMetadataOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechProto.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognitionResult.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognitionResultOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/proto/google/cloud/speech/v1/cloud_speech.proto
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#5180 Regenerate datacatalog client
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/DataCatalogStubSettings.java
  google-cloud-clients/google-cloud-datacatalog/synth.metadata
Labels: cla: yes

#5167 Spanner use custom thread factory
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITSpannerOptionsTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: cla: yes

#5178 Bigtable: Update javadoc
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettings.java
Labels: api: bigtable, cla: yes, type: docs

#5183 Regenerate talent client
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ProfileServiceClient.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ProfileServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#5168 Regenerate dialogflow client
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBasesClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/DocumentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/DocumentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcDocumentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/DocumentsClientTest.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBasesClientTest.java
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#5194 Core: Default executor used non-daemon threads
  google-cloud-clients/google-cloud-core-grpc/src/main/java/com/google/cloud/grpc/GrpcTransportOptions.java
Labels: cla: yes

#5206 Regenerate dialogflow client
  google-api-grpc/grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsGrpc.java
  google-api-grpc/grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBasesGrpc.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/AgentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ContextProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/EntityTypeProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/Intent.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/IntentOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/IntentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/QueryResult.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/QueryResultOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SessionEntityTypeProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SessionProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/agent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/context.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/entity_type.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/intent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/session.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/session_entity_type.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ContextProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/Document.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/EntityTypeProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/Intent.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/IntentOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/IntentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBase.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBaseProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/QueryResult.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/QueryResultOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionEntityTypeProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/agent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/context.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/document.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/entity_type.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/intent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/knowledge_base.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/session.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/session_entity_type.proto
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBasesClient.java
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#5199 Regenerate vision client
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/Product.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchParams.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchParamsOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search_service.proto
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/Product.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ProductOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchParams.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchParamsOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/product_search.proto
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/product_search_service.proto
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#5193 Trace: add VPC SC test
  google-cloud-clients/google-cloud-trace/src/test/java/com/google/cloud/trace/v1/VPCServiceControlTest.java
  google-cloud-clients/google-cloud-trace/src/test/java/com/google/cloud/trace/v2/VPCServiceControlTest.java
Labels: cla: yes

#5029 Allow colons in Identity values
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/Identity.java
  google-cloud-clients/google-cloud-core/src/test/java/com/google/cloud/IdentityTest.java
Labels: :rotating_light:, cla: yes

#5208 Update maven config to include *.proto files in jars
  google-api-grpc/pom.xml
  google-cloud-clients/google-cloud-firestore/pom.xml
Labels: cla: yes

#5213 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechContext.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechContextOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechProto.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#5215 Remove bigtable samples from here (moved to java-docs-samples)
  google-cloud-examples/pom.xml
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigtable/HelloWorld.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigtable/InstanceAdminExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigtable/TableAdminExample.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigtable/ITHelloWorld.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigtable/ITInstanceAdminExample.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigtable/ITTableAdminExample.java
Labels: cla: yes

#5216 Add initial integration test for BigQuery Storage API.
  .kokoro/continuous/bigquery-storage-it.cfg
  .kokoro/nightly/bigquery-storage-it.cfg
  .kokoro/presubmit/bigquery-storage-it.cfg
  google-cloud-clients/google-cloud-bigquerystorage/pom.xml
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/it/ITBigQueryStorageTest.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/it/SimpleRowReader.java
Labels: cla: yes

#5214 BigQuery: Augment BQ Model metadata.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Model.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ModelInfo.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ModelInfoTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#5218 Regenerate pubsub client
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#5219 bigquerystorage: excise retry expectations in tests for DEADLINE_EXCEEDED
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/EnhancedBigQueryStorageStubSettingsTest.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ReadRowsRetryTest.java
Labels: cla: yes

#5220 bigquery examples: update snippets to use preferred form of delete().
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITDatasetSnippets.java
Labels: cla: yes

#5223 Regenerate vision client
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/Product.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchParams.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchParamsOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search_service.proto
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/Product.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ProductOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchParams.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchParamsOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/product_search.proto
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/product_search_service.proto
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#5222 Regenerate dataproc client
  google-api-grpc/grpc-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/WorkflowTemplateServiceGrpc.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/ClusterConfig.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/ClusterConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/ClustersProto.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/Component.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/CreateClusterRequest.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/CreateClusterRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/DeleteClusterRequest.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/DeleteClusterRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/GceClusterConfig.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/GceClusterConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/JobReference.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/JobReferenceOrBuilder.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/OrderedJob.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/OrderedJobOrBuilder.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/SharedProto.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/SoftwareConfig.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/SoftwareConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/SubmitJobRequest.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/SubmitJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/TemplateParameter.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/TemplateParameterOrBuilder.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/UpdateClusterRequest.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/UpdateClusterRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/proto/google/cloud/dataproc/v1/clusters.proto
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/proto/google/cloud/dataproc/v1/jobs.proto
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/proto/google/cloud/dataproc/v1/operations.proto
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/proto/google/cloud/dataproc/v1/shared.proto
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/proto/google/cloud/dataproc/v1/workflow_templates.proto
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/WorkflowTemplateServiceClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/WorkflowTemplateServiceClient.java
  google-cloud-clients/google-cloud-dataproc/src/test/java/com/google/cloud/dataproc/v1/WorkflowTemplateServiceClientTest.java
  google-cloud-clients/google-cloud-dataproc/src/test/java/com/google/cloud/dataproc/v1beta2/WorkflowTemplateServiceClientTest.java
  google-cloud-clients/google-cloud-dataproc/synth.metadata
Labels: cla: yes

#5198 Regenerate bigquerystorage client
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/BigQueryStorageStubSettings.java
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
Labels: cla: yes

#5204 Update NIO to understand new directory stand-ins
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageOptions.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/OptionAllowTrailingSlash.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java
Labels: cla: yes

#4940 Spanner: Use gax for retries
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceAdminClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/BatchClientImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplRetryTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
Labels: :rotating_light:, cla: yes

#5229 Regenerate dataproc client
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/ClustersProto.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/proto/google/cloud/dataproc/v1/clusters.proto
  google-cloud-clients/google-cloud-dataproc/synth.metadata
Labels: cla: yes

#5237 Bigtable: Using undeprecated Truth methods.
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettingsTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettingsTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/stub/AwaitReplicationCallableTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptorTest.java
Labels: cla: yes

#5234 Pub/Sub: Fixing Subscriber's system executor config
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: cla: yes

#5240 BigQuery:Fix deprecated warnings removed
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#5241 Nio:Fix deprecated warnings removed
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/UnixPathTest.java
Labels: cla: yes

#5248 Upgrading grpc and opencensus
  google-api-grpc/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#5259 Clean up test deprecation warnings for google-cloud-core
  google-cloud-clients/google-cloud-core/src/test/java/com/google/cloud/StringEnumTest.java
Labels: cla: yes
