Repository googleapis/google-cloud-java, pull requests merged in 2019-02, with the labels that each got.

#4421 Bigtable: make row & cell ordering more consistent.
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/DefaultRowAdapter.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Row.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowCell.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/ReadModifyWriteRowCallable.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/DefaultRowAdapterTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/RowCellTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/RowTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/ReadModifyWriteRowCallableTest.java
Labels: api: bigtable, cla: yes, type: feature request

#4437 Fix code formatting
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ImageClassificationDatasetMetadata.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextClassificationDatasetMetadata.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSource.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferRunsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferMessage.java
  google-api-grpc/proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/Cell.java
  google-api-grpc/proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/Row.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/discovery/Discovered.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Key.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/EntityType.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SessionEntityType.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/StreamingRecognitionResult.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/EntityType.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeAnswers.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionEntityType.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/StreamingRecognitionResult.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/RecordCondition.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/TransformationSummary.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ListGroupStatsRequest.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/StructuredQuery.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/PublicKeyCertificate.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersion.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersionTemplate.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KeyOperationAttestation.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListCryptoKeyVersionsRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListCryptoKeysRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/PublicKey.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/NotificationChannel.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Topic.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/ListAssetsResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/OrganizationSettings.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognizeResponse.java
  google-api-grpc/proto-google-cloud-speech-v1beta1/src/main/java/com/google/cloud/speech/v1beta1/StreamingRecognizeResponse.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionMetadata.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognizeResponse.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta1/src/main/java/com/google/cloud/videointelligence/v1beta1/VideoContext.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta2/src/main/java/com/google/cloud/videointelligence/v1beta2/LabelDetectionConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p1beta1/src/main/java/com/google/cloud/videointelligence/v1p1beta1/LabelDetectionConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p2beta1/src/main/java/com/google/cloud/videointelligence/v1p2beta1/LabelDetectionConfig.java
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/ProductSearchParams.java
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/ProductSearchResults.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanRun.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/conformance/TestDefinition.java
Labels: cla: yes

#4426 Regenerate asset client
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/AssetServiceClient.java
  google-cloud-clients/google-cloud-asset/synth.metadata
Labels: cla: yes

#4427 Regenerate bigtable client
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BaseBigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BaseBigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4428 Regenerate dataproc client
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/ClusterControllerClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/WorkflowTemplateServiceClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/ClusterControllerClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/WorkflowTemplateServiceClient.java
  google-cloud-clients/google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4422 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechProto.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/proto/google/cloud/speech/v1/cloud_speech.proto
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#4431 Regenerate redis client
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisClient.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisClient.java
  google-cloud-clients/google-cloud-redis/synth.metadata
Labels: cla: yes

#4432 Regenerate securitycenter client
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClient.java
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4411 Regenerate tasks client
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineRouting.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Attempt.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AttemptOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/HttpMethod.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Queue.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/QueueOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TargetProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Task.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TaskOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TaskProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/queue.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/target.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/task.proto
  google-cloud-clients/google-cloud-tasks/synth.metadata
Labels: cla: yes

#4453 Fix usages of any(<Primitive>.class) matchers
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/BaseSessionPoolTest.java
Labels: cla: yes

#4434 Regenerate video-intelligence client
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta1/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta2/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p1beta1/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p2beta1/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#4455 Regenerate automl client
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/AutoMlClient.java
  google-cloud-clients/google-cloud-automl/synth.metadata
Labels: cla: yes

#4456 Regenerate speech client
  google-cloud-clients/google-cloud-speech/src/main/java/com/google/cloud/speech/v1/SpeechClient.java
  google-cloud-clients/google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechClient.java
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#4425 Update some default retry setting values
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/PublisherSnippets.java
Labels: cla: yes

#4404 Implement BucketPolicyOnly
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
  google-cloud-clients/pom.xml
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: cla: yes

#4459 Bigtable: make request context serializable
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/RequestContext.java
Labels: cla: yes

#4333 Regenerate texttospeech client
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1/TextToSpeechSmokeTest.java
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1beta1/TextToSpeechSmokeTest.java
  google-cloud-clients/google-cloud-texttospeech/synth.metadata
Labels: cla: yes

#4392 Skip integration tests if no changes
  .kokoro/build.sh
  .kokoro/common.cfg
  .kokoro/presubmit/common.cfg
Labels: cla: yes

#4409 update TESTING.md
  TESTING.md
Labels: cla: yes

#4433 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClient.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#4463 Regenerate texttospeech client
  google-api-grpc/grpc-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/TextToSpeechGrpc.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/AudioConfig.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/AudioConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/TextToSpeechProto.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/proto/google/cloud/texttospeech/v1/cloud_tts.proto
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/TextToSpeechClient.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/TextToSpeechSettings.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/package-info.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/stub/GrpcTextToSpeechCallableFactory.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/stub/GrpcTextToSpeechStub.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/stub/TextToSpeechStub.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/stub/TextToSpeechStubSettings.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/TextToSpeechClient.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/TextToSpeechSettings.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/package-info.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/stub/GrpcTextToSpeechCallableFactory.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/stub/GrpcTextToSpeechStub.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/stub/TextToSpeechStub.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/stub/TextToSpeechStubSettings.java
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1/MockTextToSpeech.java
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1/MockTextToSpeechImpl.java
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1/TextToSpeechClientTest.java
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1/TextToSpeechSmokeTest.java
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1beta1/MockTextToSpeech.java
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1beta1/MockTextToSpeechImpl.java
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1beta1/TextToSpeechClientTest.java
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1beta1/TextToSpeechSmokeTest.java
  google-cloud-clients/google-cloud-texttospeech/synth.metadata
Labels: cla: yes

#4439 3534: Made HttpTransportOptions constructor public.
  google-cloud-clients/google-cloud-core-http/src/main/java/com/google/cloud/http/HttpTransportOptions.java
Labels: cla: yes

#4460 Use gax 1.38.0
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#4185 Empty table results can have a schema
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/EmptyTableResult.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
Labels: cla: yes, needs tests

#4407 4273: Added a new create method to pass offset and length of sub array.
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: cla: yes

#4464 Add firestore grpc and proto versions to versions.txt
  versions.txt
Labels: cla: yes

#4461 Adding Cloud Bigtable Mutation fromProto
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Mutation.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/MutationTest.java
Labels: cla: yes

#4435 Regenerate websecurityscanner client
  google-cloud-clients/google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerClient.java
  google-cloud-clients/google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/package-info.java
  google-cloud-clients/google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerClientTest.java
  google-cloud-clients/google-cloud-websecurityscanner/synth.metadata
Labels: cla: yes

#4424 Fixes #4423 - Getter on mutations size
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/WriteBatchTest.java
Labels: :rotating_light:, cla: yes, status: blocked

#4315 Add SequentialExecutorService that assists Pub/Sub to publish messages sequentially
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SequentialExecutorServiceTest.java
Labels: :rotating_light:, cla: yes

#4473 Spanner: Add condition for date in Key.toProto
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Key.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/KeyTest.java
Labels: cla: yes

#4413 Set connect/read timeout when calling the metadata service
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/MetadataConfig.java
Labels: :rotating_light:, cla: yes

#4397 4117: Added Md5String() method and updated tests.
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BlobInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: :rotating_light:, cla: yes

#4471 Removing joda
  google-cloud-clients/google-cloud-compute/pom.xml
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/AddressInfo.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/DeprecationStatus.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/DiskInfo.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/DiskType.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/ImageInfo.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/InstanceInfo.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/MachineType.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/NetworkInfo.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/Operation.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/Region.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/SnapshotInfo.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/SubnetworkInfo.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/deprecated/Zone.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/deprecated/DeprecationStatusTest.java
  google-cloud-clients/pom.xml
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/CloudSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/dns/DnsExample.java
Labels: cla: yes

#4484 VPC Tests
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITVPCNegativeTest.java
Labels: cla: yes

#4488 Regenerate websecurityscanner client
  google-cloud-clients/google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerClient.java
  google-cloud-clients/google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/package-info.java
  google-cloud-clients/google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerClientTest.java
  google-cloud-clients/google-cloud-websecurityscanner/synth.metadata
Labels: cla: yes

#4487 Regenerate pubsub client
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4497 Remove duplicate span.end() causing log pollution.
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
Labels: cla: yes

#4491 [Bigtable] Added HeaderProvider onto ClientContext#create settings
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/ResourceHeaderTest.java
Labels: cla: yes

#4496 Bump gax-java dependency
  google-api-grpc/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#4474 Add ordered publishing support to Cloud Pub/Sub
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessage.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessageOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriptionOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakePublisherServiceImpl.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
Labels: cla: yes

#4507 Bigtable: Expose the default transport builder
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
Labels: api: bigtable, cla: yes

#4505 Bigtable: Remove deprecated typesafe names
  google-cloud-clients/google-cloud-bigtable/README.md
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/RequestContext.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/InstanceName.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
  google-cloud-testing/google-cloud-bigtable-emulator/README.md
Labels: api: bigtable, cla: yes

#4511 Regenerate kms client
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KeyOperationAttestation.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KmsResourcesProto.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/proto/google/cloud/kms/v1/resources.proto
  google-cloud-clients/google-cloud-kms/synth.metadata
Labels: cla: yes

#4489 BigQuery: Fix support standard java date in QueryParameterValue classToType
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
Labels: cla: yes

#4518 Fix broken link to DEVELOPING.md
  google-cloud-clients/google-cloud-bigtable/README.md
Labels: cla: yes

#4517 Add KMS IT test and kokoro configs.
  .kokoro/continuous/kms-it.cfg
  .kokoro/nightly/kms-it.cfg
  .kokoro/presubmit/kms-it.cfg
  google-cloud-clients/google-cloud-kms/src/test/java/com/google/cloud/kms/it/ITKmsTest.java
Labels: cla: yes

#4519 Update KMS README.md to include link to code examples.
  google-cloud-clients/google-cloud-kms/README.md
Labels: cla: yes

#4520 Regenerate dlp client
  google-api-grpc/grpc-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpServiceGrpc.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/Action.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ActionOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ActivateJobTriggerRequest.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ActivateJobTriggerRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/BigQueryOptions.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CloudStorageOptions.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CryptoHashConfig.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CustomInfoType.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpProto.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpStorage.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/FileType.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InfoTypeDescription.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InfoTypeDescriptionOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InspectConfig.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListJobTriggersRequest.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListJobTriggersRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/RecordCondition.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/RecordKey.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/RecordKeyOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/RelationalOperator.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/TransformationSummary.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/TransformationSummaryOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/dlp.proto
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/storage.proto
  google-cloud-clients/google-cloud-dlp/synth.metadata
Labels: cla: yes

#4510 BigQuery: Fix timestamp parsing regression
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
Labels: api: bigquery, cla: yes

#4506 Bigtable: add a helper method to easily connect to an emulator
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/env/Emulator.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/env/EmulatorEnv.java
  google-cloud-testing/google-cloud-bigtable-emulator/README.md
Labels: api: bigtable, cla: yes

#4515 Pubsub ordering keys subscriber
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDispatcherTest.java
Labels: api: pubsub, cla: yes

#4508 Bigtable: expose credential provider as a toplevel setting
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettings.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettingsTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettingsTest.java
Labels: api: bigtable, cla: yes

#4509 Bigtable: Deemphasize most of the settings and move them to the StubSettings
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/ResourceHeaderTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/BulkMutateRowsRetryTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsRetryTest.java
Labels: api: bigtable, cla: yes

#4490 Removing deprecated ServiceAccount creation in StorageImplTest.
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
Labels: :rotating_light:, cla: yes

#4521 Add mvn formatting call instructions to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes

#4516 Datastore: Fix `more_results` value to query results
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResults.java
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResultsImpl.java
  google-cloud-clients/google-cloud-datastore/src/test/java/com/google/cloud/datastore/DatastoreTest.java
Labels: api: datastore, cla: yes

#4526 [cloud spanner] Add dependency for surefire-junit47
  google-cloud-clients/google-cloud-spanner/pom.xml
Labels: cla: yes

#4528 Regenerate spanner client
  google-api-grpc/grpc-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerGrpc.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponse.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerProto.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/spanner.proto
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/GrpcSpannerStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/MockSpannerImpl.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#4527 Regenerate compute client
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/AttachDiskInstanceHttpRequest.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Condition.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/ForwardingRule.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InstanceClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InterconnectDiagnosticsLinkOpticalPower.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InterconnectDiagnosticsLinkStatus.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Network.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/NetworkPeering.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/NetworksAddPeeringRequest.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/ForwardingRuleClientTest.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/GlobalForwardingRuleClientTest.java
  google-cloud-clients/google-cloud-compute/synth.metadata
Labels: cla: yes

#4529 Regenerate video-intelligence client
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/Feature.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/NormalizedBoundingPoly.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/NormalizedBoundingPolyOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/NormalizedVertex.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/NormalizedVertexOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/ObjectTrackingAnnotation.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/ObjectTrackingAnnotationOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/ObjectTrackingFrame.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/ObjectTrackingFrameOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/TextAnnotation.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/TextAnnotationOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/TextDetectionConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/TextDetectionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/TextFrame.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/TextFrameOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/TextSegment.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/TextSegmentOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoAnnotationResults.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoAnnotationResultsOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoContext.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoContextOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/proto/google/cloud/videointelligence/v1/video_intelligence.proto
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#4483 BigQuery: Fixes Support for StandardSQLTypeName in Field.newBuilder(name, type).
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Field.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LegacySQLTypeName.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldTest.java
Labels: :rotating_light:, cla: yes

#4534 Upgrade gax dependency to 1.40.0.
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldValueListTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldValueTest.java
  google-cloud-clients/google-cloud-core/pom.xml
  google-cloud-clients/google-cloud-storage/pom.xml
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
  google-cloud-clients/pom.xml
Labels: cla: yes

#4538 BigQuery: support for GEOGRAPHY type.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldValue.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LegacySQLTypeName.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardSQLTypeName.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldValueTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#4539 Revert "Regenerate spanner client"
  google-api-grpc/grpc-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerGrpc.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponse.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerProto.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/spanner.proto
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/GrpcSpannerStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/MockSpannerImpl.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#4540 Regenerate redis client
  google-api-grpc/grpc-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/CloudRedisGrpc.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/CloudRedisServiceV1Proto.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ExportInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ExportInstanceRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/FailoverInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/FailoverInstanceRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GcsDestination.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GcsDestinationOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GcsSource.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GcsSourceOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ImportInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ImportInstanceRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/InputConfig.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/InputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/Instance.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/InstanceOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ListInstancesResponse.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ListInstancesResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/OutputConfig.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/OutputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/proto/google/cloud/redis/v1/cloud_redis.proto
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisClient.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/CloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/CloudRedisStubSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/GrpcCloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1/CloudRedisClientTest.java
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1/MockCloudRedisImpl.java
  google-cloud-clients/google-cloud-redis/synth.metadata
Labels: cla: yes

#4417 Add ITComputeTest test for resource name
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/it/ITComputeTest.java
Labels: :rotating_light:, cla: yes

#4533 Remove bigtableadmin artifact
  .kokoro/continuous/bigtableadmin-it.cfg
  .kokoro/nightly/bigtableadmin-it.cfg
  .kokoro/presubmit/bigtableadmin-it.cfg
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-bigtable-admin/README.md
  google-cloud-clients/google-cloud-bigtable-admin/pom.xml
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/internal/DeprecationMarker.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/internal/ArtifactDeprecationChecker.java
  google-cloud-clients/pom.xml
  google-cloud-testing/google-cloud-bigtable-emulator/README.md
  versions.txt
Labels: api: bigtable, cla: yes

#4544 bigquerystorage: address doc nits
  google-cloud-clients/google-cloud-bigquerystorage/README.md
  google-cloud-clients/google-cloud-bigquerystorage/pom.xml
Labels: cla: yes

#4389 BigQuery: Fixes When Table,Dataset and Job is not found
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryOptions.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
Labels: :rotating_light:, cla: yes

#4550 Regenerate tasks client
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/HttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/HttpRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Queue.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/QueueOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TargetProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Task.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TaskOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TaskProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/cloudtasks.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/queue.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/target.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/task.proto
  google-cloud-clients/google-cloud-tasks/synth.metadata
Labels: cla: yes

#4493 Bigtable: integrate OpenCensus tracing into the bigtable data client
  google-cloud-clients/google-cloud-bigtable/README.md
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsRetryingCallable.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/tracing/WrappedTracerFactory.java
Labels: :rotating_light:, api: bigtable, cla: yes

#4577 Regenerate trace client
  google-api-grpc/proto-google-cloud-trace-v1/src/main/proto/google/devtools/cloudtrace/v1/trace.proto
  google-api-grpc/proto-google-cloud-trace-v2/src/main/proto/google/devtools/cloudtrace/v2/trace.proto
  google-api-grpc/proto-google-cloud-trace-v2/src/main/proto/google/devtools/cloudtrace/v2/tracing.proto
  google-cloud-clients/google-cloud-trace/synth.metadata
Labels: cla: yes

#4576 Regenerate texttospeech client
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/proto/google/cloud/texttospeech/v1/cloud_tts.proto
  google-api-grpc/proto-google-cloud-texttospeech-v1beta1/src/main/proto/google/cloud/texttospeech/v1beta1/cloud_tts.proto
  google-cloud-clients/google-cloud-texttospeech/synth.metadata
Labels: cla: yes

#4575 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionAudio.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionAudioOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognizeResponse.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognizeResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/proto/google/cloud/speech/v1/cloud_speech.proto
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionAudio.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionAudioOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognizeResponse.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognizeResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#4573 Regenerate redis client
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/CreateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/DeleteInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/UpdateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/proto/google/cloud/redis/v1/cloud_redis.proto
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/CreateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/DeleteInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ListInstancesRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ListInstancesResponse.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/UpdateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/proto/google/cloud/redis/v1beta1/cloud_redis.proto
  google-cloud-clients/google-cloud-redis/synth.metadata
Labels: cla: yes

#4572 Regenerate monitoring client
  google-api-grpc/grpc-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/MetricServiceGrpc.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/AlertPolicy.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/Group.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/GroupOrBuilder.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/ListNotificationChannelsRequest.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/ListNotificationChannelsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/NotificationChannel.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/NotificationChannelOrBuilder.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/ServiceTier.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/alert.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/alert_service.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/common.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/dropped_labels.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/group.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/group_service.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/metric.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/metric_service.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/mutation_record.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/notification.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/notification_service.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/span_context.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/uptime.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/uptime_service.proto
  google-cloud-clients/google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4571 Regenerate logging client
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CreateSinkRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CreateSinkRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/UpdateExclusionRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/UpdateExclusionRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/proto/google/logging/v2/log_entry.proto
  google-api-grpc/proto-google-cloud-logging-v2/src/main/proto/google/logging/v2/logging.proto
  google-api-grpc/proto-google-cloud-logging-v2/src/main/proto/google/logging/v2/logging_config.proto
  google-api-grpc/proto-google-cloud-logging-v2/src/main/proto/google/logging/v2/logging_metrics.proto
  google-cloud-clients/google-cloud-logging/synth.metadata
Labels: cla: yes

#4568 Regenerate errorreporting client
  google-api-grpc/grpc-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ReportErrorsServiceGrpc.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ReportErrorEventRequest.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ReportErrorEventRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/proto/google/devtools/clouderrorreporting/v1beta1/common.proto
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/proto/google/devtools/clouderrorreporting/v1beta1/error_group_service.proto
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/proto/google/devtools/clouderrorreporting/v1beta1/error_stats_service.proto
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/proto/google/devtools/clouderrorreporting/v1beta1/report_errors_service.proto
  google-cloud-clients/google-cloud-errorreporting/synth.metadata
Labels: cla: yes

#4569 Regenerate iot client
  google-api-grpc/proto-google-cloud-iot-v1/src/main/proto/google/cloud/iot/v1/device_manager.proto
  google-api-grpc/proto-google-cloud-iot-v1/src/main/proto/google/cloud/iot/v1/resources.proto
  google-cloud-clients/google-cloud-iot/synth.metadata
Labels: cla: yes

#4562 Regenerate asset client
  google-api-grpc/grpc-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/AssetServiceGrpc.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/Asset.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/AssetOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/BatchGetAssetsHistoryRequest.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/BatchGetAssetsHistoryRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ExportAssetsResponse.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/Resource.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ResourceOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/proto/google/cloud/asset/v1beta1/asset_service.proto
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/proto/google/cloud/asset/v1beta1/assets.proto
  google-cloud-clients/google-cloud-asset/synth.metadata
Labels: cla: yes

#4563 Regenerate automl client
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/AnnotationPayload.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/AnnotationPayloadOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ClassificationProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/CreateDatasetRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/CreateModelRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DeleteDatasetRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DeleteModelRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DeployModelRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ExportDataRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/GetDatasetRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/GetModelEvaluationRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/GetModelRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ImportDataRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListDatasetsRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListDatasetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListDatasetsResponse.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListDatasetsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListModelEvaluationsRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListModelEvaluationsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListModelEvaluationsResponse.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListModelsRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListModelsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListModelsResponse.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictResponse.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/UndeployModelRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/annotation_payload.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/classification.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/data_items.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/dataset.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/image.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/io.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/model.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/model_evaluation.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/operations.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/prediction_service.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/service.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/text.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/translation.proto
  google-cloud-clients/google-cloud-automl/synth.metadata
Labels: cla: yes

#4565 Regenerate containeranalysis client
  google-api-grpc/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/provenance/Provenance.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1beta1/src/main/proto/google/devtools/containeranalysis/v1beta1/build/build.proto
  google-api-grpc/proto-google-cloud-containeranalysis-v1beta1/src/main/proto/google/devtools/containeranalysis/v1beta1/containeranalysis.proto
  google-api-grpc/proto-google-cloud-containeranalysis-v1beta1/src/main/proto/google/devtools/containeranalysis/v1beta1/deployment/deployment.proto
  google-api-grpc/proto-google-cloud-containeranalysis-v1beta1/src/main/proto/google/devtools/containeranalysis/v1beta1/discovery/discovery.proto
  google-api-grpc/proto-google-cloud-containeranalysis-v1beta1/src/main/proto/google/devtools/containeranalysis/v1beta1/grafeas/grafeas.proto
  google-api-grpc/proto-google-cloud-containeranalysis-v1beta1/src/main/proto/google/devtools/containeranalysis/v1beta1/provenance/provenance.proto
  google-api-grpc/proto-google-cloud-containeranalysis-v1beta1/src/main/proto/google/devtools/containeranalysis/v1beta1/vulnerability/vulnerability.proto
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
Labels: cla: yes

#4564 Regenerate bigtable client
  google-api-grpc/proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/bigtable_instance_admin.proto
  google-api-grpc/proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/bigtable_table_admin.proto
  google-api-grpc/proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/common.proto
  google-api-grpc/proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/instance.proto
  google-api-grpc/proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/table.proto
  google-api-grpc/proto-google-cloud-bigtable-v2/src/main/proto/google/bigtable/v2/bigtable.proto
  google-api-grpc/proto-google-cloud-bigtable-v2/src/main/proto/google/bigtable/v2/data.proto
  google-cloud-clients/google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4566 Regenerate datastore client
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/AllocateIdsRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/AllocateIdsResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/BeginTransactionRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/BeginTransactionResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/CommitRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/EntityResult.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/EntityResultOrBuilder.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/GqlQuery.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/PartitionId.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Query.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/QueryOrBuilder.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ReserveIdsRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ReserveIdsResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/RollbackResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/RunQueryResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/TransactionOptions.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Value.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ValueOrBuilder.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/proto/google/datastore/v1/datastore.proto
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/proto/google/datastore/v1/entity.proto
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/proto/google/datastore/v1/query.proto
  google-cloud-clients/google-cloud-datastore/synth.metadata
Labels: cla: yes

#4587 Regenerate compute client
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InstanceClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Interconnect.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/ManagedInstance.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/ManagedInstanceVersion.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/RawDisk.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/ResetInstanceHttpRequest.java
  google-cloud-clients/google-cloud-compute/synth.metadata
Labels: cla: yes

#4586 Regenerate bigquerystorage client
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/ReadOptions.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/Storage.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/avro.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/read_options.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/storage.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/table_reference.proto
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClient.java
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
Labels: cla: yes

#4588 Regenerate pubsub client
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PushConfig.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PushConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4589 Remove package private dead code from the subscriber client library.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnectionTest.java
Labels: cla: yes

#4590 Change MessageDispatcher to own its own queue.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDispatcherTest.java
Labels: cla: yes

#4591 Update Issue Templates to match other google-cloud repositories
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
Labels: cla: yes

#4592 Scale the system executor provider with the number of pull channels
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: cla: yes

#4594 Using the google-cloud-http-bom
  google-cloud-clients/pom.xml
Labels: cla: yes
