Repository googleapis/google-cloud-java, pull requests merged in 2019-12, with the labels that each got.

#6961 Update versions
  TROUBLESHOOTING.md
Labels: cla: yes

#6964 BOM 3.0.0
  README.md
  google-cloud-clients/google-cloud-bigquery/README.md
  google-cloud-clients/google-cloud-bigquerystorage/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/README.md
  google-cloud-clients/google-cloud-datastore/README.md
  google-cloud-clients/google-cloud-spanner/README.md
  google-cloud-clients/google-cloud-storage/README.md
Labels: cla: yes

#6939 spanner-jdbc: Metadata queries should be allowed during a DDL batch
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionImpl.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/DdlBatch.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/DdlBatchTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataWithMockedServerTest.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
Labels: api: spanner, cla: yes

#6579 [Storage] Update default base host for google-cloud-storage
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
Labels: api: storage, cla: yes

#6818 Regenerate spanner client
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/GetInstanceRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/GetInstanceRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/Instance.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/InstanceOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/SpannerInstanceAdminProto.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/proto/google/spanner/admin/instance/v1/spanner_instance_admin.proto
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClientTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClientTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/SpannerClientTest.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#6987 Unblock UBLA/BPO test
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#6956 spanner-jdbc: Filter unwanted files from META-INF directory
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/pom.xml
Labels: cla: yes

#7002 Fix link to BigQuery Data Transfer repository
  google-cloud-clients/google-cloud-bigquerydatatransfer/README.md
Labels: cla: yes

#7007 Updating libraries-bom and linkage-checker version
  TROUBLESHOOTING.md
Labels: cla: yes

#7010 chore: remove extracted pom files
  google-api-grpc/grpc-google-cloud-dialogflow-v2/pom.xml
  google-api-grpc/grpc-google-cloud-dialogflow-v2beta1/pom.xml
  google-api-grpc/grpc-google-cloud-dlp-v2/pom.xml
  google-api-grpc/grpc-google-cloud-kms-v1/pom.xml
  google-api-grpc/grpc-google-cloud-language-v1/pom.xml
  google-api-grpc/grpc-google-cloud-language-v1beta2/pom.xml
  google-api-grpc/grpc-google-cloud-logging-v2/pom.xml
  google-api-grpc/grpc-google-cloud-monitoring-v3/pom.xml
  google-api-grpc/grpc-google-cloud-talent-v4beta1/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1beta2/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1p1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1p2beta1/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1p3beta1/pom.xml
  google-api-grpc/grpc-google-cloud-vision-v1/pom.xml
  google-api-grpc/grpc-google-cloud-vision-v1p1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-vision-v1p2beta1/pom.xml
  google-api-grpc/grpc-google-cloud-vision-v1p3beta1/pom.xml
  google-api-grpc/grpc-google-cloud-vision-v1p4beta1/pom.xml
  google-api-grpc/proto-google-cloud-dialogflow-v2/pom.xml
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/pom.xml
  google-api-grpc/proto-google-cloud-dlp-v2/pom.xml
  google-api-grpc/proto-google-cloud-kms-v1/pom.xml
  google-api-grpc/proto-google-cloud-language-v1/pom.xml
  google-api-grpc/proto-google-cloud-language-v1beta2/pom.xml
  google-api-grpc/proto-google-cloud-logging-v2/pom.xml
  google-api-grpc/proto-google-cloud-monitoring-v3/pom.xml
  google-api-grpc/proto-google-cloud-talent-v4beta1/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta1/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta2/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1p1beta1/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1p2beta1/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/pom.xml
  google-api-grpc/proto-google-cloud-vision-v1/pom.xml
  google-api-grpc/proto-google-cloud-vision-v1p1beta1/pom.xml
  google-api-grpc/proto-google-cloud-vision-v1p2beta1/pom.xml
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/pom.xml
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/pom.xml
  google-cloud-clients/google-cloud-compute/pom.xml
  google-cloud-clients/google-cloud-dialogflow/pom.xml
  google-cloud-clients/google-cloud-dlp/pom.xml
  google-cloud-clients/google-cloud-dns/pom.xml
  google-cloud-clients/google-cloud-kms/pom.xml
  google-cloud-clients/google-cloud-language/pom.xml
  google-cloud-clients/google-cloud-logging/pom.xml
  google-cloud-clients/google-cloud-monitoring/pom.xml
  google-cloud-clients/google-cloud-resourcemanager/pom.xml
  google-cloud-clients/google-cloud-talent/pom.xml
  google-cloud-clients/google-cloud-video-intelligence/pom.xml
  google-cloud-clients/google-cloud-vision/pom.xml
Labels: cla: yes

#7005 Remove bigquerydatatransfer version entry from versions.txt
  versions.txt
Labels: cla: yes

#6951 spanner: add benchwrapper.
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-testing/spanner-benchwrapper/README.md
  google-cloud-testing/spanner-benchwrapper/pom.xml
  google-cloud-testing/spanner-benchwrapper/src/main/java/com/google/cloud/benchwrapper/Main.java
  google-cloud-testing/spanner-benchwrapper/src/main/java/com/google/cloud/benchwrapper/SpannerBenchWrapperImpl.java
  google-cloud-testing/spanner-benchwrapper/src/main/proto/spanner.proto
Labels: cla: yes

#6530 Add list buckets sample
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: api: storage, cla: yes

#7026 Update make object public sample
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/MakeObjectPublic.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITBlobSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: cla: yes

#6860 Change SigV4 canonical request formatting.
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/CanonicalExtensionHeadersSerializer.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/SignatureInfo.java
Labels: cla: yes

#7012 Add fn to correctly encode parts of signed URLs
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/SignedUrlEncodingHelper.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
Labels: cla: yes

#7034 (storage) Fix default host
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
Labels: cla: yes

#7030 Restructure V4 signature samples
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/GenerateV4GetObjectSignedUrl.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/GenerateV4PutObjectSignedUrl.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITBlobSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: cla: yes

#6740 CloudStorage: Write the storage contents to the output stream instead of a byte array
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
Labels: api: storage, cla: yes

#7038 Add test to verify file is actually downloaded with FakeStorageRpc
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/testing/LocalStorageHelperTest.java
Labels: cla: yes

#7043 Libraries-bom 3.2.0
  TROUBLESHOOTING.md
Labels: cla: yes

#7031 fix: container analysis link in README.md
  README.md
Labels: cla: yes

#7029 Make sure failsafe and surefire plugin versions match
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/pom.xml
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/pom.xml
  google-cloud-examples/pom.xml
  google-cloud-util/pom.xml
Labels: cla: yes

#7045 Allow adding query params to GCS signed URLs
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/SignatureInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#7058 deps: update dependency com.google.cloud:google-cloud-conformance-tests to v0.0.3
  google-cloud-clients/pom.xml
Labels: cla: yes

#7070 Extract logback adapter to split repository
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingEventEnhancer.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/example/enhancers/AnotherTestLoggingEnhancer.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/example/enhancers/TestLoggingEnhancer.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/StackTraceTest.java
  google-cloud-clients/google-cloud-contrib/pom.xml
Labels: cla: yes

#7069 Extract notification client to split repository
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/src/main/java/com/google/cloud/notification/Notification.java
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/src/main/java/com/google/cloud/notification/NotificationImpl.java
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/src/main/java/com/google/cloud/notification/NotificationInfo.java
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/src/test/java/com/google/cloud/notification/NotificationInfoTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/src/test/java/com/google/cloud/notification/it/ITSystemTest.java
  google-cloud-clients/google-cloud-contrib/pom.xml
Labels: cla: yes

#7055 docs: libraries-bom 3.3.0
  TROUBLESHOOTING.md
Labels: cla: yes
