Repository googleapis/google-cloud-java, pull requests merged in 2019-03, with the labels that each got.

#4597 Using the latest version of truth
  google-api-grpc/pom.xml
  google-cloud-clients/google-cloud-core/pom.xml
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResultSetsTest.java
  google-cloud-clients/pom.xml
Labels: cla: yes

#4614 Regenerate websecurityscanner client
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/crawled_url.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/finding.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/finding_addon.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/finding_type_stats.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/scan_config.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/scan_run.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/web_security_scanner.proto
  google-cloud-clients/google-cloud-websecurityscanner/synth.metadata
Labels: cla: yes

#4613 Regenerate vision client
  google-api-grpc/grpc-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchGrpc.java
  google-api-grpc/grpc-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/ProductSearchGrpc.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/BatchOperationMetadata.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/BatchOperationMetadataOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ImportProductSetsGcsSource.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ImportProductSetsGcsSourceOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ImportProductSetsResponse.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchParams.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchParamsOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/TextAnnotation.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/geometry.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/image_annotator.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search_service.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/text_annotation.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/web_detection.proto
  google-api-grpc/proto-google-cloud-vision-v1p1beta1/src/main/java/com/google/cloud/vision/v1p1beta1/EntityAnnotation.java
  google-api-grpc/proto-google-cloud-vision-v1p1beta1/src/main/java/com/google/cloud/vision/v1p1beta1/EntityAnnotationOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p1beta1/src/main/proto/google/cloud/vision/v1p1beta1/image_annotator.proto
  google-api-grpc/proto-google-cloud-vision-v1p2beta1/src/main/java/com/google/cloud/vision/v1p2beta1/TextAnnotation.java
  google-api-grpc/proto-google-cloud-vision-v1p2beta1/src/main/proto/google/cloud/vision/v1p2beta1/geometry.proto
  google-api-grpc/proto-google-cloud-vision-v1p2beta1/src/main/proto/google/cloud/vision/v1p2beta1/image_annotator.proto
  google-api-grpc/proto-google-cloud-vision-v1p2beta1/src/main/proto/google/cloud/vision/v1p2beta1/text_annotation.proto
  google-api-grpc/proto-google-cloud-vision-v1p2beta1/src/main/proto/google/cloud/vision/v1p2beta1/web_detection.proto
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/BatchOperationMetadata.java
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/BatchOperationMetadataOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/ImportProductSetsGcsSource.java
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/ImportProductSetsGcsSourceOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/ImportProductSetsResponse.java
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/ProductSearchParams.java
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/ProductSearchParamsOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/java/com/google/cloud/vision/v1p3beta1/TextAnnotation.java
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/proto/google/cloud/vision/v1p3beta1/geometry.proto
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/proto/google/cloud/vision/v1p3beta1/image_annotator.proto
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/proto/google/cloud/vision/v1p3beta1/product_search.proto
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/proto/google/cloud/vision/v1p3beta1/product_search_service.proto
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/proto/google/cloud/vision/v1p3beta1/text_annotation.proto
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/src/main/proto/google/cloud/vision/v1p3beta1/web_detection.proto
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#4612 Regenerate video-intelligence client
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/AnnotateVideoRequest.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/AnnotateVideoRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/proto/google/cloud/videointelligence/v1/video_intelligence.proto
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta1/src/main/java/com/google/cloud/videointelligence/v1beta1/AnnotateVideoRequest.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta1/src/main/java/com/google/cloud/videointelligence/v1beta1/AnnotateVideoRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta1/src/main/proto/google/cloud/videointelligence/v1beta1/video_intelligence.proto
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta2/src/main/java/com/google/cloud/videointelligence/v1beta2/AnnotateVideoRequest.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta2/src/main/java/com/google/cloud/videointelligence/v1beta2/AnnotateVideoRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta2/src/main/proto/google/cloud/videointelligence/v1beta2/video_intelligence.proto
  google-api-grpc/proto-google-cloud-video-intelligence-v1p1beta1/src/main/java/com/google/cloud/videointelligence/v1p1beta1/AnnotateVideoRequest.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p1beta1/src/main/java/com/google/cloud/videointelligence/v1p1beta1/AnnotateVideoRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p1beta1/src/main/proto/google/cloud/videointelligence/v1p1beta1/video_intelligence.proto
  google-api-grpc/proto-google-cloud-video-intelligence-v1p2beta1/src/main/java/com/google/cloud/videointelligence/v1p2beta1/AnnotateVideoRequest.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p2beta1/src/main/java/com/google/cloud/videointelligence/v1p2beta1/AnnotateVideoRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p2beta1/src/main/proto/google/cloud/videointelligence/v1p2beta1/video_intelligence.proto
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#4610 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/proto/google/cloud/securitycenter/v1beta1/organization_settings.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/proto/google/cloud/securitycenter/v1beta1/security_marks.proto
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4615 BigQuery: Fix useAvroLogicalTypes option in LoadJobConfiguration And WriteChannelConfiguration.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/WriteChannelConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/WriteChannelConfigurationTest.java
Labels: cla: yes

#4598 Spanner: Add methods in SpannerExceptionFactory for propagating ApiException and TimeoutException
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
Labels: cla: yes

#4609 Regenerate scheduler client
  google-api-grpc/grpc-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerGrpc.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineHttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineHttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineRouting.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineRoutingOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CreateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CreateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/GetJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/Job.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/JobOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsResponse.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PauseJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ResumeJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RetryConfig.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RetryConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/UpdateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/UpdateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/cloudscheduler.proto
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/job.proto
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/target.proto
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4608 Regenerate pubsub client
  google-api-grpc/grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriberGrpc.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/CreateSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriptionOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4607 Regenerate os-login client
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/proto/google/cloud/oslogin/common/common.proto
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/proto/google/cloud/oslogin/v1/oslogin.proto
  google-cloud-clients/google-cloud-os-login/synth.metadata
Labels: cla: yes

#4603 Regenerate dlp client
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/dlp.proto
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/storage.proto
  google-cloud-clients/google-cloud-dlp/synth.metadata
Labels: cla: yes

#4605 Regenerate iamcredentials client
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/proto/google/iam/credentials/v1/common.proto
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/proto/google/iam/credentials/v1/iamcredentials.proto
  google-cloud-clients/google-cloud-iamcredentials/synth.metadata
Labels: cla: yes

#4601 Regenerate bigquerystorage client
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/avro.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/read_options.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/storage.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/table_reference.proto
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
Labels: cla: yes

#4600 Regenerate bigquerydatatransfer client
  google-api-grpc/grpc-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceGrpc.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/proto/google/cloud/bigquery/datatransfer/v1/datatransfer.proto
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/proto/google/cloud/bigquery/datatransfer/v1/transfer.proto
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
Labels: cla: yes

#4606 Regenerate language client
  google-api-grpc/grpc-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/LanguageServiceGrpc.java
  google-api-grpc/grpc-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/LanguageServiceGrpc.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitiesResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitiesResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitySentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitySentimentResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSentimentResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSyntaxResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSyntaxResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnnotateTextResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnnotateTextResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Entity.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/EntityMention.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/EntityMentionOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/EntityOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Sentence.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/SentenceOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/TextSpan.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/TextSpanOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/proto/google/cloud/language/v1/language_service.proto
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitiesResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitiesResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitySentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitySentimentResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSentimentResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSyntaxResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSyntaxResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnnotateTextResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnnotateTextResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Entity.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/EntityMention.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/EntityMentionOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/EntityOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Sentence.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/SentenceOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/TextSpan.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/TextSpanOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/proto/google/cloud/language/v1beta2/language_service.proto
  google-cloud-clients/google-cloud-language/synth.metadata
Labels: cla: yes

#4616 Set the isDirectory flag appropriately on the test storage rpc
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
Labels: cla: yes

#4618 Extract the single message processing functionality from processOutstandingBatches
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
Labels: api: cloudkms, cla: yes

#4578 Publish pending batches before sending requested message
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
Labels: cla: yes

#4593 Upgrading grpc in google-api-grpc
  google-api-grpc/pom.xml
Labels: cla: yes

#4581 Prepare for KMS GA release - upgrade versions to 1.0.0.
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-kms/pom.xml
  versions.txt
Labels: cla: yes

#4619 Clean up MessageDispatcher v2
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
Labels: api: pubsub, cla: yes

#4620 Remove global synchronization from MessageDispatcher.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
Labels: cla: yes

#4625 Regenerate vision client
  google-api-grpc/grpc-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchGrpc.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/BatchOperationMetadata.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/BatchOperationMetadataOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ImportProductSetsGcsSource.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ImportProductSetsGcsSourceOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ImportProductSetsResponse.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchParams.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchParamsOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/TextAnnotation.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/geometry.proto
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/image_annotator.proto
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/product_search.proto
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/product_search_service.proto
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/text_annotation.proto
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/web_detection.proto
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#4634 Regenerate dataproc client
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/ClusterControllerClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/JobControllerClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/WorkflowTemplateServiceClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/ClusterControllerClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/JobControllerClient.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/WorkflowTemplateServiceClient.java
  google-cloud-clients/google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4635 Regenerate dialogflow client
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/AgentsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/ContextsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/EntityTypesClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/IntentsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/SessionEntityTypesClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/ContextsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/EntityTypesClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/IntentsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBasesClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionEntityTypesClient.java
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4638 Regenerate firestore client
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreClient.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/FirestoreClient.java
  google-cloud-clients/google-cloud-firestore/synth.metadata
Labels: cla: yes

#4639 Regenerate iot client
  google-cloud-clients/google-cloud-iot/src/main/java/com/google/cloud/iot/v1/DeviceManagerClient.java
  google-cloud-clients/google-cloud-iot/synth.metadata
Labels: cla: yes

#4642 Regenerate monitoring client
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/AlertPolicyServiceClient.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/GroupServiceClient.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/MetricServiceClient.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/NotificationChannelServiceClient.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/UptimeCheckServiceClient.java
  google-cloud-clients/google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4631 Regenerate bigtable client
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BaseBigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BaseBigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4637 Regenerate errorreporting client
  google-cloud-clients/google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/ErrorStatsServiceClient.java
  google-cloud-clients/google-cloud-errorreporting/synth.metadata
Labels: cla: yes

#4643 Regenerate pubsub client
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4629 Regenerate automl client
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/AutoMlClient.java
  google-cloud-clients/google-cloud-automl/synth.metadata
Labels: cla: yes

#4644 Regenerate redis client
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisClient.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisClient.java
  google-cloud-clients/google-cloud-redis/synth.metadata
Labels: cla: yes

#4630 Regenerate bigquerydatatransfer client
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClient.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
Labels: cla: yes

#4645 Regenerate scheduler client
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClient.java
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4640 Regenerate kms client
  google-cloud-clients/google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceClient.java
  google-cloud-clients/google-cloud-kms/synth.metadata
Labels: cla: yes

#4650 Regenerate vision client
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ProductSearchClient.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/ProductSearchClient.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchClient.java
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#4651 Regenerate websecurityscanner client
  google-cloud-clients/google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerClient.java
  google-cloud-clients/google-cloud-websecurityscanner/synth.metadata
Labels: cla: yes

#4633 Regenerate containeranalysis client
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1beta1/ContainerAnalysisV1Beta1Client.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1beta1/GrafeasV1Beta1Client.java
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
Labels: cla: yes

#4636 Regenerate dlp client
  google-cloud-clients/google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/DlpServiceClient.java
  google-cloud-clients/google-cloud-dlp/synth.metadata
Labels: cla: yes

#4649 Regenerate trace client
  google-cloud-clients/google-cloud-trace/src/main/java/com/google/cloud/trace/v1/TraceServiceClient.java
  google-cloud-clients/google-cloud-trace/synth.metadata
Labels: cla: yes

#4647 Regenerate spanner client
  google-api-grpc/grpc-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerGrpc.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponse.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerProto.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/spanner.proto
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/GrpcSpannerStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/MockSpannerImpl.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#4641 Regenerate logging client
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/v2/ConfigClient.java
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/v2/LoggingClient.java
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/v2/MetricsClient.java
  google-cloud-clients/google-cloud-logging/synth.metadata
Labels: cla: yes

#4648 Regenerate tasks client
  google-cloud-clients/google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta2/CloudTasksClient.java
  google-cloud-clients/google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta3/CloudTasksClient.java
  google-cloud-clients/google-cloud-tasks/synth.metadata
Labels: cla: yes

#4646 Regenerate securitycenter client
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClient.java
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4653 Batch dml mainline
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerBatchUpdateException.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContext.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchDmlTest.java
Labels: cla: yes

#4387 BigQuery: add long term storage bytes to standard table definition.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Table.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableInfo.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableInfoTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes, needs work

#4662 Regenerate compute client
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/BackendService.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Binding.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/DeprecationStatus.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/HealthCheck.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Http2HealthCheck.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/RouterStatusNatStatus.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/TargetVpnGateway.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/TargetVpnGatewaysScopedList.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/VpnTunnel.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/VpnTunnelAggregatedList.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/VpnTunnelsScopedList.java
  google-cloud-clients/google-cloud-compute/synth.metadata
Labels: cla: yes

#4018 Adding FieldValue.increment()
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldValue.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: :rotating_light:, cla: yes, do not merge

#4663 Spanner: Throw exception when SSLHandshakeException occurs instead of infinite retry loop
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
Labels: cla: yes

#4658 Add Cloud Scheduler v1 API.
  google-api-grpc/grpc-google-cloud-scheduler-v1/pom.xml
  google-api-grpc/grpc-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/CloudSchedulerGrpc.java
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-scheduler-v1/pom.xml
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/AppEngineHttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/AppEngineHttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/AppEngineRouting.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/AppEngineRoutingOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/CreateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/CreateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/DeleteJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/DeleteJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/GetJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/GetJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/HttpMethod.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/HttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/HttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/Job.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/JobName.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/JobOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/JobProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ListJobsRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ListJobsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ListJobsResponse.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ListJobsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/LocationName.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PauseJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PauseJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ProjectName.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PubsubTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PubsubTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ResumeJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ResumeJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/RetryConfig.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/RetryConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/RunJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/RunJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/SchedulerProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/TargetProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/UpdateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/UpdateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/proto/google/cloud/scheduler/v1/cloudscheduler.proto
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/proto/google/cloud/scheduler/v1/job.proto
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/proto/google/cloud/scheduler/v1/target.proto
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-scheduler/pom.xml
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/CloudSchedulerClient.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/CloudSchedulerSettings.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/package-info.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/CloudSchedulerStub.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/CloudSchedulerStubSettings.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/GrpcCloudSchedulerCallableFactory.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/GrpcCloudSchedulerStub.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1/CloudSchedulerClientTest.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1/MockCloudScheduler.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1/MockCloudSchedulerImpl.java
  google-cloud-clients/google-cloud-scheduler/synth.metadata
  google-cloud-clients/google-cloud-scheduler/synth.py
  versions.txt
Labels: cla: yes

#4656 Fix Timestamp.parseTimestamp.
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/Timestamp.java
  google-cloud-clients/google-cloud-core/src/test/java/com/google/cloud/TimestampTest.java
Labels: cla: yes

#4667 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/AssetOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/FindingOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/OrganizationSettingsOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecurityMarksOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecuritycenterService.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SourceOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/asset.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/finding.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/organization_settings.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/security_marks.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/securitycenter_service.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/source.proto
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4622 Change each StreamingSubscriberConnection to have its own executor by default.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: :rotating_light:, cla: yes

#4671 Bigtable: Remove reference to deprecated typesafe name in README
  google-cloud-clients/google-cloud-bigtable/README.md
Labels: api: bigtable, cla: yes, type: docs

#4676 Regenerate language client
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/ClassificationCategory.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/ClassificationCategoryOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/EncodingType.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Entity.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/LanguageServiceProto.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/proto/google/cloud/language/v1/language_service.proto
  google-cloud-clients/google-cloud-language/src/main/java/com/google/cloud/language/v1/LanguageServiceClient.java
  google-cloud-clients/google-cloud-language/src/main/java/com/google/cloud/language/v1/LanguageServiceSettings.java
  google-cloud-clients/google-cloud-language/src/main/java/com/google/cloud/language/v1/package-info.java
  google-cloud-clients/google-cloud-language/src/main/java/com/google/cloud/language/v1/stub/GrpcLanguageServiceCallableFactory.java
  google-cloud-clients/google-cloud-language/src/main/java/com/google/cloud/language/v1/stub/GrpcLanguageServiceStub.java
  google-cloud-clients/google-cloud-language/src/main/java/com/google/cloud/language/v1/stub/LanguageServiceStub.java
  google-cloud-clients/google-cloud-language/src/main/java/com/google/cloud/language/v1/stub/LanguageServiceStubSettings.java
  google-cloud-clients/google-cloud-language/synth.metadata
Labels: cla: yes

#4677 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupFindingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupFindingsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListAssetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListFindingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListFindingsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecuritycenterService.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/securitycenter_service.proto
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4686 Regenerate firestore client
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/Write.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/WriteOrBuilder.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/write.proto
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/Write.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/WriteOrBuilder.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/proto/google/firestore/v1beta1/write.proto
  google-cloud-clients/google-cloud-firestore/synth.metadata
Labels: cla: yes

#4687 Spanner now extends AutoCloseable
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Spanner.java
Labels: cla: yes

#4693 Update speech readme to point to v1 javadoc.
  google-cloud-clients/google-cloud-speech/README.md
Labels: cla: yes

#4696 google-cloud-logging: Fix pendingWrite race condition
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingImplTest.java
Labels: cla: yes

#4697 google-cloud-logging: Optimize pendingWrites
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java
Labels: cla: yes

#4694 Better explain how to use explicit credentials
  google-cloud-clients/google-cloud-contrib/google-cloud-nio-examples/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/nio/snippets/UseExplicitCredentials.java
Labels: cla: yes

#4477 Add MDC support in Logback appender
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
Labels: :rotating_light:, cla: yes

#4675 Firestore: Update CustomClassMapper
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/CustomClassMapper.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
Labels: cla: yes

#4704 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/AssetOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/FindingOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/OrganizationSettingsOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecurityMarksOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecuritycenterService.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SourceOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/asset.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/finding.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/organization_settings.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/security_marks.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/securitycenter_service.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/source.proto
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4705 Regenerate talent client
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#4701 BigQuery: Added missing partitioned fields to listTables.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#4240 OpenCensus Support for Cloud Pub/Sub
  google-cloud-clients/google-cloud-pubsub/pom.xml
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/OpenCensusUtil.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/OpenCensusUtilTest.java
Labels: :rotating_light:, api: pubsub, cla: yes

#4717 Fix comment in grpc-google-cloud-firestore-v1 POM
  google-api-grpc/grpc-google-cloud-firestore-v1/pom.xml
Labels: cla: yes

#4722 Upgrade common protos dependency to 1.15.0.
  google-api-grpc/pom.xml
  google-cloud-bom/pom.xml
Labels: cla: yes

#4723 Manually regenerate Redis
  google-api-grpc/grpc-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/CloudRedisGrpc.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/CloudRedisServiceV1Proto.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/CreateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/DeleteInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ExportInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ExportInstanceRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GcsDestination.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GcsDestinationOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GcsSource.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GcsSourceOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ImportInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ImportInstanceRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/InputConfig.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/InputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/Instance.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/InstanceOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/OutputConfig.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/OutputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/UpdateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/proto/google/cloud/redis/v1/cloud_redis.proto
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisClient.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/package-info.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/CloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/CloudRedisStubSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/GrpcCloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1/CloudRedisClientTest.java
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1/MockCloudRedisImpl.java
Labels: cla: yes

#4724 1.x is stable
  google-cloud-clients/google-cloud-kms/README.md
Labels: cla: yes

#4730 Regenerate bigquerystorage client
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/Storage.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/TableReferenceProto.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/avro.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/read_options.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/storage.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/table_reference.proto
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
Labels: cla: yes

#4732 Regenerate pubsub client
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessage.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessageOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriptionOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriptionAdminClientTest.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4709 Added feature to accept Firestore Value.
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/CustomClassMapper.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/WriteBatchTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#4733 pubsub - Fix flaky OpenCensusUtilTest.testOpenCensusMessageReceiver()
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/OpenCensusUtilTest.java
Labels: cla: yes

#4731 Regenerate compute client
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Instance.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/ShieldedInstanceConfig.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/ShieldedInstanceIdentity.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/ShieldedInstanceIdentityEntry.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/ShieldedInstanceIntegrityPolicy.java
  google-cloud-clients/google-cloud-compute/synth.metadata
Labels: cla: yes

#4707 Replacing GoogleCloudPlatform with googleapis in docs.
  google-cloud-clients/google-cloud-asset/README.md
  google-cloud-clients/google-cloud-asset/pom.xml
  google-cloud-clients/google-cloud-automl/README.md
  google-cloud-clients/google-cloud-automl/pom.xml
  google-cloud-clients/google-cloud-containeranalysis/README.md
  google-cloud-clients/google-cloud-containeranalysis/pom.xml
  google-cloud-clients/google-cloud-iamcredentials/README.md
  google-cloud-clients/google-cloud-kms/README.md
  google-cloud-clients/google-cloud-kms/pom.xml
  google-cloud-clients/google-cloud-securitycenter/README.md
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/package-info.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/testing/package-info.java
  google-cloud-clients/google-cloud-tasks/README.md
  google-cloud-clients/google-cloud-tasks/pom.xml
  google-cloud-clients/google-cloud-translate/src/main/java/com/google/cloud/translate/package-info.java
  google-cloud-clients/google-cloud-translate/src/main/java/com/google/cloud/translate/testing/package-info.java
  google-cloud-clients/src/site/resources/index.html
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/BigQueryExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/deprecated/ComputeExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/datastore/DatastoreExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/dns/DnsExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/logging/LoggingExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/nio/CountBytes.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/nio/ParallelCountBytes.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/nio/Stat.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/resourcemanager/ResourceManagerExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/StorageExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/translate/TranslateExample.java
  utilities/templates/README.md.tmpl
Labels: cla: yes

#4738 Regenerate Redis client
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisClient.java
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1/CloudRedisClientTest.java
Labels: cla: yes

#4728 Spanner: Fix default value of maxSessions in document of setMaxSessions
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
Labels: api: spanner, cla: yes

#4721 Spanner: Added extra documentation to the DatabaseClient.singleUse methods
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
Labels: api: spanner, cla: yes

#4741 Regenerate Firestore clients
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreAdminClient.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreClient.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/FirestoreClient.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/FirestoreAdminClientTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/FirestoreClientTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1beta1/FirestoreClientTest.java
Labels: cla: yes

#4746 Regenerate iamcredentials client
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/IamCredentialsClient.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/package-info.java
  google-cloud-clients/google-cloud-iamcredentials/src/test/java/com/google/cloud/iam/credentials/v1/IamCredentialsClientTest.java
  google-cloud-clients/google-cloud-iamcredentials/synth.metadata
Labels: cla: yes

#4747 Regenerate monitoring client
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/DroppedLabels.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/DroppedLabelsOrBuilder.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/DroppedLabelsProto.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/dropped_labels.proto
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/UptimeCheckServiceClient.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/package-info.java
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/UptimeCheckServiceClientTest.java
  google-cloud-clients/google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4690 Add Snippets for working with Assets in Cloud Security Command Center.
  google-cloud-examples/pom.xml
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/AssetSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/securitycenter/snippets/ITAssetSnippets.java
Labels: :rotating_light:, cla: yes

#4753 storage: add V4 GET and PUT samples
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: cla: yes

#4740 Pass through header provider in BQ storage client settings.
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/EnhancedBigQueryStorageStub.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/ResourceHeaderTest.java
Labels: cla: yes

#4754 storage: fix v4 samples
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: cla: yes

#4758 Regenerate asset client
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/stub/GrpcAssetServiceStub.java
  google-cloud-clients/google-cloud-asset/synth.metadata
Labels: cla: yes

#4759 Regenerate automl client
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcAutoMlStub.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcPredictionServiceStub.java
  google-cloud-clients/google-cloud-automl/synth.metadata
Labels: cla: yes

#4765 Regenerate dlp client
  google-cloud-clients/google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/stub/GrpcDlpServiceStub.java
  google-cloud-clients/google-cloud-dlp/synth.metadata
Labels: cla: yes

#4760 Regenerate bigtable client
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/MockBigtableInstanceAdminImpl.java
  google-cloud-clients/google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4769 Regenerate logging client
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcConfigServiceV2Stub.java
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcLoggingServiceV2Stub.java
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/GrpcMetricsServiceV2Stub.java
  google-cloud-clients/google-cloud-logging/synth.metadata
Labels: cla: yes

#4770 Regenerate monitoring client
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcAlertPolicyServiceStub.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcGroupServiceStub.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcMetricServiceStub.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcNotificationChannelServiceStub.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcUptimeCheckServiceStub.java
  google-cloud-clients/google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4772 Regenerate pubsub client
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcPublisherStub.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcSubscriberStub.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4761 Regenerate container client
  google-cloud-clients/google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/GrpcClusterManagerStub.java
  google-cloud-clients/google-cloud-container/synth.metadata
Labels: cla: yes

#4771 Regenerate os-login client
  google-cloud-clients/google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/GrpcOsLoginServiceStub.java
  google-cloud-clients/google-cloud-os-login/synth.metadata
Labels: cla: yes

#4766 Regenerate errorreporting client
  google-cloud-clients/google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorGroupServiceStub.java
  google-cloud-clients/google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcErrorStatsServiceStub.java
  google-cloud-clients/google-cloud-errorreporting/src/main/java/com/google/cloud/errorreporting/v1beta1/stub/GrpcReportErrorsServiceStub.java
  google-cloud-clients/google-cloud-errorreporting/synth.metadata
Labels: cla: yes

#4762 Regenerate containeranalysis client
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1beta1/stub/GrpcContainerAnalysisV1Beta1Stub.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1beta1/stub/GrpcGrafeasV1Beta1Stub.java
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
Labels: cla: yes

#4777 Regenerate talent client
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcApplicationServiceStub.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcCompanyServiceStub.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcCompletionStub.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcEventServiceStub.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcJobServiceStub.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcProfileServiceStub.java
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcTenantServiceStub.java
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#4775 Regenerate securitycenter client
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/stub/GrpcSecurityCenterStub.java
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/stub/GrpcSecurityCenterStub.java
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4773 Regenerate redis client
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/GrpcCloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/GrpcCloudRedisStub.java
  google-cloud-clients/google-cloud-redis/synth.metadata
Labels: cla: yes

#4774 Regenerate scheduler client
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/GrpcCloudSchedulerStub.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/GrpcCloudSchedulerStub.java
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4768 Regenerate iamcredentials client
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/IamCredentialsClient.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/stub/GrpcIamCredentialsStub.java
  google-cloud-clients/google-cloud-iamcredentials/src/test/java/com/google/cloud/iam/credentials/v1/IamCredentialsClientTest.java
  google-cloud-clients/google-cloud-iamcredentials/synth.metadata
Labels: cla: yes

#4764 Regenerate dialogflow client
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/GrpcAgentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/GrpcContextsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/GrpcEntityTypesStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/GrpcIntentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/GrpcSessionEntityTypesStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/GrpcSessionsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcAgentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcContextsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcDocumentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcEntityTypesStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcIntentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcKnowledgeBasesStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcSessionEntityTypesStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcSessionsStub.java
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4767 Regenerate firestore client
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreAdminStub.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreStub.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/stub/GrpcFirestoreStub.java
  google-cloud-clients/google-cloud-firestore/synth.metadata
Labels: cla: yes

#4776 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/GrpcDatabaseAdminStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/stub/GrpcInstanceAdminStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/GrpcSpannerStub.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#4778 Regenerate trace client
  google-cloud-clients/google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/GrpcTraceServiceStub.java
  google-cloud-clients/google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/GrpcTraceServiceStub.java
  google-cloud-clients/google-cloud-trace/synth.metadata
Labels: cla: yes

#4763 Regenerate dataproc client
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/stub/GrpcWorkflowTemplateServiceStub.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/stub/GrpcWorkflowTemplateServiceStub.java
  google-cloud-clients/google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4779 Regenerate vision client
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/GrpcProductSearchStub.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/GrpcProductSearchStub.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/GrpcProductSearchStub.java
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#4780 Regenerate websecurityscanner client
  google-cloud-clients/google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerClient.java
  google-cloud-clients/google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/package-info.java
  google-cloud-clients/google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/stub/GrpcWebSecurityScannerStub.java
  google-cloud-clients/google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerClientTest.java
  google-cloud-clients/google-cloud-websecurityscanner/synth.metadata
Labels: cla: yes

#4743 Upgrade google.auth.version to 0.15.0.
  google-cloud-clients/google-cloud-storage/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#4782 Spanner: Allow specifying a custom credentials file for integration tests
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/GceTestEnvConfig.java
Labels: cla: yes

#4794 Regenerate datastore client
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/AllocateIdsRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/AllocateIdsResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ArrayValue.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/BeginTransactionRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/BeginTransactionResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/CommitRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/CommitResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/CompositeFilter.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Entity.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/EntityResult.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Filter.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/GqlQuery.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/GqlQueryParameter.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Key.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/KindExpression.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/LookupRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/LookupResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Mutation.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/MutationResult.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/PartitionId.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Projection.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/PropertyFilter.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/PropertyOrder.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/PropertyReference.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Query.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/QueryResultBatch.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ReadOptions.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ReserveIdsRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ReserveIdsResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/RollbackRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/RollbackResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/RunQueryRequest.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/RunQueryResponse.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/TransactionOptions.java
  google-api-grpc/proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Value.java
  google-cloud-clients/google-cloud-datastore/synth.metadata
Labels: cla: yes

#4786 Regenerate asset client
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/Asset.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/BatchGetAssetsHistoryRequest.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/BatchGetAssetsHistoryResponse.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ExportAssetsRequest.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ExportAssetsResponse.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/GcsDestination.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/OutputConfig.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/Resource.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/TemporalAsset.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/TimeWindow.java
  google-cloud-clients/google-cloud-asset/synth.metadata
Labels: cla: yes

#4799 Regenerate iamcredentials client
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateAccessTokenRequest.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateAccessTokenResponse.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdTokenRequest.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdTokenResponse.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdentityBindingAccessTokenRequest.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdentityBindingAccessTokenResponse.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignBlobRequest.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignBlobResponse.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignJwtRequest.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignJwtResponse.java
  google-cloud-clients/google-cloud-iamcredentials/synth.metadata
Labels: cla: yes

#4788 Regenerate bigquerydatatransfer client
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CheckValidCredsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CheckValidCredsResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CreateTransferConfigRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSource.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceParameter.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DeleteTransferConfigRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DeleteTransferRunRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetDataSourceRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetTransferConfigRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetTransferRunRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListDataSourcesRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListDataSourcesResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferConfigsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferConfigsResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferLogsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferLogsResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferRunsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferRunsResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ScheduleTransferRunsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ScheduleTransferRunsResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferConfig.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferMessage.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferRun.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/UpdateTransferConfigRequest.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
Labels: cla: yes

#4802 Regenerate language client
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitiesRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitiesResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitySentimentRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitySentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSentimentRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSyntaxRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSyntaxResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnnotateTextRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnnotateTextResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/ClassificationCategory.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/ClassifyTextRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/ClassifyTextResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/DependencyEdge.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Document.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Entity.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/EntityMention.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/PartOfSpeech.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Sentence.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Sentiment.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/TextSpan.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Token.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitiesRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitiesResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitySentimentRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitySentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSentimentRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSyntaxRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSyntaxResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnnotateTextRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnnotateTextResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/ClassificationCategory.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/ClassifyTextRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/ClassifyTextResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/DependencyEdge.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Document.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Entity.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/EntityMention.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/PartOfSpeech.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Sentence.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Sentiment.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/TextSpan.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Token.java
  google-cloud-clients/google-cloud-language/synth.metadata
Labels: cla: yes

#4801 Regenerate kms client
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricDecryptRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricDecryptResponse.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricSignRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricSignResponse.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CreateCryptoKeyRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CreateCryptoKeyVersionRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CreateKeyRingRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKey.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersion.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersionTemplate.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/DecryptRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/DecryptResponse.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/DestroyCryptoKeyVersionRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/Digest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/EncryptRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/EncryptResponse.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/GetCryptoKeyRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/GetCryptoKeyVersionRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/GetKeyRingRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/GetPublicKeyRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KeyOperationAttestation.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KeyRing.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListCryptoKeyVersionsRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListCryptoKeyVersionsResponse.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListCryptoKeysRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListCryptoKeysResponse.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListKeyRingsRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListKeyRingsResponse.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/LocationMetadata.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/PublicKey.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/RestoreCryptoKeyVersionRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/UpdateCryptoKeyPrimaryVersionRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/UpdateCryptoKeyRequest.java
  google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/UpdateCryptoKeyVersionRequest.java
  google-cloud-clients/google-cloud-kms/synth.metadata
Labels: cla: yes

#4789 Regenerate bigquerystorage client
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/AvroProto.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/ReadOptions.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/Storage.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/TableReferenceProto.java
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
Labels: cla: yes

#4811 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/LongRunningRecognizeMetadata.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/LongRunningRecognizeRequest.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/LongRunningRecognizeResponse.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionAudio.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognizeRequest.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognizeResponse.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechContext.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechRecognitionAlternative.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechRecognitionResult.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognitionResult.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognizeRequest.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognizeResponse.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/WordInfo.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeMetadata.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeRequest.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeResponse.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionAudio.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionMetadata.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognizeRequest.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognizeResponse.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechContext.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechRecognitionAlternative.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechRecognitionResult.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognitionResult.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognizeRequest.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognizeResponse.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/WordInfo.java
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#4809 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/Asset.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/CreateFindingRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/CreateSourceRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/Finding.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GetOrganizationSettingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GetSourceRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupFindingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupFindingsResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupResult.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListAssetsResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListFindingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListFindingsResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListSourcesRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListSourcesResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/OrganizationSettings.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/RunAssetDiscoveryRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecurityMarks.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SetFindingStateRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/Source.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/UpdateFindingRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/UpdateOrganizationSettingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/UpdateSecurityMarksRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/UpdateSourceRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/Asset.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/CreateFindingRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/CreateSourceRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/Finding.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/GetOrganizationSettingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/GetSourceRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/GroupAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/GroupAssetsResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/GroupFindingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/GroupFindingsResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/GroupResult.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/ListAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/ListAssetsResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/ListFindingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/ListFindingsResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/ListSourcesRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/ListSourcesResponse.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/OrganizationSettings.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/RunAssetDiscoveryRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/SecurityMarks.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/SetFindingStateRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/Source.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/UpdateFindingRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/UpdateOrganizationSettingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/UpdateSecurityMarksRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/UpdateSourceRequest.java
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4810 Regenerate spanner client
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CreateDatabaseMetadata.java
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CreateDatabaseRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/Database.java
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/DropDatabaseRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/GetDatabaseDdlRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/GetDatabaseDdlResponse.java
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/GetDatabaseRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListDatabasesRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListDatabasesResponse.java
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/UpdateDatabaseDdlMetadata.java
  google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/UpdateDatabaseDdlRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/CreateInstanceMetadata.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/CreateInstanceRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/DeleteInstanceRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/GetInstanceConfigRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/GetInstanceRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/Instance.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/InstanceConfig.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/ListInstanceConfigsRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/ListInstanceConfigsResponse.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/ListInstancesRequest.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/ListInstancesResponse.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/UpdateInstanceMetadata.java
  google-api-grpc/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/UpdateInstanceRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/BeginTransactionRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/CommitRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/CommitResponse.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/CreateSessionRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/DeleteSessionRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponse.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteSqlRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/GetSessionRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/KeyRange.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/KeySet.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ListSessionsRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ListSessionsResponse.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/Mutation.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/PartialResultSet.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/Partition.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/PartitionOptions.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/PartitionQueryRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/PartitionReadRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/PartitionResponse.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/PlanNode.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/QueryPlan.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ReadRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ResultSet.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ResultSetMetadata.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ResultSetStats.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/RollbackRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/Session.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/StructType.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/Transaction.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/TransactionOptions.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/TransactionSelector.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/Type.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#4807 Regenerate redis client
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/CreateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/DeleteInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/FailoverInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GetInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/Instance.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ListInstancesRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ListInstancesResponse.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/LocationMetadata.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/OperationMetadata.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/UpdateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ZoneMetadata.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/CreateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/DeleteInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/GetInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/Instance.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ListInstancesRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ListInstancesResponse.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/LocationMetadata.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/UpdateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ZoneMetadata.java
  google-cloud-clients/google-cloud-redis/synth.metadata
Labels: cla: yes

#4791 Regenerate container client
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/AcceleratorConfig.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/AddonsConfig.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/AutoUpgradeOptions.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/CancelOperationRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ClientCertificateConfig.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/Cluster.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ClusterUpdate.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/CompleteIPRotationRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/CreateClusterRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/CreateNodePoolRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/DailyMaintenanceWindow.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/DeleteClusterRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/DeleteNodePoolRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/GetClusterRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/GetNodePoolRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/GetOperationRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/GetServerConfigRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/HorizontalPodAutoscaling.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/HttpLoadBalancing.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/IPAllocationPolicy.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/KubernetesDashboard.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/LegacyAbac.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ListClustersRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ListClustersResponse.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ListNodePoolsRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ListNodePoolsResponse.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ListOperationsRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ListOperationsResponse.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/MaintenancePolicy.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/MaintenanceWindow.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/MasterAuth.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/MasterAuthorizedNetworksConfig.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/NetworkConfig.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/NetworkPolicy.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/NetworkPolicyConfig.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/NodeConfig.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/NodeManagement.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/NodePool.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/NodePoolAutoscaling.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/Operation.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/PrivateClusterConfig.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/RollbackNodePoolUpgradeRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ServerConfig.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetAddonsConfigRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetLabelsRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetLegacyAbacRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetLocationsRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetLoggingServiceRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetMaintenancePolicyRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetMasterAuthRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetMonitoringServiceRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetNetworkPolicyRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetNodePoolAutoscalingRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetNodePoolManagementRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/SetNodePoolSizeRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/StartIPRotationRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/UpdateClusterRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/UpdateMasterRequest.java
  google-api-grpc/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/UpdateNodePoolRequest.java
  google-cloud-clients/google-cloud-container/synth.metadata
Labels: cla: yes

#4808 Regenerate scheduler client
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/AppEngineHttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/AppEngineRouting.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/CreateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/DeleteJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/GetJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/HttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/Job.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ListJobsRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ListJobsResponse.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PauseJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PubsubTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ResumeJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/RetryConfig.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/RunJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/UpdateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineHttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineRouting.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CreateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/DeleteJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/GetJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/Job.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsResponse.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PauseJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PubsubTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ResumeJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RetryConfig.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RunJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/UpdateJobRequest.java
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4805 Regenerate os-login client
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/common/OsLoginProto.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/DeletePosixAccountRequest.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/DeleteSshPublicKeyRequest.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/GetLoginProfileRequest.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/GetSshPublicKeyRequest.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/ImportSshPublicKeyRequest.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/ImportSshPublicKeyResponse.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/LoginProfile.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/UpdateSshPublicKeyRequest.java
  google-cloud-clients/google-cloud-os-login/synth.metadata
Labels: cla: yes

#4797 Regenerate errorreporting client
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/DeleteEventsRequest.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/DeleteEventsResponse.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ErrorContext.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ErrorEvent.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ErrorGroup.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ErrorGroupStats.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/GetGroupRequest.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/HttpRequestContext.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ListEventsRequest.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ListEventsResponse.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ListGroupStatsRequest.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ListGroupStatsResponse.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/QueryTimeRange.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ReportErrorEventRequest.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ReportErrorEventResponse.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ReportedErrorEvent.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ServiceContext.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ServiceContextFilter.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/SourceLocation.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/TimedCount.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/TrackingIssue.java
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/UpdateGroupRequest.java
  google-cloud-clients/google-cloud-errorreporting/synth.metadata
Labels: cla: yes

#4818 Regenerate websecurityscanner client
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/CrawledUrl.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/CreateScanConfigRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/DeleteScanConfigRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/Finding.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/FindingTypeStats.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetFindingRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetScanConfigRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetScanRunRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListCrawledUrlsRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListCrawledUrlsResponse.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingTypeStatsRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingTypeStatsResponse.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingsRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingsResponse.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanConfigsRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanConfigsResponse.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanRunsRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanRunsResponse.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/OutdatedLibrary.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanConfig.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanRun.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/StartScanRunRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/StopScanRunRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/UpdateScanConfigRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ViolatingResource.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/VulnerableParameters.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/Xss.java
  google-cloud-clients/google-cloud-websecurityscanner/synth.metadata
Labels: cla: yes

#4803 Regenerate logging client
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CreateExclusionRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CreateLogMetricRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/CreateSinkRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/DeleteExclusionRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/DeleteLogMetricRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/DeleteLogRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/DeleteSinkRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/GetExclusionRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/GetLogMetricRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/GetSinkRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListExclusionsRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListExclusionsResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogEntriesRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogEntriesResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogMetricsRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogMetricsResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogsRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListLogsResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListMonitoredResourceDescriptorsRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListMonitoredResourceDescriptorsResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListSinksRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/ListSinksResponse.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogEntry.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogEntryOperation.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogEntrySourceLocation.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogExclusion.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogMetric.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/LogSink.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/UpdateExclusionRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/UpdateLogMetricRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/UpdateSinkRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/WriteLogEntriesPartialErrors.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/WriteLogEntriesRequest.java
  google-api-grpc/proto-google-cloud-logging-v2/src/main/java/com/google/logging/v2/WriteLogEntriesResponse.java
  google-cloud-clients/google-cloud-logging/synth.metadata
Labels: cla: yes

#4814 Regenerate texttospeech client
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/AudioConfig.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/ListVoicesRequest.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/ListVoicesResponse.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/SynthesisInput.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/SynthesizeSpeechRequest.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/SynthesizeSpeechResponse.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/Voice.java
  google-api-grpc/proto-google-cloud-texttospeech-v1/src/main/java/com/google/cloud/texttospeech/v1/VoiceSelectionParams.java
  google-api-grpc/proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/AudioConfig.java
  google-api-grpc/proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/ListVoicesRequest.java
  google-api-grpc/proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/ListVoicesResponse.java
  google-api-grpc/proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/SynthesisInput.java
  google-api-grpc/proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/SynthesizeSpeechRequest.java
  google-api-grpc/proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/SynthesizeSpeechResponse.java
  google-api-grpc/proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/Voice.java
  google-api-grpc/proto-google-cloud-texttospeech-v1beta1/src/main/java/com/google/cloud/texttospeech/v1beta1/VoiceSelectionParams.java
  google-cloud-clients/google-cloud-texttospeech/synth.metadata
Labels: cla: yes

#4813 Regenerate tasks client
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/AcknowledgeTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/AppEngineHttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/AppEngineHttpTarget.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/AppEngineRouting.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/AttemptStatus.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/CancelLeaseRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/CreateQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/CreateTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/DeleteQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/DeleteTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/GetQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/GetTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/LeaseTasksRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/LeaseTasksResponse.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/ListQueuesRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/ListQueuesResponse.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/ListTasksRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/ListTasksResponse.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/PauseQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/PullMessage.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/PullTarget.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/PurgeQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/Queue.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/RateLimits.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/RenewLeaseRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/ResumeQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/RetryConfig.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/RunTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/Task.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/TaskStatus.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/UpdateQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpQueue.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineRouting.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Attempt.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CreateQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CreateTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/DeleteQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/DeleteTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/GetQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/GetTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/HttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListQueuesRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListQueuesResponse.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListTasksRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListTasksResponse.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/PauseQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/PurgeQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Queue.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RateLimits.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ResumeQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RetryConfig.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RunTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Task.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/UpdateQueueRequest.java
  google-cloud-clients/google-cloud-tasks/synth.metadata
Labels: cla: yes

#4815 Regenerate trace client
  google-api-grpc/proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/GetTraceRequest.java
  google-api-grpc/proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/ListTracesRequest.java
  google-api-grpc/proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/ListTracesResponse.java
  google-api-grpc/proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/PatchTracesRequest.java
  google-api-grpc/proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/Trace.java
  google-api-grpc/proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/TraceSpan.java
  google-api-grpc/proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/Traces.java
  google-api-grpc/proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/AttributeValue.java
  google-api-grpc/proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/BatchWriteSpansRequest.java
  google-api-grpc/proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/Module.java
  google-api-grpc/proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/Span.java
  google-api-grpc/proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/StackTrace.java
  google-api-grpc/proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/TruncatableString.java
  google-cloud-clients/google-cloud-trace/synth.metadata
Labels: cla: yes

#4819 Upgrade protobuf version to 3.7.0.
  google-api-grpc/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#4822 Regenerate automl client
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/AnnotationPayload.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ClassificationProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/CreateDatasetRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/CreateModelOperationMetadata.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/CreateModelRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Dataset.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DeleteDatasetRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DeleteModelRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DeployModelRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ExamplePayload.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ExportDataRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/GcsDestination.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/GcsSource.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/GetDatasetRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/GetModelEvaluationRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/GetModelRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Image.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ImageClassificationDatasetMetadata.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ImageClassificationModelMetadata.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ImportDataRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/InputConfig.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListDatasetsRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListDatasetsResponse.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListModelEvaluationsRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListModelEvaluationsResponse.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListModelsRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ListModelsResponse.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Model.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ModelEvaluation.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/OperationMetadata.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/OutputConfig.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictResponse.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextClassificationDatasetMetadata.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextClassificationModelMetadata.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextSnippet.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TranslationAnnotation.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TranslationDatasetMetadata.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TranslationEvaluationMetrics.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TranslationModelMetadata.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/UndeployModelRequest.java
  google-cloud-clients/google-cloud-automl/synth.metadata
Labels: cla: yes

#4826 Regenerate iot client
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/BindDeviceToGatewayRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/BindDeviceToGatewayResponse.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/CreateDeviceRegistryRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/CreateDeviceRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeleteDeviceRegistryRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeleteDeviceRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/Device.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeviceConfig.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeviceCredential.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeviceRegistry.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeviceState.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/EventNotificationConfig.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GatewayConfig.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GatewayListOptions.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GetDeviceRegistryRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GetDeviceRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/HttpConfig.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceConfigVersionsRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceConfigVersionsResponse.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceRegistriesRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceRegistriesResponse.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceStatesRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceStatesResponse.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDevicesRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDevicesResponse.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ModifyCloudToDeviceConfigRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/MqttConfig.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/PublicKeyCertificate.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/PublicKeyCredential.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/RegistryCredential.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/SendCommandToDeviceRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/SendCommandToDeviceResponse.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/StateNotificationConfig.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/UnbindDeviceFromGatewayRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/UnbindDeviceFromGatewayResponse.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/UpdateDeviceRegistryRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/UpdateDeviceRequest.java
  google-api-grpc/proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/X509CertificateDetails.java
  google-cloud-clients/google-cloud-iot/synth.metadata
Labels: cla: yes

#4827 Regenerate pubsub client
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/AcknowledgeRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/CreateSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteSubscriptionRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteTopicRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ExpirationPolicy.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetSubscriptionRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetTopicRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSnapshotsRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSnapshotsResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSubscriptionsRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSubscriptionsResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSnapshotsRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSnapshotsResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSubscriptionsRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSubscriptionsResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicsRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicsResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/MessageStoragePolicy.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ModifyAckDeadlineRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ModifyPushConfigRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublishRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublishResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessage.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PullRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PullResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PushConfig.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ReceivedMessage.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SeekRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SeekResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Snapshot.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/StreamingPullRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/StreamingPullResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Topic.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UpdateSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UpdateSubscriptionRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UpdateTopicRequest.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes
