Repository googleapis/google-cloud-java, pull requests merged in 2019-04, with the labels that each got.

#4834 Add Cloud Asset v1 API.
  google-api-grpc/grpc-google-cloud-asset-v1/pom.xml
  google-api-grpc/grpc-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetServiceGrpc.java
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-asset-v1/pom.xml
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/Asset.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetProto.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetServiceProto.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BatchGetAssetsHistoryRequest.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BatchGetAssetsHistoryRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BatchGetAssetsHistoryResponse.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BatchGetAssetsHistoryResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ContentType.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportAssetsRequest.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportAssetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportAssetsResponse.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportAssetsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/GcsDestination.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/GcsDestinationOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/OutputConfig.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/OutputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ProjectName.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/Resource.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ResourceOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/TemporalAsset.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/TemporalAssetOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/TimeWindow.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/TimeWindowOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/asset_service.proto
  google-api-grpc/proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/assets.proto
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-asset/pom.xml
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceClient.java
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceSettings.java
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1/package-info.java
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStub.java
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/GrpcAssetServiceStub.java
  google-cloud-clients/google-cloud-asset/src/test/java/com/google/cloud/asset/v1/AssetServiceClientTest.java
  google-cloud-clients/google-cloud-asset/src/test/java/com/google/cloud/asset/v1/MockAssetService.java
  google-cloud-clients/google-cloud-asset/src/test/java/com/google/cloud/asset/v1/MockAssetServiceImpl.java
  google-cloud-clients/google-cloud-asset/synth.metadata
  google-cloud-clients/google-cloud-asset/synth.py
  versions.txt
Labels: cla: yes

#4849 Regenerate iamcredentials client
  google-cloud-clients/google-cloud-iamcredentials/src/test/java/com/google/cloud/iam/credentials/v1/MockIAMCredentialsImpl.java
  google-cloud-clients/google-cloud-iamcredentials/synth.metadata
Labels: cla: yes

#4850 Regenerate iot client
  google-cloud-clients/google-cloud-iot/src/test/java/com/google/cloud/iot/v1/MockDeviceManagerImpl.java
  google-cloud-clients/google-cloud-iot/synth.metadata
Labels: cla: yes

#4851 Regenerate kms client
  google-cloud-clients/google-cloud-kms/src/test/java/com/google/cloud/kms/v1/MockIAMPolicyImpl.java
  google-cloud-clients/google-cloud-kms/src/test/java/com/google/cloud/kms/v1/MockKeyManagementServiceImpl.java
  google-cloud-clients/google-cloud-kms/synth.metadata
Labels: cla: yes

#4864 Regenerate texttospeech client
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1/MockTextToSpeechImpl.java
  google-cloud-clients/google-cloud-texttospeech/src/test/java/com/google/cloud/texttospeech/v1beta1/MockTextToSpeechImpl.java
  google-cloud-clients/google-cloud-texttospeech/synth.metadata
Labels: cla: yes

#4863 Regenerate tasks client
  google-cloud-clients/google-cloud-tasks/src/test/java/com/google/cloud/tasks/v2beta2/MockCloudTasksImpl.java
  google-cloud-clients/google-cloud-tasks/src/test/java/com/google/cloud/tasks/v2beta3/MockCloudTasksImpl.java
  google-cloud-clients/google-cloud-tasks/synth.metadata
Labels: cla: yes

#4862 Regenerate talent client
  google-cloud-clients/google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/MockApplicationServiceImpl.java
  google-cloud-clients/google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/MockCompanyServiceImpl.java
  google-cloud-clients/google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/MockCompletionImpl.java
  google-cloud-clients/google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/MockEventServiceImpl.java
  google-cloud-clients/google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/MockJobServiceImpl.java
  google-cloud-clients/google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/MockProfileServiceImpl.java
  google-cloud-clients/google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/MockTenantServiceImpl.java
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#4840 Regenerate bigquerystorage client
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/MockBigQueryStorageImpl.java
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
Labels: cla: yes

#4839 Regenerate bigquerydatatransfer client
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/test/java/com/google/cloud/bigquery/datatransfer/v1/MockDataTransferServiceImpl.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
Labels: cla: yes

#4852 Regenerate language client
  google-cloud-clients/google-cloud-language/src/test/java/com/google/cloud/language/v1/MockLanguageServiceImpl.java
  google-cloud-clients/google-cloud-language/src/test/java/com/google/cloud/language/v1beta2/MockLanguageServiceImpl.java
  google-cloud-clients/google-cloud-language/synth.metadata
Labels: cla: yes

#4854 Regenerate monitoring client
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockAlertPolicyServiceImpl.java
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockGroupServiceImpl.java
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockMetricServiceImpl.java
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockNotificationChannelServiceImpl.java
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockUptimeCheckServiceImpl.java
  google-cloud-clients/google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4856 Regenerate pubsub client
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockIAMPolicyImpl.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockPublisherImpl.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockSubscriberImpl.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4857 Regenerate redis client
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1/MockCloudRedisImpl.java
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1beta1/MockCloudRedisImpl.java
  google-cloud-clients/google-cloud-redis/synth.metadata
Labels: cla: yes

#4858 Regenerate scheduler client
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1/MockCloudSchedulerImpl.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/MockCloudSchedulerImpl.java
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4859 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupFindingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupFindingsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListAssetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListFindingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListFindingsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/securitycenter_service.proto
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-clients/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/MockSecurityCenterImpl.java
  google-cloud-clients/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/MockSecurityCenterImpl.java
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4860 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/database/v1/MockDatabaseAdminImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/instance/v1/MockInstanceAdminImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/MockSpannerImpl.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#4865 Regenerate trace client
  google-cloud-clients/google-cloud-trace/src/test/java/com/google/cloud/trace/v1/MockTraceServiceImpl.java
  google-cloud-clients/google-cloud-trace/src/test/java/com/google/cloud/trace/v2/MockTraceServiceImpl.java
  google-cloud-clients/google-cloud-trace/synth.metadata
Labels: cla: yes

#4866 Regenerate video-intelligence client
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1/MockVideoIntelligenceServiceImpl.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1beta1/MockVideoIntelligenceServiceImpl.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1beta2/MockVideoIntelligenceServiceImpl.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p1beta1/MockVideoIntelligenceServiceImpl.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p2beta1/MockVideoIntelligenceServiceImpl.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p3beta1/MockStreamingVideoIntelligenceServiceImpl.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p3beta1/MockVideoIntelligenceServiceImpl.java
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#4868 Regenerate websecurityscanner client
  google-cloud-clients/google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/v1alpha/MockWebSecurityScannerImpl.java
  google-cloud-clients/google-cloud-websecurityscanner/synth.metadata
Labels: cla: yes

#4867 Regenerate vision client
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ProductSearchClient.java
  google-cloud-clients/google-cloud-vision/src/test/java/com/google/cloud/vision/v1/MockImageAnnotatorImpl.java
  google-cloud-clients/google-cloud-vision/src/test/java/com/google/cloud/vision/v1/MockProductSearchImpl.java
  google-cloud-clients/google-cloud-vision/src/test/java/com/google/cloud/vision/v1p1beta1/MockImageAnnotatorImpl.java
  google-cloud-clients/google-cloud-vision/src/test/java/com/google/cloud/vision/v1p2beta1/MockImageAnnotatorImpl.java
  google-cloud-clients/google-cloud-vision/src/test/java/com/google/cloud/vision/v1p3beta1/MockImageAnnotatorImpl.java
  google-cloud-clients/google-cloud-vision/src/test/java/com/google/cloud/vision/v1p3beta1/MockProductSearchImpl.java
  google-cloud-clients/google-cloud-vision/src/test/java/com/google/cloud/vision/v1p4beta1/MockImageAnnotatorImpl.java
  google-cloud-clients/google-cloud-vision/src/test/java/com/google/cloud/vision/v1p4beta1/MockProductSearchImpl.java
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#4861 Regenerate speech client
  google-cloud-clients/google-cloud-speech/src/test/java/com/google/cloud/speech/v1/MockSpeechImpl.java
  google-cloud-clients/google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/MockSpeechImpl.java
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#4855 Regenerate os-login client
  google-cloud-clients/google-cloud-os-login/src/test/java/com/google/cloud/oslogin/v1/MockOsLoginServiceImpl.java
  google-cloud-clients/google-cloud-os-login/synth.metadata
Labels: cla: yes

#4853 Regenerate logging client
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockConfigServiceV2Impl.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockLoggingServiceV2Impl.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/v2/MockMetricsServiceV2Impl.java
  google-cloud-clients/google-cloud-logging/synth.metadata
Labels: cla: yes

#4848 Regenerate firestore client
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/GrpcFirestoreStub.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1beta1/stub/GrpcFirestoreStub.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/MockFirestoreAdminImpl.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/MockFirestoreImpl.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1beta1/MockFirestoreImpl.java
  google-cloud-clients/google-cloud-firestore/synth.metadata
Labels: cla: yes

#4843 Regenerate containeranalysis client
  google-cloud-clients/google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1beta1/MockContainerAnalysisV1Beta1Impl.java
  google-cloud-clients/google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1beta1/MockGrafeasV1Beta1Impl.java
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
Labels: cla: yes

#4842 Regenerate container client
  google-cloud-clients/google-cloud-container/src/test/java/com/google/cloud/container/v1/MockClusterManagerImpl.java
  google-cloud-clients/google-cloud-container/synth.metadata
Labels: cla: yes

#4841 Regenerate bigtable client
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/MockBigtableInstanceAdminImpl.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/MockBigtableTableAdminImpl.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/MockBigtableImpl.java
  google-cloud-clients/google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4844 Regenerate dataproc client
  google-cloud-clients/google-cloud-dataproc/src/test/java/com/google/cloud/dataproc/v1/MockClusterControllerImpl.java
  google-cloud-clients/google-cloud-dataproc/src/test/java/com/google/cloud/dataproc/v1/MockJobControllerImpl.java
  google-cloud-clients/google-cloud-dataproc/src/test/java/com/google/cloud/dataproc/v1/MockWorkflowTemplateServiceImpl.java
  google-cloud-clients/google-cloud-dataproc/src/test/java/com/google/cloud/dataproc/v1beta2/MockClusterControllerImpl.java
  google-cloud-clients/google-cloud-dataproc/src/test/java/com/google/cloud/dataproc/v1beta2/MockJobControllerImpl.java
  google-cloud-clients/google-cloud-dataproc/src/test/java/com/google/cloud/dataproc/v1beta2/MockWorkflowTemplateServiceImpl.java
  google-cloud-clients/google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4846 Regenerate dlp client
  google-cloud-clients/google-cloud-dlp/src/test/java/com/google/cloud/dlp/v2/MockDlpServiceImpl.java
  google-cloud-clients/google-cloud-dlp/synth.metadata
Labels: cla: yes

#4847 Regenerate errorreporting client
  google-cloud-clients/google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/MockErrorGroupServiceImpl.java
  google-cloud-clients/google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/MockErrorStatsServiceImpl.java
  google-cloud-clients/google-cloud-errorreporting/src/test/java/com/google/cloud/errorreporting/v1beta1/MockReportErrorsServiceImpl.java
  google-cloud-clients/google-cloud-errorreporting/synth.metadata
Labels: cla: yes

#4729 google-cloud-logging-logback: Allow user to specify custom LoggingOptions
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
Labels: :rotating_light:, cla: yes

#4837 Regenerate asset client
  google-cloud-clients/google-cloud-asset/src/test/java/com/google/cloud/asset/v1/MockAssetServiceImpl.java
  google-cloud-clients/google-cloud-asset/src/test/java/com/google/cloud/asset/v1beta1/MockAssetServiceImpl.java
  google-cloud-clients/google-cloud-asset/synth.metadata
Labels: cla: yes

#4845 Regenerate dialogflow client
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBasesClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBasesSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/DocumentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/DocumentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcDocumentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcKnowledgeBasesStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/KnowledgeBasesStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/KnowledgeBasesStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockAgentsImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockContextsImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockEntityTypesImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockIntentsImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockSessionEntityTypesImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockSessionsImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockAgentsImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockContextsImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockDocumentsImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockEntityTypesImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockIntentsImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockKnowledgeBasesImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockSessionEntityTypesImpl.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockSessionsImpl.java
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4878 Auto close input stream for MetadataConfig
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/MetadataConfig.java
Labels: cla: yes

#4881 Add Cloud Web Risk client.
  google-api-grpc/grpc-google-cloud-webrisk-v1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/WebRiskServiceV1Beta1Grpc.java
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/pom.xml
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/CompressionType.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ComputeThreatListDiffRequest.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ComputeThreatListDiffRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ComputeThreatListDiffResponse.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ComputeThreatListDiffResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/RawHashes.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/RawHashesOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/RawIndices.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/RawIndicesOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/RiceDeltaEncoding.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/RiceDeltaEncodingOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchHashesRequest.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchHashesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchHashesResponse.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchHashesResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchUrisRequest.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchUrisRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchUrisResponse.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchUrisResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ThreatEntryAdditions.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ThreatEntryAdditionsOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ThreatEntryRemovals.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ThreatEntryRemovalsOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ThreatType.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/WebRiskProto.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/proto/google/cloud/webrisk/v1beta1/webrisk.proto
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-webrisk/README.md
  google-cloud-clients/google-cloud-webrisk/pom.xml
  google-cloud-clients/google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/WebRiskServiceV1Beta1Client.java
  google-cloud-clients/google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/WebRiskServiceV1Beta1Settings.java
  google-cloud-clients/google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/package-info.java
  google-cloud-clients/google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/GrpcWebRiskServiceV1Beta1CallableFactory.java
  google-cloud-clients/google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/GrpcWebRiskServiceV1Beta1Stub.java
  google-cloud-clients/google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/WebRiskServiceV1Beta1Stub.java
  google-cloud-clients/google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/stub/WebRiskServiceV1Beta1StubSettings.java
  google-cloud-clients/google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1beta1/MockWebRiskServiceV1Beta1.java
  google-cloud-clients/google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1beta1/MockWebRiskServiceV1Beta1Impl.java
  google-cloud-clients/google-cloud-webrisk/src/test/java/com/google/cloud/webrisk/v1beta1/WebRiskServiceV1Beta1ClientTest.java
  google-cloud-clients/google-cloud-webrisk/synth.py
  google-cloud-clients/pom.xml
  versions.txt
Labels: cla: yes

#4883 Regenerate datalabeling client
  google-cloud-clients/google-cloud-datalabeling/synth.metadata
Labels: cla: yes

#4882 Regenerate automl client
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/AnnotationSpecName.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ColumnSpecName.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ModelExportOutputConfig.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ModelExportOutputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TableSpecName.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/io.proto
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/AutoMlClient.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/AutoMlSettings.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/PredictionServiceClient.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/PredictionServiceSettings.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/AutoMlStub.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/AutoMlStubSettings.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcAutoMlStub.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcPredictionServiceStub.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/PredictionServiceStub.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/PredictionServiceStubSettings.java
  google-cloud-clients/google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/AutoMlClientTest.java
  google-cloud-clients/google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/PredictionServiceClientTest.java
  google-cloud-clients/google-cloud-automl/synth.metadata
Labels: cla: yes

#4884 Regenerate talent client
  google-cloud-clients/google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/JobServiceClientTest.java
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#4897 Spanner: Fix flaky TransactionManager tests
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerTest.java
Labels: cla: yes

#4898 Change .yaml file name for webrisk client.
  google-cloud-clients/google-cloud-webrisk/synth.py
Labels: cla: yes

#4880 Adding the translate beta samples
  google-cloud-examples/src/main/java/com/google/cloud/examples/translate/snippets/TranslateSnippetsBeta.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/translate/snippets/ITTranslateSnippetsBeta.java
Labels: cla: yes

#4902 Regenerate bigquerystorage client
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/BigQueryStorageStubSettings.java
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
Labels: cla: yes

#4903 Regenerate language client
  google-api-grpc/grpc-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/LanguageServiceGrpc.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitiesRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitiesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitiesResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitiesResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitySentimentRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitySentimentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitySentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeEntitySentimentResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSentimentRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSentimentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSentimentResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSyntaxRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSyntaxRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSyntaxResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnalyzeSyntaxResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnnotateTextRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnnotateTextRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnnotateTextResponse.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/AnnotateTextResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/ClassifyTextRequest.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/ClassifyTextRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Document.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/DocumentOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Entity.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/EntityMention.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/EntityMentionOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/EntityOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/LanguageServiceProto.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/Sentence.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/SentenceOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/TextSpan.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/TextSpanOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1/src/main/proto/google/cloud/language/v1/language_service.proto
  google-cloud-clients/google-cloud-language/synth.metadata
Labels: cla: yes

#4904 Regenerate webrisk client
  google-cloud-clients/google-cloud-webrisk/synth.metadata
Labels: cla: yes

#4692 (storage) Add V4 signing support
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/CanonicalExtensionHeadersSerializer.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/SignatureInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/CanonicalExtensionHeadersSerializerTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/SignatureInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/V4SigningTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
  google-cloud-clients/google-cloud-storage/src/test/resources/UrlSignerV4TestAccount.json
  google-cloud-clients/google-cloud-storage/src/test/resources/UrlSignerV4TestData.json
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: api: storage, cla: yes, do not merge, needs work

#4901 Add web risk to list of clients.
  google-cloud-clients/pom.xml
Labels: cla: yes

#4912 Regenerate tasks client
  google-api-grpc/grpc-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CloudTasksGrpc.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpQueue.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpQueueOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineRouting.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineRoutingOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CloudTasksProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CreateQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CreateQueueRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CreateTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CreateTaskRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/DeleteQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/GetQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/GetTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/GetTaskRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/HttpRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/HttpRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListQueuesRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListQueuesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListQueuesResponse.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListQueuesResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListTasksRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListTasksRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListTasksResponse.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ListTasksResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/OAuthToken.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/OAuthTokenOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/OidcToken.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/OidcTokenOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/PauseQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/PurgeQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Queue.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/QueueOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/QueueProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RateLimits.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RateLimitsOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/ResumeQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RetryConfig.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RetryConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RunTaskRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RunTaskRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TargetProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Task.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TaskOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TaskProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/UpdateQueueRequest.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/UpdateQueueRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/cloudtasks.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/queue.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/target.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/task.proto
  google-cloud-clients/google-cloud-tasks/src/test/java/com/google/cloud/tasks/v2beta3/CloudTasksClientTest.java
  google-cloud-clients/google-cloud-tasks/synth.metadata
Labels: cla: yes

#4911 Regenerate scheduler client
  google-api-grpc/grpc-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerGrpc.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineHttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineHttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineRouting.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineRoutingOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CreateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CreateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/GetJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/Job.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/JobOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/JobProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsResponse.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/OAuthToken.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/OAuthTokenOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/OidcToken.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/OidcTokenOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PauseJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ResumeJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RetryConfig.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RetryConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/SchedulerProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/TargetProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/UpdateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/UpdateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/cloudscheduler.proto
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/job.proto
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/target.proto
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4910 Regenerate redis client
  google-api-grpc/grpc-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisGrpc.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisServiceBetaProto.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/FailoverInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/FailoverInstanceRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/Instance.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/InstanceOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ListInstancesResponse.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ListInstancesResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/UpdateInstanceRequest.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/UpdateInstanceRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-redis-v1beta1/src/main/proto/google/cloud/redis/v1beta1/cloud_redis.proto
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisClient.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/CloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/GrpcCloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1beta1/CloudRedisClientTest.java
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1beta1/MockCloudRedisImpl.java
  google-cloud-clients/google-cloud-redis/synth.metadata
Labels: cla: yes

#4891 Spanner: Refactor SpannerImpl - Move AbstractResultSet to separate file
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResumableStreamIteratorTest.java
Labels: cla: yes

#4890 Spanner: Refactor SpannerImpl - Move AbstractReadContext to separate file
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
Labels: cla: yes

#4921 Regenerate language client
  google-cloud-clients/google-cloud-language/src/main/java/com/google/cloud/language/v1/LanguageServiceClient.java
  google-cloud-clients/google-cloud-language/src/main/java/com/google/cloud/language/v1/package-info.java
  google-cloud-clients/google-cloud-language/src/test/java/com/google/cloud/language/v1/LanguageServiceClientTest.java
  google-cloud-clients/google-cloud-language/synth.metadata
Labels: cla: yes

#4892 Spanner: Refactor SpannerImpl - Move DatabaseAdminClientImpl to separate file
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientImplTest.java
Labels: cla: yes

#4924 Bigquery : Fix close write channel
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java
Labels: api: bigquery, cla: yes

#4893 Spanner: Refactor SpannerImpl - Move InstanceAdminClient to separate file
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceAdminClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminClientImplTest.java
Labels: cla: yes

#4923 BigQuery: Added listPartitions.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#4928 Regenerate dialogflow client
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/session.proto
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4929 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecuritycenterService.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/securitycenter_service.proto
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4931 Regenerate trace client
  google-cloud-clients/google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/TraceServiceStubSettings.java
  google-cloud-clients/google-cloud-trace/synth.metadata
Labels: cla: yes

#4920 google-cloud-core: Optimize Date.parseDate(String)
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/Date.java
  google-cloud-clients/google-cloud-core/src/test/java/com/google/cloud/DateTest.java
Labels: cla: yes

#4896 Spanner: Refactor SpannerImpl - Move TransactionRunnerImpl to separate file
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManagerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
Labels: :rotating_light:, cla: yes

#4937 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/AssetName.java
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4936 storage: Un-Ignore testRotateFromCustomerEncryptionToKmsKeyWithCustom…
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes

#4935 #4933 Adding support to custom ports on LocalDatastoreHelper
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java
  google-cloud-clients/google-cloud-datastore/src/test/java/com/google/cloud/datastore/testing/LocalDatastoreHelperTest.java
Labels: cla: yes

#4874 Storage : Fix manage resumeable signedURL uploads.
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
  google-cloud-clients/google-cloud-storage/.attach_pid8524
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: :rotating_light:, cla: yes

#4718 cloud-storage-contrib-nio: Add support for newFileChannel
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageReadFileChannel.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageWriteFileChannel.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadFileChannelTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageWriteFileChannelTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Labels: :rotating_light:, cla: yes

#4916 Change MessageDispatcher to be synchronous instead of asynchronous.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDispatcherTest.java
Labels: :rotating_light:, cla: yes

#4895 Spanner: Refactor SpannerImpl - Move SessionImpl to separate file
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManagerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
Labels: :rotating_light:, cla: yes

#4947 PubSub subscriber cleanup
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: cla: yes

#4945 Minor cleanup in pubsub
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageWaiter.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageWaiterTest.java
Labels: cla: yes

#4917 CSCC Snippets
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/AssetSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/FindingSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/OrganizationSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/SecurityMarkSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/SourceSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/securitycenter/snippets/ITAssetSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/securitycenter/snippets/ITFindingSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/securitycenter/snippets/ITOrganizationSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/securitycenter/snippets/ITSecurityMarkSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/securitycenter/snippets/ITSourceSnippets.java
Labels: :rotating_light:, cla: yes

#4954 Regenerate kms client
  google-cloud-clients/google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  google-cloud-clients/google-cloud-kms/synth.metadata
Labels: cla: yes

#4949 Cleaning up deprecated pubsub code.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/it/ITPubSubTest.java
Labels: cla: yes

#4948 More Pubsub cleanup
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/PublisherStats.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StatusUtil.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriberStats.java
Labels: cla: yes

#4951 Encapsulating a notion of "message batch" in pub/sub
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#4952 Use splitindex for google-api-grpc javadoc.
  google-api-grpc/pom.xml
Labels: cla: yes

#4963 Regenerate firestore client
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreClient.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreSettings.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/stub/FirestoreStubSettings.java
  google-cloud-clients/google-cloud-firestore/synth.metadata
Labels: cla: yes

#4962 Refactoring of the Pub/Sub Ordering keys client
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
Labels: cla: yes

#4957 Initial Generation of data catalog
  google-api-grpc/grpc-google-cloud-datacatalog-v1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/DataCatalogGrpc.java
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/pom.xml
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/BigQueryTableSpec.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/BigQueryTableSpecOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/ColumnSchema.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/ColumnSchemaOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/Datacatalog.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/Entry.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/EntryName.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/EntryOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/EntryType.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/LocationName.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/LookupEntryRequest.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/LookupEntryRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/Schema.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/SchemaOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/SchemaOuterClass.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/SystemTimestamps.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/SystemTimestampsOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/TableSourceType.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/TableSpec.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/Timestamps.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/ViewSpec.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/ViewSpecOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/proto/google/cloud/datacatalog/v1beta1/datacatalog.proto
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/proto/google/cloud/datacatalog/v1beta1/schema.proto
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/proto/google/cloud/datacatalog/v1beta1/table_spec.proto
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/proto/google/cloud/datacatalog/v1beta1/timestamps.proto
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-datacatalog/README.md
  google-cloud-clients/google-cloud-datacatalog/pom.xml
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/DataCatalogClient.java
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/DataCatalogSettings.java
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/package-info.java
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/DataCatalogStub.java
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/DataCatalogStubSettings.java
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/GrpcDataCatalogCallableFactory.java
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/GrpcDataCatalogStub.java
  google-cloud-clients/google-cloud-datacatalog/src/test/java/com/google/cloud/datacatalog/v1beta1/DataCatalogClientTest.java
  google-cloud-clients/google-cloud-datacatalog/src/test/java/com/google/cloud/datacatalog/v1beta1/MockDataCatalog.java
  google-cloud-clients/google-cloud-datacatalog/src/test/java/com/google/cloud/datacatalog/v1beta1/MockDataCatalogImpl.java
  google-cloud-clients/google-cloud-datacatalog/synth.py
  google-cloud-clients/pom.xml
  versions.txt
Labels: cla: yes

#4966 Upgrade gax to 1.44.0.
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#4968 Prep version numbers for Firestore GA.
  google-api-grpc/grpc-google-cloud-firestore-admin-v1/pom.xml
  google-api-grpc/grpc-google-cloud-firestore-v1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-firestore-admin-v1/pom.xml
  google-api-grpc/proto-google-cloud-firestore-v1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-firestore/pom.xml
  versions.txt
Labels: cla: yes

#4969 [WIP] Refactoring SequentialExecutorService
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
Labels: cla: yes

#4970 Prep version numbers for Speech GA.
  google-api-grpc/grpc-google-cloud-speech-v1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-speech-v1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-speech/pom.xml
  versions.txt
Labels: cla: yes

#4975 Regenerate datacatalog client
  google-cloud-clients/google-cloud-datacatalog/synth.metadata
Labels: cla: yes

#4976 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/AssetOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/FindingOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/OrganizationSettingsOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecurityMarksOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SourceOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/asset.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/finding.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/organization_settings.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/security_marks.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/source.proto
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4977 Refactoring Publisher.publishOutstandingBatch
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#4978 Moving methods from SequentialExecutor to subclasses
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
Labels: cla: yes

#4979 Refactoring SequentialExecutorService.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
Labels: cla: yes

#4980 Move Speech, Firestore, and KMS to GA list.
  README.md
  google-cloud-clients/google-cloud-speech/README.md
Labels: cla: yes

#4982 Cleaning up generics in SequentialExecutorService
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SequentialExecutorServiceTest.java
Labels: cla: yes

#4981 Adding comments to CallbackExecutor.submit
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
Labels: cla: yes

#4983 Exposing AutoExecutor and CallbackExecutor directly
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SequentialExecutorServiceTest.java
Labels: cla: yes

#4987 Regenerate firestore client
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/v1/FirestoreAdminClient.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/FirestoreAdminClientTest.java
  google-cloud-clients/google-cloud-firestore/synth.metadata
Labels: cla: yes

#4985 Add Kokoro config and script for building current structure of javadocs
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
Labels: cla: yes, type: docs

#4984 More refactoring to SequentialExecutor
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
Labels: cla: yes

#4955 Spanner: Aborted batch dml should be retried
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionContextImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerTest.java
Labels: cla: yes

#4988 Spanner: Refactor SpannerImpl - Remove dead code
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
Labels: cla: yes

#4989 Regenerate compute client
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Binding.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/FixedOrPercent.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/HealthCheck.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InsertNodeGroupHttpRequest.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InsertNodeTemplateHttpRequest.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InstanceGroupManager.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InstanceGroupManagerVersion.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/NodeGroup.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/NodeGroupClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/NodeTemplate.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/NodeTemplateClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Zone.java
  google-cloud-clients/google-cloud-compute/synth.metadata
Labels: cla: yes

#4991 Fix credentials and staging bucket for publish_javadoc job
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
Labels: cla: yes, type: docs

#4992 SequentialExecutorService.callNextTaskAsync only uses key
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SequentialExecutorServiceTest.java
Labels: cla: yes

#5005 add links to Tasks, Scheduler
  README.md
Labels: cla: yes

#4997 Regenerate datacatalog client
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/DataCatalogClient.java
  google-cloud-clients/google-cloud-datacatalog/synth.metadata
Labels: cla: yes

#5002 Regenerate vision client
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ProductSearchClient.java
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#5001 Regenerate translate client
  google-cloud-clients/google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceClient.java
  google-cloud-clients/google-cloud-translate/synth.metadata
Labels: cla: yes

#4999 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/securitycenter_service.proto
  google-cloud-clients/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/SecurityCenterClientTest.java
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#5004 Updating region tags for hello world
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigtable/HelloWorld.java
Labels: cla: yes

#4998 Regenerate datalabeling client
  google-cloud-clients/google-cloud-datalabeling/src/main/java/com/google/cloud/datalabeling/v1beta1/DataLabelingServiceClient.java
  google-cloud-clients/google-cloud-datalabeling/synth.metadata
Labels: cla: yes

#5006 Add VPCSC test.
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/VPCServiceControlTest.java
Labels: cla: yes

#5008 P/S: moving all alarm setup into a single method
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: api: pubsub, cla: yes

#4990 Bigtable: Added unit tests for `GCRule#fromProto`
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/GCRulesTest.java
Labels: cla: yes

#5007 Enhancing Publisher.OutstandingBatch
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: api: pubsub, cla: yes

#4996 Include user project in seemsLikeADirectoryAndUsePseudoDirectories
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
Labels: cla: yes

#5017 P/S Cleaning up unused code
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/it/ITPubSubTest.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakeScheduledExecutorService.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakeSubscriberServiceImpl.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDispatcherTest.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/OpenCensusUtilTest.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
Labels: cla: yes

#4965 Bigquery: Fix bug for ProjectId in listTableData.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
Labels: :rotating_light:, cla: yes

#5018 P/S refactoring Publisher.publish
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#5022 Update http-client-bom version to fixed version without jdo artifact
  google-cloud-clients/pom.xml
Labels: cla: yes, type: process

#5015 update to api-common 1.8.1
  google-api-grpc/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#5028 Update new client script
  utilities/batch_generate_apis.py
  utilities/bump_versions.py
  utilities/generate_api.py
  utilities/new_client.py
  utilities/replace_versions.py
  utilities/requirements.txt
  utilities/templates/README.md.tmpl
  utilities/templates/cloud_pom.xml
  utilities/templates/grpc_pom.xml
  utilities/templates/proto_pom.xml
  utilities/templates/synth.py
Labels: cla: yes, type: process

#5027 Add reCAPTCHA Enterprise client
  google-api-grpc/grpc-google-cloud-recaptchaenterprise-v1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/RecaptchaEnterpriseServiceV1Beta1Grpc.java
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/pom.xml
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/AnnotateAssessmentRequest.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/AnnotateAssessmentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/AnnotateAssessmentResponse.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/AnnotateAssessmentResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/Assessment.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/AssessmentName.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/AssessmentOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/CreateAssessmentRequest.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/CreateAssessmentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/Event.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/EventOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/ProjectName.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/RecaptchaEnterpriseProto.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/TokenProperties.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/TokenPropertiesOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/proto/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise.proto
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-recaptchaenterprise/README.md
  google-cloud-clients/google-cloud-recaptchaenterprise/pom.xml
  google-cloud-clients/google-cloud-recaptchaenterprise/src/main/java/com/google/cloud/recaptchaenterprise/v1beta1/RecaptchaEnterpriseServiceV1Beta1Client.java
  google-cloud-clients/google-cloud-recaptchaenterprise/src/main/java/com/google/cloud/recaptchaenterprise/v1beta1/RecaptchaEnterpriseServiceV1Beta1Settings.java
  google-cloud-clients/google-cloud-recaptchaenterprise/src/main/java/com/google/cloud/recaptchaenterprise/v1beta1/package-info.java
  google-cloud-clients/google-cloud-recaptchaenterprise/src/main/java/com/google/cloud/recaptchaenterprise/v1beta1/stub/GrpcRecaptchaEnterpriseServiceV1Beta1CallableFactory.java
  google-cloud-clients/google-cloud-recaptchaenterprise/src/main/java/com/google/cloud/recaptchaenterprise/v1beta1/stub/GrpcRecaptchaEnterpriseServiceV1Beta1Stub.java
  google-cloud-clients/google-cloud-recaptchaenterprise/src/main/java/com/google/cloud/recaptchaenterprise/v1beta1/stub/RecaptchaEnterpriseServiceV1Beta1Stub.java
  google-cloud-clients/google-cloud-recaptchaenterprise/src/main/java/com/google/cloud/recaptchaenterprise/v1beta1/stub/RecaptchaEnterpriseServiceV1Beta1StubSettings.java
  google-cloud-clients/google-cloud-recaptchaenterprise/src/test/java/com/google/cloud/recaptchaenterprise/v1beta1/MockRecaptchaEnterpriseServiceV1Beta1.java
  google-cloud-clients/google-cloud-recaptchaenterprise/src/test/java/com/google/cloud/recaptchaenterprise/v1beta1/MockRecaptchaEnterpriseServiceV1Beta1Impl.java
  google-cloud-clients/google-cloud-recaptchaenterprise/src/test/java/com/google/cloud/recaptchaenterprise/v1beta1/RecaptchaEnterpriseServiceV1Beta1ClientTest.java
  google-cloud-clients/google-cloud-recaptchaenterprise/synth.py
  google-cloud-clients/pom.xml
  versions.txt
Labels: cla: yes

#5034 Bigtable: clean up the public surface
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BaseBigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BaseBigtableInstanceAdminSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BaseBigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BaseBigtableTableAdminSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/package-info.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/BigtableInstanceAdminStub.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/BigtableTableAdminStub.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/GrpcBigtableInstanceAdminCallableFactory.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/GrpcBigtableInstanceAdminStub.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/GrpcBigtableTableAdminCallableFactory.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/GrpcBigtableTableAdminStub.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BaseBigtableDataClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BaseBigtableDataSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/package-info.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableStub.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableStubSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/GrpcBigtableCallableFactory.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/GrpcBigtableStub.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/package-info.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/reframing/package-info.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/ApiResultRetryAlgorithm.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/package-info.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/HiddenGapicApiTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BaseBigtableDataClientTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/HiddenGapicApiTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/MockBigtable.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/MockBigtableImpl.java
  google-cloud-clients/google-cloud-bigtable/synth.metadata
  google-cloud-clients/google-cloud-bigtable/synth.py
Labels: api: bigtable, cla: yes, type: cleanup

#5035 Bigtable: filter out all `@InternalApi` classed from the javadocs
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/pom.xml
Labels: api: bigtable, cla: yes, type: cleanup, type: docs

#5036 Regenerate dialogflow client
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/AudioConfigProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/AudioEncoding.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/InputAudioConfig.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/InputAudioConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/OutputAudioConfig.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/OutputAudioEncoding.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SessionProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SpeechModelVariant.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SsmlVoiceGender.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/audio_config.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/session.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AudioConfigProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/InputAudioConfig.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/InputAudioConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/OutputAudioEncoding.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SpeechModelVariant.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SsmlVoiceGender.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/audio_config.proto
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#5037 Regenerate recaptchaenterprise client
  google-cloud-clients/google-cloud-recaptchaenterprise/synth.metadata
Labels: cla: yes

#5039 Pubsub: Fix Publisher.shutdown should return promptly.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
Labels: cla: yes

#5032 Pub/Sub: add MessagesBatch.add method
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#5033 Pub/Sub: some Publisher.Builder variables are private
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#5040 Pub/Sub: Streamining publisher proto creation.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes
