Repository googleapis/google-cloud-java, pull requests merged in 2019-07, with the labels that each got.

#5607 Fix publisher throughput when there are no ordering keys.
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes, kokoro:force-run

#5621 [Bigtable] Fixes Query#toProto state change effect
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java
Labels: api: bigtable, cla: yes, type: feature request

#5616 Contrib : Cleanup dependency
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-nio-examples/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/pom.xml
Labels: cla: yes

#5615 Container Analysis : Cleanup dependency
  google-cloud-clients/google-cloud-containeranalysis/pom.xml
Labels: cla: yes

#5614 Container : Cleanup dependency
  google-cloud-clients/google-cloud-container/pom.xml
Labels: cla: yes

#5611 BigqueryDatatransfer : Cleanup dependency
  google-cloud-clients/google-cloud-bigquerydatatransfer/pom.xml
Labels: cla: yes

#5612 BigqueryStorage : Cleanup dependency
  google-cloud-clients/google-cloud-bigquerystorage/pom.xml
Labels: cla: yes

#5613 Bigtable : Cleanup dependency
  google-cloud-clients/google-cloud-bigtable/pom.xml
Labels: cla: yes

#5620 Datalabeling : Cleanup dependency
  google-cloud-clients/google-cloud-datalabeling/pom.xml
Labels: cla: yes

#5619 Datacatalog : Cleanup dependency
  google-cloud-clients/google-cloud-datacatalog/pom.xml
Labels: cla: yes

#5618 google-cloud-core-grpc : cleanup dependency
  google-cloud-clients/google-cloud-core-grpc/pom.xml
Labels: cla: yes

#5625 Spanner: Fix test cases for gax 1.47
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
Labels: cla: yes

#5200 Spanner: Create new instance if existing Spanner is closed
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Spanner.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
Labels: :rotating_light:, cla: yes

#5590 Update gax -> 1.47.0, guava -> 28.0-android, gson -> 2.8.5
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#5634 Regenerate video-intelligence client
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/proto/google/cloud/videointelligence/v1/video_intelligence.proto
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta1/src/main/java/com/google/cloud/videointelligence/v1beta1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta1/src/main/proto/google/cloud/videointelligence/v1beta1/video_intelligence.proto
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta2/src/main/java/com/google/cloud/videointelligence/v1beta2/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta2/src/main/proto/google/cloud/videointelligence/v1beta2/video_intelligence.proto
  google-api-grpc/proto-google-cloud-video-intelligence-v1p1beta1/src/main/java/com/google/cloud/videointelligence/v1p1beta1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p1beta1/src/main/proto/google/cloud/videointelligence/v1p1beta1/video_intelligence.proto
  google-api-grpc/proto-google-cloud-video-intelligence-v1p2beta1/src/main/java/com/google/cloud/videointelligence/v1p2beta1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p2beta1/src/main/proto/google/cloud/videointelligence/v1p2beta1/video_intelligence.proto
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/proto/google/cloud/videointelligence/v1p3beta1/video_intelligence.proto
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#5632 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecuritycenterService.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/securitycenter_service.proto
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#5656 Update gax.version to 1.47.1.
  google-cloud-clients/pom.xml
Labels: cla: yes

#5672 Spanner : Cleanup dependency
  google-cloud-clients/google-cloud-spanner/pom.xml
Labels: cla: yes

#5670 Scheduler : Cleanup dependency
  google-cloud-clients/google-cloud-scheduler/pom.xml
Labels: cla: yes

#5668 Recaptchaenterprise : Cleanup dependency
  google-cloud-clients/google-cloud-recaptchaenterprise/pom.xml
Labels: cla: yes

#5667 Pubsub : Cleanup dependency
  google-cloud-clients/google-cloud-pubsub/pom.xml
Labels: cla: yes

#5666 Phishingprotection : Cleanup dependency
  google-cloud-clients/google-cloud-phishingprotection/pom.xml
Labels: cla: yes

#5665 Os-login : Cleanup dependency
  google-cloud-clients/google-cloud-os-login/pom.xml
Labels: cla: yes

#5664 Monitoring : Cleanup dependency
  google-cloud-clients/google-cloud-monitoring/pom.xml
Labels: cla: yes

#5671 Securitycenter : Cleanup dependency
  google-cloud-clients/google-cloud-securitycenter/pom.xml
Labels: cla: yes

#5673 Speech : Cleanup dependency
  google-cloud-clients/google-cloud-speech/pom.xml
Labels: cla: yes

#5669 Redis : Cleanup dependency
  google-cloud-clients/google-cloud-redis/pom.xml
Labels: cla: yes

#5644 Language : Cleanup dependency
  google-cloud-clients/google-cloud-language/pom.xml
Labels: cla: yes

#5643 kms : Cleanup dependency
  google-cloud-clients/google-cloud-kms/pom.xml
Labels: cla: yes

#5641 IOT : Cleanup dependency
  google-cloud-clients/google-cloud-iot/pom.xml
Labels: cla: yes

#5640 Iamcredentials : Cleanup dependency
  google-cloud-clients/google-cloud-iamcredentials/pom.xml
Labels: cla: yes

#5638 ErrorReporting : Cleanup dependency
  google-cloud-clients/google-cloud-errorreporting/pom.xml
Labels: cla: yes

#5637 Dlp : Cleanup dependency
  google-cloud-clients/google-cloud-dlp/pom.xml
Labels: cla: yes

#5635 Dataproc : Cleanup dependency
  google-cloud-clients/google-cloud-dataproc/pom.xml
Labels: cla: yes

#5636 Dialogflow : Cleanup dependency
  google-cloud-clients/google-cloud-dialogflow/pom.xml
Labels: cla: yes

#5660 Regenerate talent client
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobServiceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/job_service.proto
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#5645 Logging : Cleanup dependency
  google-cloud-clients/google-cloud-logging/pom.xml
Labels: cla: yes

#5628 Add Tasks smoke test
  google-cloud-clients/google-cloud-tasks/src/test/java/com/google/cloud/tasks/v2beta3/CloudTasksSmokeTest.java
Labels: cla: yes

#5681 Talent : Cleanup dependency
  google-cloud-clients/google-cloud-talent/pom.xml
Labels: cla: yes

#5682 Tasks : Cleanup dependency
  google-cloud-clients/google-cloud-tasks/pom.xml
Labels: cla: yes

#5691 google-cloud-client : Cleanup dependency
  google-cloud-clients/pom.xml
Labels: cla: yes

#5683 Texttospeech : Cleanup dependency
  google-cloud-clients/google-cloud-texttospeech/pom.xml
Labels: cla: yes

#5684 Trace : Cleanup dependency
  google-cloud-clients/google-cloud-trace/pom.xml
Labels: cla: yes

#5685 Compute : Cleanup dependency
  google-cloud-clients/google-cloud-compute/pom.xml
Labels: cla: yes

#5688 Dns : Cleanup dependency
  google-cloud-clients/google-cloud-dns/pom.xml
Labels: cla: yes

#5675 Regenerate dialogflow client
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/AgentsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/AgentsSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/package-info.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/AgentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/AgentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/GrpcAgentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentsClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentsSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/package-info.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/AgentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/AgentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/GrpcAgentsStub.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/AgentsClientTest.java
  google-cloud-clients/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/AgentsClientTest.java
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#5693 google-cloud-client : testlib and junit
  google-cloud-clients/pom.xml
Labels: cla: yes

#5678 Regenerate dlp client
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/Action.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ActionOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/CustomInfoType.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpProto.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/dlp.proto
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/storage.proto
  google-cloud-clients/google-cloud-dlp/synth.metadata
Labels: cla: yes

#5689 Resourcemanager : Cleanup dependency
  google-cloud-clients/google-cloud-resourcemanager/pom.xml
Labels: cla: yes

#5695 Add VPCSC tests for cloud asset client lib
  google-cloud-clients/google-cloud-asset/src/test/java/com/google/cloud/asset/v1/VPCServiceControlTest.java
Labels: cla: yes

#5525 Storage: add service api to read storage object in to output stream using direct download
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
Labels: cla: yes

#5624 Pubsub ordering keys
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakePublisherServiceImpl.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SequentialExecutorServiceTest.java
Labels: api: pubsub, cla: yes

#5710 Pub/Sub: Replacing AutoClosable with BackgrondResource
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: cla: yes

#5709 Spanner: Add specific timeout for Partitioned DML with default of 2 hours
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Labels: cla: yes

#5658 Update resumption strategy to use format-independent row count.
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ReadRowsResumptionStrategy.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/it/ITBigQueryStorageLongRunningTest.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/it/ITBigQueryStorageTest.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ReadRowsRetryTest.java
Labels: api: bigquery, cla: yes

#5715 Add additional assertions to DatabaseClientImplTest.
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Labels: cla: yes

#5642 Firestore: Fix float fields to accept in pojos.
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/WriteBatchTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#5594 Add VPC-SC positive and negative integration tests in Web Security Scanner
  google-cloud-clients/google-cloud-websecurityscanner/pom.xml
  google-cloud-clients/google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/it/v1beta/VPCServiceControlNegativeTest.java
  google-cloud-clients/google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/it/v1beta/VPCServiceControlPositiveTest.java
Labels: cla: yes

#5718 Remove fallback for yoshi-java
  .github/CODEOWNERS
Labels: cla: yes

#5726 Regenerate automl client
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Tables.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TablesModelMetadata.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TablesModelMetadataOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/tables.proto
  google-cloud-clients/google-cloud-automl/synth.metadata
Labels: cla: yes

#5727 Regenerate gameservices client
  google-cloud-clients/google-cloud-gameservices/synth.metadata
Labels: cla: yes

#5591 BigQuery: Add routines support
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Routine.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/RoutineArgument.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/RoutineId.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/RoutineInfo.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardSQLDataType.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardSQLField.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardSQLStructType.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/testing/RemoteBigQueryHelper.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineArgumentTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineIdTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineInfoTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardSQLDataTypeTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardSQLFieldTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardSQLStructTypeTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#5717 BigQuery: Implement missing list options
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#5730 Regenerate dialogflow client
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/AudioConfigProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/InputAudioConfig.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/InputAudioConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/QueryResult.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/QueryResultOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SessionProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/StreamingDetectIntentRequest.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/StreamingDetectIntentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/StreamingRecognitionResult.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/StreamingRecognitionResultOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/audio_config.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/session.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AudioConfigProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/DetectIntentRequest.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/DetectIntentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/InputAudioConfig.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/InputAudioConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/Intent.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/IntentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/QueryResult.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/QueryResultOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/StreamingDetectIntentRequest.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/StreamingDetectIntentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/StreamingRecognitionResult.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/StreamingRecognitionResultOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/audio_config.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/document.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/intent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/session.proto
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionsClient.java
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#5742 Bigtable: Fix stale docs
  google-cloud-clients/google-cloud-bigtable/README.md
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
Labels: api: bigtable, cla: yes, type: docs

#5745 Update enum Regions.java with latest regions
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/Regions.java
Labels: cla: yes

#5740 Ignore guava, protobuf, opencensus for renovate
  renovate.json
Labels: cla: yes

#5707 Update the storage mock so that copied objects can be read
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/testing/LocalStorageHelperTest.java
Labels: api: storage, cla: yes

#5751 Mark ordering keys APIs public
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#5542 Update firestore conformance tests
  google-cloud-clients/google-cloud-firestore/pom.xml
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceConversions.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/conformance/TestDefinition.java
  google-cloud-clients/google-cloud-firestore/src/test/resources/com/google/cloud/firestore/conformance/test-suite.binproto
Labels: cla: yes

#5725 Storage: Fix locationType field is added in bucket
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#5748 Regenerate datalabeling client
  google-api-grpc/proto-google-cloud-datalabeling-v1beta1/src/main/java/com/google/cloud/datalabeling/v1beta1/DataLabelingServiceOuterClass.java
  google-api-grpc/proto-google-cloud-datalabeling-v1beta1/src/main/proto/google/cloud/datalabeling/v1beta1/data_labeling_service.proto
  google-cloud-clients/google-cloud-datalabeling/synth.metadata
Labels: cla: yes

#5752 Bigtable: improve ReadIt test failure mode to give the underlying error
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/ReadIT.java
Labels: api: bigtable, cla: yes, type: cleanup

#5762 Bigtable: fix integration tests
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
  google-cloud-examples/pom.xml
Labels: api: bigtable, cla: yes, type: bug

#5743 Firestore: Port @DocumentId to server SDK
  google-cloud-clients/google-cloud-firestore/pom.xml
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/CustomClassMapper.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/QuerySnapshot.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/annotation/DocumentId.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/MapperTest.java
Labels: cla: yes

#5732 BigQuery: update signature for ML model access to label/feature columns.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Model.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ModelInfo.java
Labels: cla: yes

#5769 Bigtable: Update integration tests to use the bundled emulator
  TESTING.md
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/env/Emulator.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/env/EmulatorEnv.java
  google-cloud-testing/google-cloud-gcloud-maven-plugin/src/main/java/com/google/cloud/DownloadComponentsMojo.java
Labels: api: bigtable, cla: yes

#5786 Logging:Fix Deprecated warnings removed logging 5287
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/SinkInfo.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingImplTest.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/SinkInfoTest.java
Labels: cla: yes

#5782 Regenerate talent client
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Activity.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ActivityOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/BatchOperationMetadata.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/BatchUpdateJobsRequest.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/BatchUpdateJobsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Company.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/CompanyOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/FiltersProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobOperationResult.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobQuery.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobQueryOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobServiceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/PersonNameFilter.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/PersonNameFilterOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Profile.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileEvent.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileQuery.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileQueryOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileServiceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/SearchProfilesRequest.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/SearchProfilesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/batch.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/company.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/event.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/filters.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/job_service.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/profile.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/profile_service.proto
  google-cloud-clients/google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/JobServiceStubSettings.java
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#5771 Regenerate asset client
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/stub/AssetServiceStubSettings.java
  google-cloud-clients/google-cloud-asset/synth.metadata
Labels: cla: yes

#5775 Regenerate dataproc client
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/stub/ClusterControllerStubSettings.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/stub/WorkflowTemplateServiceStubSettings.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/stub/ClusterControllerStubSettings.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/stub/WorkflowTemplateServiceStubSettings.java
  google-cloud-clients/google-cloud-dataproc/synth.metadata
Labels: cla: yes

#5756 Bigtable: Add ability to run tests against direct path
  .kokoro/continuous/bigtable-it.cfg
  .kokoro/nightly/bigtable-it.cfg
  .kokoro/presubmit/bigtable-it.cfg
  TESTING.md
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/google-cloud-bigtable/scripts/setup-test-table.sh
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/env/DirectPathEnv.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/env/TestEnvRule.java
  google-cloud-testing/google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/Emulator.java
  google-cloud-testing/google-cloud-gcloud-maven-plugin/src/main/java/com/google/cloud/DownloadComponentsMojo.java
Labels: api: bigtable, cla: yes

#5794 Bigtable: update retry & timeout settings
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/BigtableInstanceAdminStubSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/BigtableTableAdminStubSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableStubSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
  google-cloud-clients/google-cloud-bigtable/synth.metadata
Labels: cla: yes

#5790 Remove pmd.xml
  .eclipse-pmd
  pmd.xml
Labels: cla: yes

#5746 Add debugging information for Firestore integration tests
  .kokoro/build.sh
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#5805 spanner-jdbc: Step 01 - Create jdbc project
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/pom.xml
  versions.txt
Labels: cla: yes

#5796 Undefined name: Fix typo on viariable name
  utilities/add_snippets_to_file.py
Labels: cla: yes

#5806 spanner-jdbc: Step 02 - Client side statement interfaces
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AutocommitDmlMode.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ClientSideStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionStatementExecutor.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/StatementResult.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/TransactionMode.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/com/google/cloud/spanner/jdbc/ClientSideStatements.json
Labels: cla: yes

#5807 spanner-jdbc: Step 03 - Generic connection interface
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AutocommitDmlMode.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/Connection.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/TransactionRetryListener.java
Labels: cla: yes

#5824 Regenerate datacatalog client
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/DataCatalogSettings.java
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/package-info.java
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/DataCatalogStubSettings.java
  google-cloud-clients/google-cloud-datacatalog/synth.metadata
Labels: cla: yes

#5818 Regenerate bigquerydatatransfer client
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceSettings.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/package-info.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/DataTransferServiceStubSettings.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
Labels: cla: yes

#5779 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupFindingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupFindingsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListAssetsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListAssetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListFindingsRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListFindingsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/securitycenter_service.proto
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/stub/SecurityCenterStubSettings.java
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/stub/SecurityCenterStubSettings.java
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#5772 Regenerate automl client
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/AutoMlStubSettings.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/PredictionServiceStubSettings.java
  google-cloud-clients/google-cloud-automl/synth.metadata
Labels: cla: yes

#5778 Regenerate redis client
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/CloudRedisStubSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
  google-cloud-clients/google-cloud-redis/synth.metadata
Labels: cla: yes

#5776 Regenerate dialogflow client
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/EntityTypeProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/agent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/entity_type.proto
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/AgentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/EntityTypesStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/IntentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/AgentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/DocumentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/EntityTypesStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/IntentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#5781 Regenerate speech client
  google-cloud-clients/google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/SpeechStubSettings.java
  google-cloud-clients/google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/SpeechStubSettings.java
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#5777 Regenerate gameservices client
  google-cloud-clients/google-cloud-gameservices/src/main/java/com/google/cloud/gaming/v1alpha/stub/AllocationPoliciesServiceStubSettings.java
  google-cloud-clients/google-cloud-gameservices/src/main/java/com/google/cloud/gaming/v1alpha/stub/GameServerClustersServiceStubSettings.java
  google-cloud-clients/google-cloud-gameservices/src/main/java/com/google/cloud/gaming/v1alpha/stub/GameServerDeploymentsServiceStubSettings.java
  google-cloud-clients/google-cloud-gameservices/src/main/java/com/google/cloud/gaming/v1alpha/stub/RealmsServiceStubSettings.java
  google-cloud-clients/google-cloud-gameservices/src/main/java/com/google/cloud/gaming/v1alpha/stub/ScalingPoliciesServiceStubSettings.java
  google-cloud-clients/google-cloud-gameservices/synth.metadata
Labels: cla: yes

#5783 Regenerate translate client
  google-cloud-clients/google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/TranslationServiceStubSettings.java
  google-cloud-clients/google-cloud-translate/synth.metadata
Labels: cla: yes

#5784 Regenerate vision client
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ProductSearchStubSettings.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/ImageAnnotatorStubSettings.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/ProductSearchStubSettings.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/ImageAnnotatorStubSettings.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/ProductSearchStubSettings.java
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#5774 Regenerate datalabeling client
  google-cloud-clients/google-cloud-datalabeling/src/main/java/com/google/cloud/datalabeling/v1beta1/stub/DataLabelingServiceStubSettings.java
  google-cloud-clients/google-cloud-datalabeling/synth.metadata
Labels: cla: yes

#5811 bigquery: update streaming insert snippet to better indicate usage.
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java
Labels: cla: yes

#5813 spanner-jdbc: Step 05 - Util for parsing read-only staleness values
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ReadOnlyStalenessUtil.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ReadOnlyStalenessUtilTest.java
Labels: cla: yes

#5815 spanner-jdbc: Step 07 - DirectExecuteResultSet
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/DirectExecuteResultSet.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/DirectExecuteResultSetTest.java
Labels: cla: yes

#5816 spanner-jdbc: Step 08 - ReplaceableForwardingResultSet
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ReplaceableForwardingResultSet.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ReplaceableForwardingResultSetTest.java
Labels: cla: yes

#5848 spanner-jdbc: Step 10 - Added additional comments to JDBC Connection interface
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/CloudSpannerJdbcConnection.java
Labels: cla: yes

#5847 spanner-jdbc: Step 09 - StatementResultImpl
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionPreconditions.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/StatementResultImpl.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SpannerExceptionMatcher.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/StatementResultImplTest.java
Labels: cla: yes

#5814 spanner-jdbc: Step 06 - Client side statement parser
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ClientSideStatementExecutor.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ClientSideStatementImpl.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ClientSideStatementNoParamExecutor.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ClientSideStatementSetExecutor.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ClientSideStatementValueConverter.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ClientSideStatementValueConverters.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ClientSideStatements.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/StatementParser.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/TransactionMode.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/com/google/cloud/spanner/jdbc/ClientSideStatements.json
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/AutocommitDmlModeConverterTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/BooleanConverterTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/DurationConverterTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ReadOnlyStalenessConverterTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/StatementParserTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/TransactionModeConverterTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/CommentsTest.sql
Labels: cla: yes

#5876 spanner-jdbc: Step 12 - Specific AbortedExceptions for failed transaction retries
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbortedDueToConcurrentModificationException.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
Labels: cla: yes

#5871 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeakerDiarizationConfig.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeakerDiarizationConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechProto.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
  google-cloud-clients/google-cloud-speech/src/main/java/com/google/cloud/speech/v1/SpeechSettings.java
  google-cloud-clients/google-cloud-speech/src/main/java/com/google/cloud/speech/v1/package-info.java
  google-cloud-clients/google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/SpeechStubSettings.java
  google-cloud-clients/google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechSettings.java
  google-cloud-clients/google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/package-info.java
  google-cloud-clients/google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/SpeechStubSettings.java
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#5881 spanner-jdbc: Step 14 - Add base interface for unit of work on connections
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AnalyzeMode.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/UnitOfWork.java
Labels: cla: yes

#5877 spanner-jdbc: Step 13 - Add JDBC types and type mappings for Cloud Spanner
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcArray.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcBlob.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcClob.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDataType.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcPreconditions.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcSqlExceptionFactory.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcTypeConverter.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcArrayTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcBlobTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcClobTest.java
Labels: cla: yes

#5892 Regenerate dialogflow client
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/QueryResult.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/QueryResultOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/session.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AudioConfigProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/InputAudioConfig.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/InputAudioConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/QueryResult.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/QueryResultOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SpeechContext.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SpeechContextOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/audio_config.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/session.proto
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#5893 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeakerDiarizationConfig.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#5875 spanner-jdbc: Step 11 - CredentialService
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/CredentialsService.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/CredentialsServiceTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/test-key-app-default.json
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/test-key-cloud-storage.json
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/test-key.json
Labels: cla: yes

#5896 spanner-jdbc: Step 19 - SingleUseTransaction
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/SingleUseTransaction.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SingleUseTransactionTest.java
Labels: cla: yes

#5897 spanner-jdbc: Step 20 - ReadOnlyTransaction
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractMultiUseTransaction.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ReadOnlyTransaction.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ReadOnlyTransactionTest.java
Labels: cla: yes

#5882 Add CSEK decryption for storage.get(BlobId,..)
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: api: storage, cla: yes, type: feature request

#5890 spanner-jdbc: Step 15 - ConnectionOptions and SpannerPool
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionImpl.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionOptions.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ReadOnlyStalenessUtil.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/SpannerPool.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/StatementExecutionInterceptor.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionOptionsTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SpannerPoolTest.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
Labels: cla: yes

#5891 spanner-jdbc: Step 16 - JdbcResultSet
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcResultSet.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcWrapper.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcArray.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcClob.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSet.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSetMetaData.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/AbstractJdbcWrapperTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetMetaDataTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java
Labels: cla: yes

#5894 spanner-jdbc: Step 17 - Base class for transactions and batches
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractBaseUnitOfWork.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/StatementExecutor.java
Labels: cla: yes

#5895 spanner-jdbc: Step 18 - ConnectionImpl
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionImpl.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionStatementExecutorImpl.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/DdlClient.java
Labels: cla: yes

#5916 Firestore: Add @Deprecated annotation to getCollections
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java
Labels: cla: yes

#5917 spanner-jdbc: Add to contrib module
  google-cloud-clients/google-cloud-contrib/pom.xml
Labels: cla: yes

#5883 TextToSpeech: Fix #4595 update default inbound msg size to max
  google-cloud-clients/google-cloud-texttospeech/synth.py
Labels: cla: yes

#5759 Expose FullEntity::fromPb and Value::fromPb
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/Entity.java
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/FullEntity.java
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/Value.java
Labels: api: datastore, cla: yes

#5915 feat: allow endpoint override on Publisher/Subscriber
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: cla: yes

#5902 Refactor com.google.cloud.firestore.it.ITSystemTest.queryWatch to make it more reliable.
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: api: firestore, cla: yes

#5898 spanner-jdbc: Step 21 - ReadWriteTransaction
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ChecksumResultSet.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/FailedBatchUpdate.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/FailedQuery.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/FailedUpdate.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ReadWriteTransaction.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/RetriableBatchUpdate.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/RetriableUpdate.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ReadWriteTransactionTest.java
Labels: cla: yes

#5908 spanner-jdbc: Step 23 - DmlBatch
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/DmlBatch.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/DmlBatchTest.java
Labels: cla: yes

#5910 spanner-jdbc: Step 25 - JdbcConnection implementation
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcConnection.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcExceptionMatcher.java
Labels: cla: yes

#5911 spanner-jdbc: Step 26 - JDBC Statement and PreparedStatement implementation
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcConstants.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterMetaData.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTest.java
Labels: cla: yes

#5907 spanner-jdbc: Step 22 - DdlBatch
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/Connection.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/DdlBatch.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/UnitOfWork.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/DdlBatchTest.java
Labels: cla: yes

#5927 Make LoggingAppender.getLoggingOptions() protected
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
Labels: cla: yes

#5617 Core: Cleanup unused dependencies
  google-cloud-clients/google-cloud-core/pom.xml
Labels: cla: yes

#5286 Bigtable: clean up redundant code
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
Labels: cla: yes

#5926 Add missing BucketField fields
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
Labels: cla: yes

#5690 grafeas: Cleanup unused dependencies
  google-cloud-clients/grafeas/pom.xml
Labels: cla: yes

#5687 Datastore : cleanup dependency
  google-cloud-clients/google-cloud-datastore/pom.xml
Labels: cla: yes

#5639 Firestore: Cleanup unused dependencies
  google-cloud-clients/google-cloud-firestore/pom.xml
Labels: cla: yes

#5686 Core-http: Cleanup unused dependencies
  google-cloud-clients/google-cloud-core-http/pom.xml
Labels: cla: yes

#5680 Storage: Cleanup unused dependencies
  google-cloud-clients/google-cloud-storage/pom.xml
Labels: cla: yes

#5791 Storage: Fix slow download performance
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
Labels: cla: yes

#5909 spanner-jdbc: Step 24 - Parameter store for jdbc parameters
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterStore.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java
Labels: cla: yes

#5912 spanner-jdbc: Step 27 - JdbcDriver
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDataSource.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/META-INF/services/java.sql.Driver
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcDriverTest.java
Labels: cla: yes

#5913 spanner-jdbc: Step 28 - JdbcDatabaseMetadata
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetColumns.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetCrossReferences.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetExportedKeys.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetImportedKeys.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetIndexInfo.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetPrimaryKeys.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetSchemas.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetTables.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java
Labels: cla: yes

#5928 Firestore: Add note about potential flakiness in the new Watch test
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#5931 spanner-jdbc-cleanup - Step 01 - Fix compile errors and test failures
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ChecksumResultSet.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/FailedQuery.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ReadWriteTransaction.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/RetriableBatchUpdate.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/RetriableUpdate.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/AbstractConnectionImplTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcDriverTest.java
Labels: cla: yes

#5932 spanner-jdbc-cleanup - Step 02 - Fix formatting
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractBaseUnitOfWork.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcConnection.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcResultSet.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AnalyzeMode.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ChecksumResultSet.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/Connection.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionImpl.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionStatementExecutorImpl.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/DdlBatch.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/DdlClient.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/DmlBatch.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/FailedBatchUpdate.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/FailedQuery.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/FailedUpdate.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcConstants.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDataSource.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterMetaData.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterStore.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSet.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSetMetaData.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ReadWriteTransaction.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/RetriableBatchUpdate.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/RetriableUpdate.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/StatementExecutor.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/UnitOfWork.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/AbstractConnectionImplTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/DdlBatchTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/DmlBatchTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcDriverTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcExceptionMatcher.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTest.java
Labels: cla: yes
