Repository googleapis/google-cloud-java, pull requests merged in 2019-08, with the labels that each got.

#5750 Firestore: Fix FieldValue.arrayUnion() accept POJO.
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldValue.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
Labels: cla: yes

#5952 Spanner: Handle aborted transactions when using TransactionManager
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerAbortedTest.java
Labels: api: spanner, cla: yes, type: bug

#5954 spanner-jdbc: Set clientLibToken on RPC instance
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
Labels: cla: yes

#5955 Bigtable: remove integration tests from the default failsafe execution
  google-cloud-clients/google-cloud-bigtable/pom.xml
Labels: api: bigtable, cla: yes, type: bug

#5901 Storage: Update conformance tests
  google-cloud-clients/google-cloud-storage/pom.xml
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/V4SigningTest.java
  google-cloud-clients/google-cloud-storage/src/test/resources/UrlSignerV4TestAccount.json
  google-cloud-clients/google-cloud-storage/src/test/resources/UrlSignerV4TestData.json
Labels: api: storage, cla: yes, type: cleanup

#5934 spanner-jdbc-cleanup - Step 04 - SQL Based Tests
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/AbstractSqlScriptVerifier.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ClientSideStatementsTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplAutocommitReadOnlyTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplAutocommitReadWriteTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplGeneratedSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplTransactionalReadOnlyTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplTransactionalReadWriteTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionGeneratedSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcSqlScriptVerifier.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcTimeoutSqlTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ReplaceableForwardingResultSetTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SetReadOnlyStalenessSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SetStatementTimeoutSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SqlScriptVerifier.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SqlTestScriptsGenerator.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/StatementParserTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ClientSideStatementsTest.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ConnectionImplGeneratedSqlScriptTest.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/SetReadOnlyStalenessTest.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/SetStatementTimeoutTest.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/TimeoutSqlScriptTest.sql
Labels: cla: yes

#5800 Storage: Bucket metadata sample
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: cla: yes

#5924 Firestore: add emulator support
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
Labels: cla: yes

#5996 spanner-jdbc-cleanup - Step 07 - Increase timeout when creating a new test instance
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
Labels: cla: yes

#6000 Add Spanner JDBC kokoro configs.
  .kokoro/continuous/spannerjdbc-it.cfg
  .kokoro/nightly/spannerjdbc-it.cfg
  .kokoro/presubmit/spannerjdbc-it.cfg
Labels: cla: yes

#5998 spanner-jdbc-cleanup - Step 09 - DDL integration tests
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/DdlBatch.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SqlScriptVerifier.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITDdlTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcDdlTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITDdlTest.sql
Labels: cla: yes

#6003 spanner-jdbc-cleanup - Step 13 - Add integration tests for transactions and retries
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITTransactionModeTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITTransactionRetryTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITTransactionModeTest.sql
Labels: cla: yes

#5999 spanner-jdbc-cleanup - Step 10 - Integration tests using only SQL scripts
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_CreateTables.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_InsertTestData.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestAutocommitDmlMode.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestAutocommitReadOnly.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestGetCommitTimestamp.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestGetReadTimestamp.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestInvalidStatements.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestReadOnlyStaleness.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestSetStatements.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestStatementTimeout.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestTemporaryTransactions.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestTransactionMode.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestTransactionMode_ReadOnly.sql
Labels: cla: yes

#6010 spanner-jdbc: Fix version numbers
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/pom.xml
Labels: cla: yes

#6005 spanner-jdbc-cleanup - Step 15 - Add Integration Tests for ReadOnlyTransaction
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadOnlyTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITReadOnlySpannerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITReadOnlySpannerTest.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITReadOnlySpannerTest_CreateTables.sql
Labels: cla: yes

#6006 spanner-jdbc-cleanup - Step 16 - Add integration tests for autocommit
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadWriteAutocommitTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITReadWriteAutocommitSpannerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITReadWriteAutocommitSpannerTest.sql
Labels: cla: yes

#6011 spanner-jdbc - Upgrade http client to support nanosecond support
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ReadOnlyStalenessUtil.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ReadOnlyStalenessConverterTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ReadOnlyStalenessUtilTest.java
  google-cloud-clients/pom.xml
Labels: cla: yes

#6012 spanner-jdbc: Run code formatter
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/DdlBatch.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ReadOnlyStalenessUtil.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/AbstractSqlScriptVerifier.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/AutocommitDmlModeTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ClientSideStatementsTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplAutocommitReadOnlyTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplAutocommitReadWriteTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplGeneratedSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplTransactionalReadOnlyTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplTransactionalReadWriteTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionStatementExecutorTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionStatementWithNoParametersTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionStatementWithOneParameterTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/CredentialsServiceTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/DdlClientTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ITAbstractJdbcTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ITAbstractSpannerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcAbortedTransactionTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionGeneratedSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcGrpcErrorTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcSqlScriptVerifier.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcTimeoutSqlTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ReadOnlyStalenessTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SetReadOnlyStalenessSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SetStatementTimeoutSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SpannerJdbcExceptionMatcher.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SqlScriptVerifier.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/StatementTimeoutTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITBulkConnectionTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITDdlTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcConnectTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcDdlTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadOnlyTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadWriteAutocommitTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITReadOnlySpannerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITReadWriteAutocommitSpannerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITTransactionModeTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITTransactionRetryTest.java
Labels: cla: yes

#6013 spanner-jdbc: Fix timezone test bug
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java
Labels: cla: yes

#6014 spanner-jdbc: Run code formatter on Spanner project
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
Labels: cla: yes

#5959 Move setClientLibToken to ServiceOptions.
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
Labels: cla: yes

#6016 spanner-jdbc: Run code formatter on SpannerOptions
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
Labels: cla: yes

#6017 spanner-jdbc: Run code formatter on core ServiceOptions
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java
Labels: cla: yes

#5930 Regenerate video-intelligence client
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/SpeechRecognitionAlternative.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/SpeechRecognitionAlternativeOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoAnnotationProgress.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoAnnotationProgressOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoAnnotationResults.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoAnnotationResultsOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/proto/google/cloud/videointelligence/v1/video_intelligence.proto
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#5956 Regenerate monitoring client
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/NotificationChannelServiceClient.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/NotificationChannelServiceSettings.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcNotificationChannelServiceStub.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/NotificationChannelServiceStub.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/NotificationChannelServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockNotificationChannelServiceImpl.java
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/NotificationChannelServiceClientTest.java
  google-cloud-clients/google-cloud-monitoring/synth.metadata
Labels: cla: yes

#6021 Change JDBC version number to 0.0.1-SNAPSHOT for release prep.
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/pom.xml
  versions.txt
Labels: cla: yes

#6023 Bulk client regen: set default maxInboundMessageSize to max int (part 2)
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  google-cloud-clients/google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/stub/AssetServiceStubSettings.java
  google-cloud-clients/google-cloud-asset/synth.metadata
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/AutoMlStubSettings.java
  google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/PredictionServiceStubSettings.java
  google-cloud-clients/google-cloud-automl/synth.metadata
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/DataTransferServiceStubSettings.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/BigQueryStorageStubSettings.java
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/BigtableInstanceAdminStubSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/BigtableTableAdminStubSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableStubSettings.java
  google-cloud-clients/google-cloud-bigtable/synth.metadata
  google-cloud-clients/google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/ClusterManagerStubSettings.java
  google-cloud-clients/google-cloud-container/synth.metadata
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/ContainerAnalysisStubSettings.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1beta1/stub/ContainerAnalysisV1Beta1StubSettings.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1beta1/stub/GrafeasV1Beta1StubSettings.java
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/DataCatalogStubSettings.java
  google-cloud-clients/google-cloud-datacatalog/synth.metadata
  google-cloud-clients/google-cloud-datalabeling/src/main/java/com/google/cloud/datalabeling/v1beta1/stub/DataLabelingServiceStubSettings.java
  google-cloud-clients/google-cloud-datalabeling/synth.metadata
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/stub/ClusterControllerStubSettings.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/stub/JobControllerStubSettings.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/stub/WorkflowTemplateServiceStubSettings.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/stub/AutoscalingPolicyServiceStubSettings.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/stub/ClusterControllerStubSettings.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/stub/JobControllerStubSettings.java
  google-cloud-clients/google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1beta2/stub/WorkflowTemplateServiceStubSettings.java
  google-cloud-clients/google-cloud-dataproc/synth.metadata
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/AgentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/ContextsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/EntityTypesStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/IntentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/SessionEntityTypesStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/SessionsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/AgentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/ContextsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/DocumentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/EntityTypesStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/IntentsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/KnowledgeBasesStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/SessionEntityTypesStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/SessionsStubSettings.java
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
  google-cloud-clients/google-cloud-dlp/src/main/java/com/google/cloud/dlp/v2/stub/DlpServiceStubSettings.java
  google-cloud-clients/google-cloud-dlp/synth.metadata
Labels: cla: yes

#5982 Regenerate pubsub client
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/MessageStoragePolicy.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/MessageStoragePolicyOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PushConfig.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PushConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Topic.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
  google-cloud-clients/google-cloud-pubsub/synth.py
Labels: cla: yes

#6032 spanner-jdbc - Use standard data model for tests
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/StatementParserTest.java
Labels: cla: yes

#6029 Regenerate texttospeech client
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1/stub/TextToSpeechStubSettings.java
  google-cloud-clients/google-cloud-texttospeech/src/main/java/com/google/cloud/texttospeech/v1beta1/stub/TextToSpeechStubSettings.java
  google-cloud-clients/google-cloud-texttospeech/synth.metadata
Labels: cla: yes

#6030 Regenerate video-intelligence client
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta2/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p1beta1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p2beta1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/stub/StreamingVideoIntelligenceServiceStubSettings.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/stub/VideoIntelligenceServiceStubSettings.java
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#6027 Regenerate monitoring client
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/AlertPolicyServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GroupServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/MetricServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/NotificationChannelServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/UptimeCheckServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/synth.metadata
Labels: cla: yes

#6028 Regenerate talent client
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/CustomAttribute.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/CustomAttributeOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/EducationRecord.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/EducationRecordOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/EmploymentRecord.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/EmploymentRecordOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/FiltersProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/HistogramProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobResourceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobServiceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Profile.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileEvent.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileQuery.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileQueryOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileResourceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Resume.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ResumeOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/TenantResourceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/common.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/event.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/filters.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/histogram.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/job.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/job_service.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/profile.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/tenant.proto
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#6026 Regenerate dialogflow client
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/agent.proto
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#6036 spanner-jdbc: Fix potential flaky integration test
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITTransactionRetryTest.java
Labels: cla: yes

#6044 Regenerate talent client
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/LocationFilter.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/LocationFilterOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Profile.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/TenantResourceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/filters.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/profile.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/tenant.proto
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#6046 Regenerate vision client
  google-api-grpc/grpc-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchGrpc.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/AnnotateFileResponse.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/AnnotateFileResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/AsyncBatchAnnotateFilesRequest.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/AsyncBatchAnnotateFilesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/AsyncBatchAnnotateImagesRequest.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/AsyncBatchAnnotateImagesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/BatchAnnotateFilesRequest.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/BatchAnnotateFilesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/BatchAnnotateImagesRequest.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/BatchAnnotateImagesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ImageAnnotatorProto.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/Likelihood.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/Paragraph.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ParagraphOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/Product.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchProto.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchResults.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchServiceProto.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSetPurgeConfig.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSetPurgeConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/PurgeProductsRequest.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/PurgeProductsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/Symbol.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/SymbolOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/WebDetection.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/WebDetectionProto.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/image_annotator.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search_service.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/text_annotation.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/web_detection.proto
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ProductSearchClient.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ProductSearchSettings.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/GrpcImageAnnotatorStub.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/GrpcProductSearchStub.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ProductSearchStub.java
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ProductSearchStubSettings.java
  google-cloud-clients/google-cloud-vision/src/test/java/com/google/cloud/vision/v1/MockProductSearchImpl.java
  google-cloud-clients/google-cloud-vision/src/test/java/com/google/cloud/vision/v1/ProductSearchClientTest.java
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#6045 Regenerate video-intelligence client
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoAnnotationResults.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoAnnotationResultsOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/proto/google/cloud/videointelligence/v1/video_intelligence.proto
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#6047 spanner-jdbc: Add beta note to README and cleanup pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/pom.xml
Labels: cla: yes

#6037 Bigtable: update docs to stress that client creation is expensive
  google-cloud-clients/google-cloud-bigtable/README.md
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
Labels: api: bigtable, cla: yes, type: docs

#6052 Add Spanner JDBC driver to contrib readme.
  google-cloud-clients/google-cloud-contrib/README.md
Labels: cla: yes

#6065 Spanner: Fix retry test cases for database and instance admin operations
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
Labels: cla: yes

#6058 Regenerate dialogflow client
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/session.proto
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#6059 Regenerate talent client
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/TenantResourceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/UpdateProfileRequest.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/UpdateProfileRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/profile_service.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/tenant.proto
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#5780 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/DatabaseAdminStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/stub/InstanceAdminStubSettings.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#6054 Elevate access level of CollectionReference to support mocking
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
Labels: cla: yes

#6068 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/package-info.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/DatabaseAdminStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/package-info.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/stub/InstanceAdminStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/package-info.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#6072 Regenerate kms client
  google-cloud-clients/google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  google-cloud-clients/google-cloud-kms/synth.metadata
Labels: cla: yes

#6070 Fix links to googleapis.dev from GitHub pages
  README.md
  google-api-grpc/pom.xml
  google-cloud-clients/google-cloud-asset/README.md
  google-cloud-clients/google-cloud-automl/README.md
  google-cloud-clients/google-cloud-bigquery/README.md
  google-cloud-clients/google-cloud-bigquerydatatransfer/README.md
  google-cloud-clients/google-cloud-bigquerystorage/README.md
  google-cloud-clients/google-cloud-bigtable/README.md
  google-cloud-clients/google-cloud-compute/README.md
  google-cloud-clients/google-cloud-container/README.md
  google-cloud-clients/google-cloud-containeranalysis/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/README.md
  google-cloud-clients/google-cloud-core/README.md
  google-cloud-clients/google-cloud-datacatalog/README.md
  google-cloud-clients/google-cloud-datalabeling/README.md
  google-cloud-clients/google-cloud-dataproc/README.md
  google-cloud-clients/google-cloud-datastore/README.md
  google-cloud-clients/google-cloud-dialogflow/README.md
  google-cloud-clients/google-cloud-dlp/README.md
  google-cloud-clients/google-cloud-dns/README.md
  google-cloud-clients/google-cloud-errorreporting/README.md
  google-cloud-clients/google-cloud-firestore/README.md
  google-cloud-clients/google-cloud-gameservices/README.md
  google-cloud-clients/google-cloud-iamcredentials/README.md
  google-cloud-clients/google-cloud-iot/README.md
  google-cloud-clients/google-cloud-kms/README.md
  google-cloud-clients/google-cloud-language/README.md
  google-cloud-clients/google-cloud-logging/README.md
  google-cloud-clients/google-cloud-monitoring/README.md
  google-cloud-clients/google-cloud-os-login/README.md
  google-cloud-clients/google-cloud-phishingprotection/README.md
  google-cloud-clients/google-cloud-pubsub/README.md
  google-cloud-clients/google-cloud-recaptchaenterprise/README.md
  google-cloud-clients/google-cloud-redis/README.md
  google-cloud-clients/google-cloud-resourcemanager/README.md
  google-cloud-clients/google-cloud-scheduler/README.md
  google-cloud-clients/google-cloud-securitycenter/README.md
  google-cloud-clients/google-cloud-spanner/README.md
  google-cloud-clients/google-cloud-speech/README.md
  google-cloud-clients/google-cloud-storage/README.md
  google-cloud-clients/google-cloud-talent/README.md
  google-cloud-clients/google-cloud-tasks/README.md
  google-cloud-clients/google-cloud-texttospeech/README.md
  google-cloud-clients/google-cloud-trace/README.md
  google-cloud-clients/google-cloud-translate/README.md
  google-cloud-clients/google-cloud-video-intelligence/README.md
  google-cloud-clients/google-cloud-vision/README.md
  google-cloud-clients/google-cloud-webrisk/README.md
  google-cloud-clients/google-cloud-websecurityscanner/README.md
  google-cloud-clients/pom.xml
  google-cloud-examples/README.md
  google-cloud-testing/google-cloud-bigtable-emulator/pom.xml
  utilities/templates/README.md.tmpl
Labels: cla: yes, type: docs

#5789 Storage-nio: Only com.google.cloud.storage.** should be excluded from shading
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/pom.xml
Labels: cla: yes

#6071 Dataproc: release as beta
  README.md
  versions.txt
Labels: cla: yes

#6076 Fix performance regression on Cloud Pub/Sub publish
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#5284 Storage: HMAC service account support
  .kokoro/continuous/storage-it.cfg
  .kokoro/nightly/storage-it.cfg
  .kokoro/presubmit/storage-it.cfg
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/HmacKey.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#6094 spanner-jdbc: Fix flaky timeouts in tests
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/StatementTimeoutTest.java
Labels: cla: yes

#6095 spanner-jdbc: Do not close TransactionManager twice
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/SingleUseTransaction.java
Labels: cla: yes

#6093 Regenerate vision client
  google-api-grpc/grpc-google-cloud-vision-v1p4beta1/src/main/java/com/google/cloud/vision/v1p4beta1/ImageAnnotatorGrpc.java
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/src/main/proto/google/cloud/vision/v1p4beta1/image_annotator.proto
  google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/ImageAnnotatorClient.java
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#6090 Regenerate automl client
  google-api-grpc/grpc-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictionServiceGrpc.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/BatchPredictRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/BatchPredictResult.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DataItems.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Document.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DocumentDimensions.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DocumentDimensionsOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DocumentOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/InputConfig.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictRequest.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictResponse.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictionServiceProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextSnippet.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextSnippetOrBuilder.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/data_items.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/io.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/prediction_service.proto
  google-cloud-clients/google-cloud-automl/synth.metadata
Labels: cla: yes

#6038 Update protobuf to 3.9.1
  google-cloud-clients/pom.xml
Labels: cla: yes

#6091 Regenerate dialogflow client
  google-api-grpc/grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SessionEntityTypesGrpc.java
  google-api-grpc/grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionEntityTypesGrpc.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/session_entity_type.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ContextProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/EntityTypeProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/IntentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionEntityTypeProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/agent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/context.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/entity_type.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/intent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/session.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/session_entity_type.proto
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/SessionEntityTypesClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/package-info.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionEntityTypesClient.java
  google-cloud-clients/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/package-info.java
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#6096 spanner-tests: Sleep uninterruptedly to prevent test failures
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
Labels: cla: yes

#6098 spanner-jdbc: Use random data for tests
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_InsertTestData.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestAutocommitDmlMode.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestAutocommitReadOnly.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestGetCommitTimestamp.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestGetReadTimestamp.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestStatementTimeout.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestTemporaryTransactions.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestTransactionMode.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestTransactionMode_ReadOnly.sql
Labels: cla: yes

#6033 spanner-jdbc: Add jdbc statement integration tests
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ITAbstractJdbcTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPreparedStatementTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSimpleStatementsTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/it/Albums.txt
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/it/Concerts.txt
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/it/CreateMusicTables.sql
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/it/Singers.txt
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/it/Songs.txt
Labels: cla: yes

#6102 Regenerate talent client
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/CommonProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Job.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobResourceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobServiceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/LocationFilter.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/LocationFilterOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileQuery.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileQueryOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/SearchProfilesRequest.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/SearchProfilesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Visibility.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/common.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/filters.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/job.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/job_service.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/profile_service.proto
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#6105 Update Spanner JDBC README
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/README.md
Labels: cla: yes

#6067 connecting to Bigtable emulator using environment variable
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettings.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/env/EmulatorEnv.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/env/TestEnvRule.java
Labels: cla: yes

#6108 Remove duplicate program element in POM
  google-cloud-examples/pom.xml
Labels: cla: yes

#6110 Regenerate talent client
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/JobServiceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/job_service.proto
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#6111 Spanner: Remove SQL logging from integration test runs
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/AbstractSqlScriptVerifier.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ClientSideStatementsTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplGeneratedSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionGeneratedSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcTimeoutSqlTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SetReadOnlyStalenessSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SetStatementTimeoutSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITDdlTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcDdlTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadOnlyTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadWriteAutocommitTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITReadOnlySpannerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITReadWriteAutocommitSpannerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITTransactionModeTest.java
Labels: cla: yes

#6034 spanner-jdbc: Add music sql script based integration tests
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ITAbstractJdbcTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ITAbstractSpannerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSqlMusicScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITSqlMusicScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITTransactionRetryTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/resources/com/google/cloud/spanner/jdbc/ITSqlMusicScriptTest.sql
Labels: cla: yes

#6109 Pub/Sub: subscriber async pull example update
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/SubscriberSnippets.java
Labels: cla: yes

#6104 Logback: Fix loggerName in log entry.
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
Labels: cla: yes

#6116 Fix build
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSqlMusicScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITSqlMusicScriptTest.java
Labels: cla: yes

#6100 docs: update Pub/Sub publisher docstring example
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#6115 Update core dependencies
  google-api-grpc/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/OpenCensusUtilTest.java
  google-cloud-clients/pom.xml
  google-cloud-testing/google-cloud-conformance-tests/pom.xml
  google-cloud-testing/pom.xml
  google-cloud-util/google-cloud-compat-checker/pom.xml
Labels: cla: yes

#6128 Regenerate dialogflow client
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/StreamingDetectIntentRequest.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/session.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/StreamingDetectIntentRequest.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/session.proto
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#6136 Update google-auth-library to 0.17.1
  google-cloud-clients/pom.xml
Labels: cla: yes

#6138 chore: Regenerate conformance-tests with protoc 3.9.1
  google-cloud-testing/google-cloud-conformance-tests/generate-conformance-tests.sh
  google-cloud-testing/google-cloud-conformance-tests/src/main/java/com/google/cloud/conformance/bigtable/v2/TestDefinition.java
  google-cloud-testing/google-cloud-conformance-tests/src/main/java/com/google/cloud/conformance/firestore/v1/TestDefinition.java
  google-cloud-testing/google-cloud-conformance-tests/src/main/java/com/google/cloud/conformance/storage/v1/SigningV4Test.java
  google-cloud-testing/google-cloud-conformance-tests/src/main/java/com/google/cloud/conformance/storage/v1/TestFile.java
  google-cloud-testing/google-cloud-conformance-tests/src/main/java/com/google/cloud/conformance/storage/v1/Tests.java
Labels: cla: yes

#6118 Spanner: Unflake partitioned dml test case
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Labels: cla: yes

#6146 Regenerate spanner client
  google-api-grpc/grpc-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerGrpc.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/BatchCreateSessionsRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/BatchCreateSessionsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/BatchCreateSessionsResponse.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/BatchCreateSessionsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponse.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteSqlRequest.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteSqlRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerProto.java
  google-api-grpc/proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/spanner.proto
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/GrpcSpannerStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/MockSpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/SpannerClientTest.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#6085 Expose Object serialization for internal consumers
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Internal.java
Labels: cla: yes

#6142 Bigtable: minor cleanups
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
Labels: api: bigtable, cla: yes

#6159 spanner-jdbc: Unflake ITTransactionRetryTest
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/it/ITTransactionRetryTest.java
Labels: cla: yes

#6158 spanner-jdbc: Add tests for JdbcStatement
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTest.java
Labels: cla: yes

#6155 Spanner: Increase timeouts to prevent test flakiness
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
Labels: cla: yes

#6152 Spanner: Re-enable test depending on gax 1.47
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
Labels: cla: yes

#5703 Spanner: Add trace+timeout for waiting for sessions
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Labels: cla: yes

#6156 spanner-jdbc: Add tests for AbstractJdbcResultSet
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcResultSet.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/AbstractJdbcResultSetTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java
Labels: cla: yes

#6153 spanner-jdbc: Add tests for setting invalid parameter values
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java
Labels: cla: yes

#6154 spanner-jdbc: Add additional tests for JdbcDatabaseMetaData
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java
Labels: cla: yes

#6157 spanner-jdbc: Add tests for JdbcConnection
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java
Labels: cla: yes

#6163 Spanner: Simplify and unflake SpannerGaxRetryTest
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
Labels: cla: yes

#6145 spanner-jdbc: Use NoCredentials for tests
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionOptions.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplGeneratedSqlScriptTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/SetStatementTimeoutSqlScriptTest.java
Labels: cla: yes

#6151 Spanner: Print stack trace in case of test case flake
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: cla: yes

#6176 Spanner: Remove tracing implementation from tests
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Labels: cla: yes

#6165 Spanner: Fix potential session leak when BeginTransaction would throw an error
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolLeakTest.java
Labels: cla: yes

#6184 Unflake SpannerGaxRetryTest
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
Labels: cla: yes

#6178 Spanner: Session pool should return sessions in LIFO order
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Labels: cla: yes

#6191 Fix BucketPolicyOnly StorageIT test
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#6190 Change submodule to use https style of URL.
  .gitmodules
Labels: cla: yes

#6175 spanner-jdbc: Fix possible IllegalArgumentException in SingleUseTransaction
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/SingleUseTransaction.java
Labels: cla: yes

#6197 Translate: fix sample output
  google-cloud-examples/src/main/java/com/google/cloud/examples/translate/snippets/TranslateSnippetsBeta.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/translate/snippets/ITTranslateSnippetsBeta.java
Labels: cla: yes

#6193 Bigtable: Added deleteForcedAppProfile InstanceAdmin operation
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTest.java
Labels: cla: yes

#6186 Bigtable: Adding Integration Test of BigtableInstanceAdminClient
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/DirectPathEnv.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/EmulatorEnv.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/ProdEnv.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java
Labels: api: bigtable, cla: yes
