Repository googleapis/google-cloud-java, pull requests merged in 2019-11, with the labels that each got.

#6677 chore: stop release for dialogflow
  google-api-grpc/grpc-google-cloud-dialogflow-v2/pom.xml
  google-api-grpc/grpc-google-cloud-dialogflow-v2beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-dialogflow-v2/pom.xml
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-dialogflow/.repo-metadata.json
  google-cloud-clients/google-cloud-dialogflow/README.md
  google-cloud-clients/google-cloud-dialogflow/pom.xml
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
  google-cloud-clients/google-cloud-dialogflow/synth.py
  versions.txt
Labels: cla: yes

#6678 Allow custom FirestoreRPC in Internal
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Internal.java
Labels: cla: yes

#6676 chore: stop release for dataproc
  google-api-grpc/grpc-google-cloud-dataproc-v1/pom.xml
  google-api-grpc/grpc-google-cloud-dataproc-v1beta2/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-dataproc-v1/pom.xml
  google-api-grpc/proto-google-cloud-dataproc-v1beta2/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-dataproc/.repo-metadata.json
  google-cloud-clients/google-cloud-dataproc/README.md
  google-cloud-clients/google-cloud-dataproc/pom.xml
  google-cloud-clients/google-cloud-dataproc/synth.metadata
  google-cloud-clients/google-cloud-dataproc/synth.py
  versions.txt
Labels: cla: yes

#6669 chore: stop release for dns
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-dns/.repo-metadata.json
  google-cloud-clients/google-cloud-dns/README.md
  google-cloud-clients/google-cloud-dns/pom.xml
  versions.txt
Labels: cla: yes

#6681 chore: stop release for container
  google-api-grpc/grpc-google-cloud-container-v1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-container-v1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-container/.repo-metadata.json
  google-cloud-clients/google-cloud-container/README.md
  google-cloud-clients/google-cloud-container/pom.xml
  google-cloud-clients/google-cloud-container/synth.metadata
  google-cloud-clients/google-cloud-container/synth.py
  versions.txt
Labels: cla: yes

#6683 chore: stop release for compute
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-compute/.repo-metadata.json
  google-cloud-clients/google-cloud-compute/README.md
  google-cloud-clients/google-cloud-compute/pom.xml
  google-cloud-clients/google-cloud-compute/synth.metadata
  google-cloud-clients/google-cloud-compute/synth.py
  versions.txt
Labels: cla: yes

#6672 chore: stop release for errorreporting
  google-api-grpc/grpc-google-cloud-error-reporting-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-error-reporting-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-errorreporting/.repo-metadata.json
  google-cloud-clients/google-cloud-errorreporting/README.md
  google-cloud-clients/google-cloud-errorreporting/pom.xml
  google-cloud-clients/google-cloud-errorreporting/synth.metadata
  google-cloud-clients/google-cloud-errorreporting/synth.py
  versions.txt
Labels: cla: yes

#6682 chore: stop release for containeranalysis
  google-api-grpc/grpc-google-cloud-containeranalysis-v1/pom.xml
  google-api-grpc/grpc-google-cloud-containeranalysis-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-containeranalysis-v1/pom.xml
  google-api-grpc/proto-google-cloud-containeranalysis-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-containeranalysis/.repo-metadata.json
  google-cloud-clients/google-cloud-containeranalysis/README.md
  google-cloud-clients/google-cloud-containeranalysis/pom.xml
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
  google-cloud-clients/google-cloud-containeranalysis/synth.py
  versions.txt
Labels: cla: yes

#5899 [Storage] Add support for UniformBucketLevelAccess
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: api: storage, cla: yes, do not merge, needs work, type: feature request

#6521 Bigquery: Fix bug QueryParameterValue.timestamp(long) conversion causes loss of microsecond precision.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
Labels: cla: yes

#6552 Bigquery: add range partitioning to tables, load jobs, and query jobs.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/RangePartitioning.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: api: bigquery, cla: yes, type: feature request

#6702 Storage : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-storage/README.md
Labels: cla: yes

#6699 Bigquery Data Transfer : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-bigquerydatatransfer/README.md
Labels: cla: yes

#6700 BigqueryStorage : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-bigquerystorage/README.md
Labels: cla: yes

#6701 Bigtable : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-bigtable/README.md
Labels: cla: yes

#6707 Storage : Fix bom version in doc
  google-cloud-clients/google-cloud-storage/README.md
Labels: cla: yes

#6706 BigQuery: implement scripting support.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#6238 Make sure that background resources are closed when the PubSub subscriber fails
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
Labels: cla: yes

#6390 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#6715 Datastore : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-datastore/README.md
Labels: cla: yes

#6716 Firestore : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-firestore/README.md
Labels: cla: yes

#6717 update http-client to 1.33.0, datastore-v1-proto-client to 1.6.3
  google-cloud-clients/pom.xml
Labels: cla: yes

#6733 Pubsub : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-pubsub/README.md
Labels: cla: yes

#6732 Os-Login : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-os-login/README.md
Labels: cla: yes

#6731 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#6735 Bigquerystorage : Fix bom version in doc
  google-cloud-clients/google-cloud-bigquerystorage/README.md
Labels: cla: yes

#6760 Logging - Logback : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/README.md
Labels: cla: yes

#6756 Securitycenter: reference libraries-bom in docs
  google-cloud-clients/google-cloud-securitycenter/README.md
Labels: cla: yes

#6758 Spanner : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-spanner/README.md
Labels: cla: yes

#6759 Nio : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/README.md
Labels: cla: yes

#6698 Bigquery : Reference libraries-bom in docs
  google-cloud-clients/google-cloud-bigquery/README.md
Labels: cla: yes

#6761 Bigquery: add Description field for Routine entities.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Routine.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/RoutineInfo.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineInfoTest.java
Labels: cla: yes

#6430 fix(logging): add ability to filter MDC labels
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java
Labels: cla: yes

#6762 Spanner: Remove dependency on GCS
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/CredentialsService.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/CredentialsServiceTest.java
Labels: cla: yes

#6788 Storage : Updating docstring of withHostName
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
Labels: cla: yes

#6789 Spanner: Session pool should not retry BeginTransaction if database has been deleted
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
Labels: cla: yes

#6746 Fix projectName parsing in GapicSpannerRpc
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Labels: cla: yes

#6792 Update versions
  TROUBLESHOOTING.md
Labels: cla: yes

#6791 Spanner: Fix session leak on allowNestedTransaction
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Labels: api: spanner, cla: yes

#6820 gRPC 1.25.0
  google-cloud-clients/pom.xml
Labels: cla: yes, semver: patch

#6815 Regenerate bigquerydatatransfer client
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/test/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClientTest.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
Labels: cla: yes

#6819 Regenerate grafeas client
  google-cloud-clients/grafeas/src/test/java/io/grafeas/v1/GrafeasClientTest.java
  google-cloud-clients/grafeas/synth.metadata
Labels: cla: yes

#6817 Regenerate firestore client
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/FirestoreAdminClientTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1/FirestoreClientTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/v1beta1/FirestoreClientTest.java
  google-cloud-clients/google-cloud-firestore/synth.metadata
Labels: cla: yes

#6816 Regenerate bigquerystorage client
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClientTest.java
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
Labels: cla: yes

#6129 Regenerate pubsub client
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeadLetterPolicy.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeadLetterPolicyOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PullRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PullRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriptionOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#6793 BOM 2.9.0
  README.md
Labels: cla: yes

#6796 Update README.md to 0.116.0
  google-cloud-clients/google-cloud-websecurityscanner/README.md
Labels: cla: yes

#6799 update libraries-bom to 2.9.0
  google-cloud-clients/google-cloud-bigquery/README.md
  google-cloud-clients/google-cloud-bigquerystorage/README.md
  google-cloud-clients/google-cloud-bigtable/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/README.md
  google-cloud-clients/google-cloud-datastore/README.md
  google-cloud-clients/google-cloud-firestore/README.md
  google-cloud-clients/google-cloud-os-login/README.md
  google-cloud-clients/google-cloud-pubsub/README.md
  google-cloud-clients/google-cloud-securitycenter/README.md
  google-cloud-clients/google-cloud-spanner/README.md
  google-cloud-clients/google-cloud-storage/README.md
Labels: cla: yes

#6859 Storage: Allow null values in labels map
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#6856 Add toString() method to LifecycleRule
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
Labels: cla: yes

#6861 Prepare Pub/Sub for extraction
  google-api-grpc/grpc-google-cloud-pubsub-v1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-pubsub-v1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-pubsub/README.md
  google-cloud-clients/google-cloud-pubsub/pom.xml
  google-cloud-clients/google-cloud-pubsub/synth.metadata
  google-cloud-clients/google-cloud-pubsub/synth.py
  versions.txt
Labels: cla: yes

#6843 Firestore: Allow passing POJOs as field values throughout API reference from Firebase
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentSnapshot.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/WriteBatchTest.java
Labels: cla: yes

#6794 Fix versions
  google-cloud-clients/google-cloud-bigtable/README.md
Labels: cla: yes

#6736 Bigquerystorage: fix missing dependency.
  google-cloud-bom/pom.xml
Labels: cla: yes

#6896 chore: remove utilities that are unnecessary with the split repo
  utilities/README.md
  utilities/add_snippets_to_file.py
  utilities/new_client.py
  utilities/requirements.txt
  utilities/snippets.go
  utilities/snippets_test.go
  utilities/stage_sites.py
  utilities/templates/README.md.tmpl
  utilities/templates/cloud_pom.xml
  utilities/templates/grpc_pom.xml
  utilities/templates/proto_pom.xml
  utilities/templates/synth.py
  utilities/verify_single_it.sh
Labels: cla: yes

#6842 Datastore: expose serializedSize for Entity.
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/Entity.java
  google-cloud-clients/google-cloud-datastore/src/test/java/com/google/cloud/datastore/EntityTest.java
Labels: cla: yes

#6895 chore: remove dependency management for removed clients
  google-api-grpc/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#6901 Fix new README for translate
  google-cloud-clients/google-cloud-translate/README.md
Labels: cla: yes

#6903 deps: google-cloud-clients should not import google-cloud-bom
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-bigquery/pom.xml
  google-cloud-clients/google-cloud-bigquerydatatransfer/pom.xml
  google-cloud-clients/google-cloud-bigquerystorage/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/pom.xml
  google-cloud-clients/google-cloud-datastore/pom.xml
  google-cloud-clients/google-cloud-pubsub/pom.xml
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/google-cloud-storage/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#6926 Extract BOM to https://github.com/googleapis/java-cloud-bom
  google-cloud-bom/README.md
  google-cloud-bom/pom.xml
  google-cloud-bom/src/site/site.xml
  google-cloud-examples/pom.xml
  google-cloud-testing/pom.xml
  pom.xml
  versions.txt
Labels: cla: yes
