Repository googleapis/google-cloud-java, pull requests merged in 2019-10, with the labels that each got.

#6325 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/SpannerClientTest.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#6379 fix: bump grpc-google-iam to 0.13.0 to introduce GetPolicyOptions
  google-api-grpc/pom.xml
  google-cloud-bom/pom.xml
Labels: cla: yes

#6394 update only GAX
  google-cloud-clients/pom.xml
Labels: cla: yes

#6388 Regenerate language client
  google-api-grpc/grpc-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/LanguageServiceGrpc.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitiesRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitiesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitiesResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitiesResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitySentimentRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitySentimentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitySentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeEntitySentimentResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSentimentRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSentimentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSentimentResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSentimentResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSyntaxRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSyntaxRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSyntaxResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnalyzeSyntaxResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnnotateTextRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnnotateTextRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnnotateTextResponse.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/AnnotateTextResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/ClassificationCategory.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/ClassificationCategoryOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/ClassifyTextRequest.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/ClassifyTextRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Document.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/DocumentOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/EncodingType.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Entity.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/EntityMention.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/EntityMentionOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/EntityOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/LanguageServiceProto.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Sentence.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/SentenceOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/Sentiment.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/TextSpan.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/v1beta2/TextSpanOrBuilder.java
  google-api-grpc/proto-google-cloud-language-v1beta2/src/main/proto/google/cloud/language/v1beta2/language_service.proto
  google-cloud-clients/google-cloud-language/src/main/java/com/google/cloud/language/v1beta2/LanguageServiceClient.java
  google-cloud-clients/google-cloud-language/synth.metadata
Labels: cla: yes

#6183 Add virtual hosted-style support for signurl gen.
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/SignatureInfo.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#6359 Regenerate phishingprotection client
  google-api-grpc/grpc-google-cloud-phishingprotection-v1beta1/src/main/java/com/google/phishingprotection/v1beta1/PhishingProtectionServiceV1Beta1Grpc.java
  google-api-grpc/proto-google-cloud-phishingprotection-v1beta1/src/main/java/com/google/phishingprotection/v1beta1/PhishingProtectionProto.java
  google-api-grpc/proto-google-cloud-phishingprotection-v1beta1/src/main/java/com/google/phishingprotection/v1beta1/ReportPhishingRequest.java
  google-api-grpc/proto-google-cloud-phishingprotection-v1beta1/src/main/java/com/google/phishingprotection/v1beta1/ReportPhishingRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-phishingprotection-v1beta1/src/main/proto/google/cloud/phishingprotection/v1beta1/phishingprotection.proto
  google-cloud-clients/google-cloud-phishingprotection/src/main/java/com/google/cloud/phishingprotection/v1beta1/PhishingProtectionServiceV1Beta1Client.java
  google-cloud-clients/google-cloud-phishingprotection/synth.metadata
Labels: cla: yes

#6341 Regenerate talent client
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/AvailabilityFilter.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/AvailabilityFilterOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/AvailabilitySignal.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/AvailabilitySignalOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/AvailabilitySignalType.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/CandidateAvailabilityFilter.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/CandidateAvailabilityFilterOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/CommonProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/FiltersProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/Profile.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileQuery.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileQueryOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/ProfileResourceProto.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/UpdateProfileRequest.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/UpdateProfileRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/common.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/filters.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/profile.proto
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/profile_service.proto
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#6363 Regenerate bigquerydatatransfer client
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CheckValidCredsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CheckValidCredsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CreateTransferConfigRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CreateTransferConfigRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSource.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferProto.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DeleteTransferConfigRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DeleteTransferConfigRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DeleteTransferRunRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DeleteTransferRunRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetDataSourceRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetDataSourceRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetTransferConfigRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetTransferConfigRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetTransferRunRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetTransferRunRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListDataSourcesRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListDataSourcesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListDataSourcesResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListDataSourcesResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferConfigsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferConfigsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferConfigsResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferConfigsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferLogsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferLogsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferLogsResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferLogsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferRunsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferRunsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferRunsResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferRunsResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ScheduleTransferRunsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ScheduleTransferRunsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/StartManualTransferRunsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/StartManualTransferRunsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferConfig.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferProto.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferRun.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferRunOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/UpdateTransferConfigRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/UpdateTransferConfigRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/proto/google/cloud/bigquery/datatransfer/v1/datatransfer.proto
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/proto/google/cloud/bigquery/datatransfer/v1/transfer.proto
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClient.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
Labels: cla: yes

#6343 Dns: Fix CAA record support.
  google-cloud-clients/google-cloud-dns/src/main/java/com/google/cloud/dns/RecordSet.java
  google-cloud-clients/google-cloud-dns/src/test/java/com/google/cloud/dns/RecordSetTest.java
  google-cloud-clients/google-cloud-dns/src/test/java/com/google/cloud/dns/it/ITDnsTest.java
Labels: cla: yes

#6391 Regenerate websecurityscanner client
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/CrawledUrl.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/CrawledUrlOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/CrawledUrlProto.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/CreateScanConfigRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/CreateScanConfigRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/DeleteScanConfigRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/DeleteScanConfigRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/Finding.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/FindingAddonProto.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/FindingOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/FindingProto.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/FindingTypeStats.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/FindingTypeStatsOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/FindingTypeStatsProto.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetFindingRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetFindingRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetScanConfigRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetScanConfigRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetScanRunRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetScanRunRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListCrawledUrlsRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListCrawledUrlsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingTypeStatsRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingTypeStatsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingsRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanConfigsRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanConfigsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanRunsRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanRunsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanConfig.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanConfigProto.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanRun.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanRunOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanRunProto.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/StartScanRunRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/StartScanRunRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/StopScanRunRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/StopScanRunRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/UpdateScanConfigRequest.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/UpdateScanConfigRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/VulnerableHeaders.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/VulnerableHeadersOrBuilder.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerProto.java
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/crawled_url.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/finding.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/finding_addon.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/finding_type_stats.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/scan_config.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/scan_run.proto
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/src/main/proto/google/cloud/websecurityscanner/v1alpha/web_security_scanner.proto
  google-cloud-clients/google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerClient.java
  google-cloud-clients/google-cloud-websecurityscanner/synth.metadata
Labels: cla: yes

#6367 Bigquery: Expose labels for CopyJobConfiguration.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/CopyJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/CopyJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#6376 Bigquery: Expose labels for ExtractJobConfiguration.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExtractJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExtractJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#6387 Bigquery: Expose labels for LoadJobConfiguration.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#6331 Spanner: Close ResultSet from session keep-alive request
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
Labels: cla: yes

#6400 More dependency updates
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#6412 Regenerate recaptchaenterprise client
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/AnnotateAssessmentRequest.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/AnnotateAssessmentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/Assessment.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/AssessmentOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/CreateAssessmentRequest.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/CreateAssessmentRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/Event.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/EventOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/RecaptchaEnterpriseProto.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/TokenProperties.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/java/com/google/recaptchaenterprise/v1beta1/TokenPropertiesOrBuilder.java
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/src/main/proto/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise.proto
  google-cloud-clients/google-cloud-recaptchaenterprise/src/main/java/com/google/cloud/recaptchaenterprise/v1beta1/RecaptchaEnterpriseServiceV1Beta1Client.java
  google-cloud-clients/google-cloud-recaptchaenterprise/src/test/java/com/google/cloud/recaptchaenterprise/v1beta1/RecaptchaEnterpriseServiceV1Beta1ClientTest.java
  google-cloud-clients/google-cloud-recaptchaenterprise/synth.metadata
Labels: cla: yes

#6408 Regenerate bigquerystorage client
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/Storage.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/TableReferenceProto.java
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/storage.proto
  google-api-grpc/proto-google-cloud-bigquerystorage-v1beta1/src/main/proto/google/cloud/bigquery/storage/v1beta1/table_reference.proto
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClient.java
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/BigQueryStorageStubSettings.java
  google-cloud-clients/google-cloud-bigquerystorage/synth.metadata
Labels: cla: yes

#6399 Recommend linkage checker enforcer rule instead of dependency convergence
  TROUBLESHOOTING.md
Labels: cla: yes

#6409 Regenerate firestore client
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/Field.java
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/FirestoreAdminProto.java
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/Index.java
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/IndexOrBuilder.java
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/IndexProto.java
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/proto/google/firestore/admin/v1/field.proto
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/proto/google/firestore/admin/v1/firestore_admin.proto
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/proto/google/firestore/admin/v1/index.proto
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/proto/google/firestore/admin/v1/location.proto
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/proto/google/firestore/admin/v1/operation.proto
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/FirestoreProto.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/QueryProto.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/StructuredQuery.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/Target.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/TargetChange.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/TargetChangeOrBuilder.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/TargetOrBuilder.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/common.proto
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/document.proto
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/firestore.proto
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/query.proto
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/write.proto
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/FirestoreProto.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/QueryProto.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/StructuredQuery.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/Target.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/TargetChange.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/TargetChangeOrBuilder.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/TargetOrBuilder.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/proto/google/firestore/v1beta1/common.proto
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/proto/google/firestore/v1beta1/document.proto
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/proto/google/firestore/v1beta1/firestore.proto
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/proto/google/firestore/v1beta1/query.proto
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/proto/google/firestore/v1beta1/write.proto
  google-cloud-clients/google-cloud-firestore/synth.metadata
Labels: cla: yes

#6418 Skip translate deployment from this repo
  google-api-grpc/grpc-google-cloud-translate-v3beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-translate-v3beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-translate/pom.xml
  versions.txt
Labels: cla: yes

#6360 Datastore : add GqlQuery#setBinding method which accept null value
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/GqlQuery.java
  google-cloud-clients/google-cloud-datastore/src/test/java/com/google/cloud/datastore/DatastoreTest.java
  google-cloud-clients/google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITDatastoreTest.java
Labels: cla: yes

#6433 Fix translate release skipping
  google-api-grpc/grpc-google-cloud-translate-v3beta1/pom.xml
  google-api-grpc/proto-google-cloud-translate-v3beta1/pom.xml
  google-cloud-clients/google-cloud-translate/pom.xml
Labels: cla: yes

#6436 Prepare asset client for extraction
  google-api-grpc/grpc-google-cloud-asset-v1/pom.xml
  google-api-grpc/grpc-google-cloud-asset-v1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-asset-v1p2beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-asset-v1/pom.xml
  google-api-grpc/proto-google-cloud-asset-v1beta1/pom.xml
  google-api-grpc/proto-google-cloud-asset-v1p2beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-asset/README.md
  google-cloud-clients/google-cloud-asset/pom.xml
  google-cloud-clients/google-cloud-asset/synth.metadata
  google-cloud-clients/google-cloud-asset/synth.py
  versions.txt
Labels: cla: yes

#6448 Update google-cloud-core to 1.91.2
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#6424 Regenerate tasks client
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/java/com/google/cloud/tasks/v2/CloudTasksProto.java
  google-api-grpc/proto-google-cloud-tasks-v2/src/main/proto/google/cloud/tasks/v2/cloudtasks.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/CloudTasksProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta2/src/main/proto/google/cloud/tasks/v2beta2/cloudtasks.proto
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/CloudTasksProto.java
  google-api-grpc/proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/cloudtasks.proto
  google-cloud-clients/google-cloud-tasks/synth.metadata
Labels: cla: yes

#6450 ignore Eclipse metadata
  .gitignore
Labels: cla: yes, semver: patch, type: cleanup

#6438 Spanner: Add tests for translating to SessionNotFoundException
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerExceptionFactoryTest.java
Labels: cla: yes

#6458 fix a few warnings
  google-cloud-clients/google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITDatastoreTest.java
Labels: cla: yes, semver: patch, type: cleanup

#6328 Updated JavaDoc to mention connection pooling over ManagedChannel
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
Labels: api: bigtable, cla: yes

#6201 Bigtable: Updated Javadoc of models/CreateInstanceRequest.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateInstanceRequest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequestTest.java
Labels: api: bigtable, cla: yes

#6432 [Bigtable] Overload MutationApi#setCell to accept long values
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Mutation.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/MutationApi.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowMutation.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowMutationEntry.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/MutateRowIT.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/ReadModifyWriteIT.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/MutationTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/RowMutationEntryTest.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/RowMutationTest.java
Labels: api: bigtable, cla: yes

#6461 reclassify GrafeasInteropTest as an integration test
  google-cloud-clients/google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1/ITGrafeasInteropTest.java
Labels: cla: yes

#6375 Redis: Added system test
  .kokoro/continuous/redis-it.cfg
  .kokoro/nightly/redis-it.cfg
  .kokoro/presubmit/redis-it.cfg
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/it/ITSystemTest.java
Labels: cla: yes

#6467 Regenerate webrisk client
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ComputeThreatListDiffRequest.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ComputeThreatListDiffRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ComputeThreatListDiffResponse.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/ComputeThreatListDiffResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchHashesRequest.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchHashesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchUrisRequest.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/SearchUrisRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/java/com/google/webrisk/v1beta1/WebRiskProto.java
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/src/main/proto/google/cloud/webrisk/v1beta1/webrisk.proto
  google-cloud-clients/google-cloud-webrisk/src/main/java/com/google/cloud/webrisk/v1beta1/WebRiskServiceV1Beta1Client.java
  google-cloud-clients/google-cloud-webrisk/synth.metadata
Labels: cla: yes

#6455 Regenerate redis client
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisClient.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/CloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/CloudRedisStubSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/GrpcCloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisClient.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/CloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
  google-cloud-clients/google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/GrpcCloudRedisStub.java
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1/CloudRedisClientTest.java
  google-cloud-clients/google-cloud-redis/src/test/java/com/google/cloud/redis/v1beta1/CloudRedisClientTest.java
  google-cloud-clients/google-cloud-redis/synth.metadata
Labels: cla: yes

#6465 Regenerate os-login client
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/common/OsLoginProto.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/DeletePosixAccountRequest.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/DeletePosixAccountRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/DeleteSshPublicKeyRequest.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/DeleteSshPublicKeyRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/GetLoginProfileRequest.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/GetLoginProfileRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/ImportSshPublicKeyRequest.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/ImportSshPublicKeyRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/LoginProfile.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/LoginProfileOrBuilder.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/OsLoginProto.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/UpdateSshPublicKeyRequest.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/UpdateSshPublicKeyRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/proto/google/cloud/oslogin/common/common.proto
  google-api-grpc/proto-google-cloud-os-login-v1/src/main/proto/google/cloud/oslogin/v1/oslogin.proto
  google-cloud-clients/google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceClient.java
  google-cloud-clients/google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/package-info.java
  google-cloud-clients/google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/GrpcOsLoginServiceCallableFactory.java
  google-cloud-clients/google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/GrpcOsLoginServiceStub.java
  google-cloud-clients/google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStub.java
  google-cloud-clients/google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStubSettings.java
  google-cloud-clients/google-cloud-os-login/src/test/java/com/google/cloud/oslogin/v1/OsLoginServiceClientTest.java
  google-cloud-clients/google-cloud-os-login/synth.metadata
Labels: cla: yes

#6466 Regenerate talent client
  google-api-grpc/proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/filters.proto
  google-cloud-clients/google-cloud-talent/synth.metadata
Labels: cla: yes

#6457 Be more direct about setting up ADC
  CONTRIBUTING.md
Labels: cla: yes

#6463 recommend libraries-bom for troubleshooting
  TROUBLESHOOTING.md
Labels: cla: yes, semver: patch, type: docs

#6472 Refresh VPCSC tests for monitoring V3
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/VPCServiceControlTest.java
Labels: cla: yes

#6452 Extract gcloud-maven-plugin, bigtable-emulator
  google-cloud-bom/pom.xml
  google-cloud-testing/google-cloud-bigtable-emulator/README.md
  google-cloud-testing/google-cloud-bigtable-emulator/pom.xml
  google-cloud-testing/google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/BigtableEmulatorRule.java
  google-cloud-testing/google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/Emulator.java
  google-cloud-testing/google-cloud-bigtable-emulator/src/test/java/com/google/cloud/bigtable/emulator/v2/BigtableEmulatorRuleTest.java
  google-cloud-testing/google-cloud-bigtable-emulator/src/test/java/com/google/cloud/bigtable/emulator/v2/EmulatorTest.java
  google-cloud-testing/google-cloud-gcloud-maven-plugin/README.md
  google-cloud-testing/google-cloud-gcloud-maven-plugin/pom.xml
  google-cloud-testing/google-cloud-gcloud-maven-plugin/src/main/java/com/google/cloud/Component.java
  google-cloud-testing/google-cloud-gcloud-maven-plugin/src/main/java/com/google/cloud/DownloadComponentsMojo.java
  google-cloud-testing/pom.xml
  versions.txt
Labels: cla: yes

#6431 [Bigtable] Updated javaDoc for callable being wrapper around read & write
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
Labels: api: bigtable, cla: yes

#6480 Regenerate vision client
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchParams.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchParamsOrBuilder.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchProto.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchServiceProto.java
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search.proto
  google-api-grpc/proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search_service.proto
  google-cloud-clients/google-cloud-vision/synth.metadata
Labels: cla: yes

#6479 Regenerate firestore client
  google-api-grpc/proto-google-cloud-firestore-admin-v1/src/main/proto/google/firestore/admin/v1/operation.proto
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/QueryProto.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/StructuredQuery.java
  google-api-grpc/proto-google-cloud-firestore-v1/src/main/proto/google/firestore/v1/query.proto
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/QueryProto.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/java/com/google/firestore/v1beta1/StructuredQuery.java
  google-api-grpc/proto-google-cloud-firestore-v1beta1/src/main/proto/google/firestore/v1beta1/query.proto
  google-cloud-clients/google-cloud-firestore/synth.metadata
Labels: cla: yes

#6482 Bigquery: Added jobTimeoutMs field for JobConfiguration.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/CopyJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExtractJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/CopyJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExtractJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
Labels: api: bigquery, cla: yes, type: feature request

#6327 Storage: Fix Bucket logging configuration using library
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
Labels: cla: yes

#6429 Spanner: Change default MinSessions to 100
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/AbortedTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/ITAbstractSpannerTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcAbortedTransactionTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcDriverTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/JdbcGrpcErrorTest.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/BatchClientImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolIntegrationTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
Labels: cla: yes

#6469 Spanner: Add IAM wrapper methods
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Database.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Instance.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceAdminClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminClientImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminClientTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockDatabaseAdminServiceImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockDatabaseAdminServiceImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockInstanceAdminServiceImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockOperationsServiceImpl.java
Labels: cla: yes

#6407 Bigquery: Expose labels for QueryJobConfiguration.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes

#6484 Declare direct dependencies in google-cloud-bigtable pom.xml
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsRetryTest.java
Labels: cla: yes

#6460 Bigtable: Add integration test for DirectPath fallback to and from CFE
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/DirectPathEnv.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/EmulatorEnv.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/ProdEnv.java
Labels: api: bigtable, cla: yes

#6497 Prepare datalabeling client for extraction
  google-api-grpc/grpc-google-cloud-datalabeling-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-datalabeling-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-datalabeling/README.md
  google-cloud-clients/google-cloud-datalabeling/pom.xml
  google-cloud-clients/google-cloud-datalabeling/synth.metadata
  google-cloud-clients/google-cloud-datalabeling/synth.py
  versions.txt
Labels: cla: yes

#6502 Prepare IoT client for extraction
  google-api-grpc/grpc-google-cloud-iot-v1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-iot-v1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-iot/README.md
  google-cloud-clients/google-cloud-iot/pom.xml
  google-cloud-clients/google-cloud-iot/synth.metadata
  google-cloud-clients/google-cloud-iot/synth.py
  versions.txt
Labels: cla: yes

#6498 Prepare DLP client for extraction
  google-api-grpc/grpc-google-cloud-dlp-v2/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-dlp-v2/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-dlp/README.md
  google-cloud-clients/google-cloud-dlp/pom.xml
  google-cloud-clients/google-cloud-dlp/synth.metadata
  google-cloud-clients/google-cloud-dlp/synth.py
  versions.txt
Labels: cla: yes

#6500 Prepare gameservices client for extraction
  google-api-grpc/grpc-google-cloud-gameservices-v1alpha/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-gameservices-v1alpha/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-gameservices/README.md
  google-cloud-clients/google-cloud-gameservices/pom.xml
  google-cloud-clients/google-cloud-gameservices/synth.metadata
  google-cloud-clients/google-cloud-gameservices/synth.py
  versions.txt
Labels: cla: yes

#6486 Prepare datacatalog client for extraction
  google-api-grpc/grpc-google-cloud-datacatalog-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-datacatalog/README.md
  google-cloud-clients/google-cloud-datacatalog/pom.xml
  google-cloud-clients/google-cloud-datacatalog/synth.metadata
  google-cloud-clients/google-cloud-datacatalog/synth.py
  versions.txt
Labels: cla: yes

#6501 Prepare iamcredentials client for extraction
  google-api-grpc/grpc-google-cloud-iamcredentials-v1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-iamcredentials-v1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-iamcredentials/README.md
  google-cloud-clients/google-cloud-iamcredentials/pom.xml
  google-cloud-clients/google-cloud-iamcredentials/synth.metadata
  google-cloud-clients/google-cloud-iamcredentials/synth.py
  versions.txt
Labels: cla: yes

#6514 Prepare vision client for extraction
  google-api-grpc/grpc-google-cloud-vision-v1/pom.xml
  google-api-grpc/grpc-google-cloud-vision-v1p1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-vision-v1p2beta1/pom.xml
  google-api-grpc/grpc-google-cloud-vision-v1p3beta1/pom.xml
  google-api-grpc/grpc-google-cloud-vision-v1p4beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-vision-v1/pom.xml
  google-api-grpc/proto-google-cloud-vision-v1p1beta1/pom.xml
  google-api-grpc/proto-google-cloud-vision-v1p2beta1/pom.xml
  google-api-grpc/proto-google-cloud-vision-v1p3beta1/pom.xml
  google-api-grpc/proto-google-cloud-vision-v1p4beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-vision/README.md
  google-cloud-clients/google-cloud-vision/pom.xml
  google-cloud-clients/google-cloud-vision/synth.metadata
  google-cloud-clients/google-cloud-vision/synth.py
  versions.txt
Labels: cla: yes

#6515 Prepare video-intelligence client for extraction
  google-api-grpc/grpc-google-cloud-video-intelligence-v1/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1beta2/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1p1beta1/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1p2beta1/pom.xml
  google-api-grpc/grpc-google-cloud-video-intelligence-v1p3beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta1/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1beta2/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1p1beta1/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1p2beta1/pom.xml
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-video-intelligence/README.md
  google-cloud-clients/google-cloud-video-intelligence/pom.xml
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
  google-cloud-clients/google-cloud-video-intelligence/synth.py
  versions.txt
Labels: cla: yes

#6512 Prepare websecurityscanner client for extraction
  google-api-grpc/grpc-google-cloud-websecurityscanner-v1alpha/pom.xml
  google-api-grpc/grpc-google-cloud-websecurityscanner-v1beta/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-websecurityscanner-v1alpha/pom.xml
  google-api-grpc/proto-google-cloud-websecurityscanner-v1beta/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-translate/synth.metadata
  google-cloud-clients/google-cloud-translate/synth.py
  google-cloud-clients/google-cloud-websecurityscanner/README.md
  google-cloud-clients/google-cloud-websecurityscanner/pom.xml
  google-cloud-clients/google-cloud-websecurityscanner/synth.metadata
  google-cloud-clients/google-cloud-websecurityscanner/synth.py
  versions.txt
Labels: cla: yes

#6513 Prepare webrisk client for extraction
  google-api-grpc/grpc-google-cloud-webrisk-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-webrisk-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-webrisk/README.md
  google-cloud-clients/google-cloud-webrisk/pom.xml
  google-cloud-clients/google-cloud-webrisk/synth.metadata
  google-cloud-clients/google-cloud-webrisk/synth.py
  versions.txt
Labels: cla: yes

#6522 Skip IoT deployment from the batch deployment
  google-cloud-clients/google-cloud-iot/pom.xml
Labels: cla: yes

#6192 Storage:Fixing the documentation #6099
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
Labels: api: storage, cla: yes

#6445 Bigquery: Fix defaultPartitionExpirationMs for Dataset.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Dataset.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/DatasetInfo.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetInfoTest.java
Labels: cla: yes, semver: minor, type: feature request

#6427 Bigquery: Fix bug for sourceFormat Bigtable ExternalTableDefinition.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableColumn.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableColumnFamily.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
Labels: cla: yes

#6519 Remove some custom settings in BQ storage client.
  google-cloud-clients/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/EnhancedBigQueryStorageStubSettings.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/EnhancedBigQueryStorageStubSettingsTest.java
Labels: cla: yes

#6529 spanner: Increase PDML test timeout
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Labels: cla: yes

#6528 spanner-jdbc: GCS dependency should be scope provided
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/ConnectionOptions.java
Labels: cla: yes

#6539 Prepare Bigtable client for extraction
  google-api-grpc/grpc-google-cloud-bigtable-admin-v2/pom.xml
  google-api-grpc/grpc-google-cloud-bigtable-v2/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-bigtable-admin-v2/pom.xml
  google-api-grpc/proto-google-cloud-bigtable-v2/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/google-cloud-bigtable/synth.metadata
  google-cloud-clients/google-cloud-bigtable/synth.py
  versions.txt
Labels: cla: yes

#6487 Regenerate monitoring client
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/DroppedLabelsProto.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/dropped_labels.proto
  google-cloud-clients/google-cloud-monitoring/synth.metadata
Labels: cla: yes

#6490 Regenerate scheduler client
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/CreateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/CreateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/DeleteJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/DeleteJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/GetJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/GetJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/HttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/HttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/JobProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ListJobsRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ListJobsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/OAuthToken.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/OidcToken.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PauseJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PauseJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PubsubTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PubsubTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ResumeJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ResumeJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/RunJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/RunJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/SchedulerProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/TargetProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/UpdateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/UpdateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/proto/google/cloud/scheduler/v1/cloudscheduler.proto
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/proto/google/cloud/scheduler/v1/job.proto
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/proto/google/cloud/scheduler/v1/target.proto
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/CloudSchedulerClient.java
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#6538 Os-Login : Added ITSystem Test
  google-cloud-clients/google-cloud-os-login/src/test/java/com/google/cloud/oslogin/v1/it/ITSystemTest.java
Labels: cla: yes

#6541 chore: stop release of texttospeech
  google-api-grpc/grpc-google-cloud-texttospeech-v1/pom.xml
  google-api-grpc/grpc-google-cloud-texttospeech-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-texttospeech-v1/pom.xml
  google-api-grpc/proto-google-cloud-texttospeech-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-texttospeech/README.md
  google-cloud-clients/google-cloud-texttospeech/pom.xml
  google-cloud-clients/google-cloud-texttospeech/synth.metadata
  google-cloud-clients/google-cloud-texttospeech/synth.py
  versions.txt
Labels: cla: yes

#6506 Regenerate dataproc client
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/ClustersProto.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/proto/google/cloud/dataproc/v1/clusters.proto
  google-api-grpc/proto-google-cloud-dataproc-v1beta2/src/main/java/com/google/cloud/dataproc/v1beta2/ClustersProto.java
  google-api-grpc/proto-google-cloud-dataproc-v1beta2/src/main/proto/google/cloud/dataproc/v1beta2/clusters.proto
  google-cloud-clients/google-cloud-dataproc/synth.metadata
Labels: cla: yes

#6550 Spanner: Add IT for inserting duplicate row
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Labels: cla: yes

#6549 Regenerate scheduler client
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/SchedulerProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/TopicName.java
  google-api-grpc/proto-google-cloud-scheduler-v1/src/main/proto/google/cloud/scheduler/v1/cloudscheduler.proto
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CreateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CreateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/DeleteJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/DeleteJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/GetJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/GetJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/JobProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/OAuthToken.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/OidcToken.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PauseJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PauseJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PubsubTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PubsubTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ResumeJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ResumeJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RunJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RunJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/SchedulerProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/TargetProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/TopicName.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/UpdateJobRequest.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/UpdateJobRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/cloudscheduler.proto
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/job.proto
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/target.proto
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/CloudSchedulerStubSettings.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClient.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStubSettings.java
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#6547 Regenerate monitoring client
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/Point.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/PointOrBuilder.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/TimeInterval.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/UptimeCheckConfig.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/UptimeCheckConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/UptimeProto.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/common.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/metric.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/uptime.proto
  google-cloud-clients/google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/UptimeCheckServiceClientTest.java
  google-cloud-clients/google-cloud-monitoring/synth.metadata
Labels: cla: yes

#6555 Update gax to 1.49.1
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#6565 chore: stop release of tasks
  google-api-grpc/grpc-google-cloud-tasks-v2/pom.xml
  google-api-grpc/grpc-google-cloud-tasks-v2beta2/pom.xml
  google-api-grpc/grpc-google-cloud-tasks-v2beta3/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-tasks-v2/pom.xml
  google-api-grpc/proto-google-cloud-tasks-v2beta2/pom.xml
  google-api-grpc/proto-google-cloud-tasks-v2beta3/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-tasks/README.md
  google-cloud-clients/google-cloud-tasks/pom.xml
  google-cloud-clients/google-cloud-tasks/synth.metadata
  google-cloud-clients/google-cloud-tasks/synth.py
  versions.txt
Labels: cla: yes

#6553 spanner-jdbc: Support query hints
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/main/java/com/google/cloud/spanner/jdbc/StatementParser.java
  google-cloud-clients/google-cloud-contrib/google-cloud-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/StatementParserTest.java
Labels: cla: yes

#6569 chore: stop release of tasks
  google-api-grpc/grpc-google-cloud-talent-v4beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-talent-v4beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-talent/README.md
  google-cloud-clients/google-cloud-talent/pom.xml
  google-cloud-clients/google-cloud-talent/synth.metadata
  google-cloud-clients/google-cloud-talent/synth.py
  versions.txt
Labels: cla: yes

#6577 chore: stop release for resourcemanager
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-resourcemanager/README.md
  google-cloud-clients/google-cloud-resourcemanager/pom.xml
  versions.txt
Labels: cla: yes

#6604 Remove redundant content
  README.md
Labels: cla: yes

#6603 BOM 2.7.1
  TROUBLESHOOTING.md
Labels: cla: yes

#6580 chore: stop release of redis
  google-api-grpc/grpc-google-cloud-redis-v1/pom.xml
  google-api-grpc/grpc-google-cloud-redis-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-redis-v1/pom.xml
  google-api-grpc/proto-google-cloud-redis-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-redis/.repo-metadata.json
  google-cloud-clients/google-cloud-redis/README.md
  google-cloud-clients/google-cloud-redis/pom.xml
  google-cloud-clients/google-cloud-redis/synth.metadata
  google-cloud-clients/google-cloud-redis/synth.py
  versions.txt
Labels: cla: yes

#6649 deps: update google-cloud-core to 1.91.3
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#6573 chore: stop release of securitycenter
  google-api-grpc/grpc-google-cloud-securitycenter-v1/pom.xml
  google-api-grpc/grpc-google-cloud-securitycenter-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-securitycenter-v1/pom.xml
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-securitycenter/README.md
  google-cloud-clients/google-cloud-securitycenter/pom.xml
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
  google-cloud-clients/google-cloud-securitycenter/synth.py
  versions.txt
Labels: cla: yes

#6619 chore: stop phishingprotection release
  google-api-grpc/grpc-google-cloud-phishingprotection-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-phishingprotection-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-phishingprotection/.repo-metadata.json
  google-cloud-clients/google-cloud-phishingprotection/README.md
  google-cloud-clients/google-cloud-phishingprotection/pom.xml
  google-cloud-clients/google-cloud-phishingprotection/synth.metadata
  google-cloud-clients/google-cloud-phishingprotection/synth.py
  versions.txt
Labels: cla: yes

#6651 chore: stop release for recaptchaenterprise
  google-api-grpc/grpc-google-cloud-recaptchaenterprise-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-recaptchaenterprise-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-recaptchaenterprise/.repo-metadata.json
  google-cloud-clients/google-cloud-recaptchaenterprise/README.md
  google-cloud-clients/google-cloud-recaptchaenterprise/pom.xml
  google-cloud-clients/google-cloud-recaptchaenterprise/synth.metadata
  google-cloud-clients/google-cloud-recaptchaenterprise/synth.py
  versions.txt
Labels: cla: yes

#6640 Start with libraries-bom
  README.md
Labels: cla: yes, type: docs

#6554 Import split-repo boms into google-cloud-bom
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/google-cloud-datastore/pom.xml
  google-cloud-clients/google-cloud-firestore/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#6575 chore: stop release of scheduler
  google-api-grpc/grpc-google-cloud-scheduler-v1/pom.xml
  google-api-grpc/grpc-google-cloud-scheduler-v1beta1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-scheduler-v1/pom.xml
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-scheduler/README.md
  google-cloud-clients/google-cloud-scheduler/pom.xml
  google-cloud-clients/google-cloud-scheduler/synth.metadata
  google-cloud-clients/google-cloud-scheduler/synth.py
  versions.txt
Labels: cla: yes

#6659 chore: stop release for language
  google-api-grpc/grpc-google-cloud-language-v1/pom.xml
  google-api-grpc/grpc-google-cloud-language-v1beta2/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-language-v1/pom.xml
  google-api-grpc/proto-google-cloud-language-v1beta2/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-language/.repo-metadata.json
  google-cloud-clients/google-cloud-language/README.md
  google-cloud-clients/google-cloud-language/pom.xml
  google-cloud-clients/google-cloud-language/synth.metadata
  google-cloud-clients/google-cloud-language/synth.py
  versions.txt
Labels: cla: yes

#6662 chore: stop release for os-login
  google-api-grpc/grpc-google-cloud-os-login-v1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-os-login-v1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-os-login/.repo-metadata.json
  google-cloud-clients/google-cloud-os-login/README.md
  google-cloud-clients/google-cloud-os-login/pom.xml
  google-cloud-clients/google-cloud-os-login/synth.metadata
  google-cloud-clients/google-cloud-os-login/synth.py
  versions.txt
Labels: cla: yes

#6658 chore: stop release of kms
  google-api-grpc/grpc-google-cloud-kms-v1/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-kms-v1/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-kms/.repo-metadata.json
  google-cloud-clients/google-cloud-kms/README.md
  google-cloud-clients/google-cloud-kms/pom.xml
  google-cloud-clients/google-cloud-kms/synth.metadata
  google-cloud-clients/google-cloud-kms/synth.py
  versions.txt
Labels: cla: yes

#6661 chore: stop release for monitoring
  google-api-grpc/grpc-google-cloud-monitoring-v3/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-monitoring-v3/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-monitoring/.repo-metadata.json
  google-cloud-clients/google-cloud-monitoring/README.md
  google-cloud-clients/google-cloud-monitoring/pom.xml
  google-cloud-clients/google-cloud-monitoring/synth.metadata
  google-cloud-clients/google-cloud-monitoring/synth.py
  versions.txt
Labels: cla: yes

#6660 chore: stop release of logging
  google-api-grpc/grpc-google-cloud-logging-v2/pom.xml
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-logging-v2/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/pom.xml
  google-cloud-clients/google-cloud-logging/.repo-metadata.json
  google-cloud-clients/google-cloud-logging/README.md
  google-cloud-clients/google-cloud-logging/pom.xml
  google-cloud-clients/google-cloud-logging/synth.metadata
  google-cloud-clients/google-cloud-logging/synth.py
  versions.txt
Labels: cla: yes

#6670 chore: stop release of resourcemanager
  google-cloud-clients/google-cloud-resourcemanager/pom.xml
Labels: cla: yes

#6618 nit(storage): v4 url curl command missing space
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
Labels: cla: yes
