Repository googleapis/google-cloud-java, pull requests merged in 2019-01, with the labels that each got.

#4225 Fix Kokoro release jobs
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  RELEASING.md
  google-api-grpc/pom.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
  google-cloud-testing/google-cloud-bigtable-emulator/pom.xml
Labels: cla: yes

#4250 Pubsub added message abandonment
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckReplyConsumer.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDispatcherTest.java
Labels: cla: yes

#4262 BigQuery : Fix Maximum Bytes Billed property.
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
Labels: api: bigquery, cla: yes

#4256 Update UsePubSubEmulatorSnippet.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/UsePubSubEmulatorSnippet.java
Labels: api: pubsub, cla: yes

#4254 Logging: disable severity based flush on write by default
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/Logging.java
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/BaseSystemTest.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingImplTest.java
Labels: cla: yes

#4232 Docs: Fix maven site generation
  google-api-grpc/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#4249 Fixed cannot call public methods in via reflection
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/BasePath.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Option.java
Labels: cla: yes

#4271 BigQuery : Fix numBytes, numRows in TableInfo/Table
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Table.java
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableInfo.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableInfoTest.java
Labels: cla: yes

#4274 Cloud Bigtable: helloWorld sample
  google-cloud-examples/pom.xml
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigtable/HelloWorld.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigtable/ITHelloWorld.java
Labels: cla: yes

#4280 Add .tmpl extension for README.md so releasetool is not confused
  utilities/new_client.py
  utilities/templates/README.md.tmpl
Labels: cla: yes

#4289 Fix #4284 fix NPE for getZone
  google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/MetadataConfig.java
Labels: cla: yes

#4290 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/Source.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/SourceOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/proto/google/cloud/securitycenter/v1beta1/source.proto
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4258 Bigtable admin: deprecate typesafe names part 2
  .kokoro/continuous/bigtableadmin-it.cfg
  .kokoro/nightly/bigtableadmin-it.cfg
  .kokoro/presubmit/bigtableadmin-it.cfg
  TESTING.md
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettings.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettings.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/internal/NameUtil.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateAppProfileRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateInstanceRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/ModifyColumnFamiliesRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateAppProfileRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateInstanceRequest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettingsTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettingsTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateAppProfileRequestTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequestTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/TableAdminRequestsTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateAppProfileRequestTest.java
  google-cloud-clients/google-cloud-bigtable-admin/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateInstanceRequestTest.java
Labels: api: bigtable, cla: yes

#4297 Revert "Pub/Sub: Add message abandonment (#4250)"
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckReplyConsumer.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDispatcherTest.java
Labels: cla: yes

#4287 updated links
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Field.java
Labels: cla: yes

#4301 Regenerate dataproc client
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/ClustersProto.java
  google-api-grpc/proto-google-cloud-dataproc-v1/src/main/proto/google/cloud/dataproc/v1/clusters.proto
  google-api-grpc/proto-google-cloud-dataproc-v1beta2/src/main/java/com/google/cloud/dataproc/v1beta2/ClustersProto.java
  google-api-grpc/proto-google-cloud-dataproc-v1beta2/src/main/proto/google/cloud/dataproc/v1beta2/clusters.proto
  google-cloud-clients/google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4299 Cloud Bigtable: instanceAdmin sample
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigtable/InstanceAdminExample.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigtable/ITInstanceAdminExample.java
Labels: api: bigtable, cla: yes

#4311 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/Asset.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/Finding.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/FindingOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/Source.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/SourceOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/UpdateFindingRequest.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/UpdateFindingRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/proto/google/cloud/securitycenter/v1beta1/asset.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/proto/google/cloud/securitycenter/v1beta1/finding.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/proto/google/cloud/securitycenter/v1beta1/securitycenter_service.proto
  google-api-grpc/proto-google-cloud-securitycenter-v1beta1/src/main/proto/google/cloud/securitycenter/v1beta1/source.proto
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
Labels: cla: yes

#4305 3540: Used transformer for shaded plugin
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/pom.xml
Labels: cla: yes

#4291 Added Query#fromProto to convert protobuf ReadRowsRequest
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/NameUtil.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java
Labels: cla: yes

#4303 4152: Added checking PAGE_TOKEN from options
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
Labels: cla: yes

#4304 3918: Added checking of attributes size for 0. Added unit test
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileAttributesTest.java
Labels: cla: yes

#4293 Regenerate pubsub client
  google-api-grpc/grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublisherGrpc.java
  google-api-grpc/grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriberGrpc.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/CreateSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/CreateSnapshotRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSnapshotsRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSnapshotsResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSnapshotsRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSnapshotsResponse.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/MessageStoragePolicy.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/MessageStoragePolicyOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ModifyAckDeadlineRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ModifyAckDeadlineRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessage.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SeekRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Snapshot.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SnapshotOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriptionOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Topic.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicOrBuilder.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UpdateSnapshotRequest.java
  google-api-grpc/proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4316 Regenerate monitoring client
  google-api-grpc/grpc-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/NotificationChannelServiceGrpc.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/InternalChecker.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/InternalCheckerOrBuilder.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/NotificationServiceProto.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/ServiceTier.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/UptimeCheckConfig.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/UptimeCheckConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/UptimeProto.java
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/alert.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/alert_service.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/common.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/dropped_labels.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/group.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/group_service.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/metric.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/metric_service.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/mutation_record.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/notification.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/notification_service.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/span_context.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/uptime.proto
  google-api-grpc/proto-google-cloud-monitoring-v3/src/main/proto/google/monitoring/v3/uptime_service.proto
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/NotificationChannelServiceClient.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/AlertPolicyServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GroupServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/MetricServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/NotificationChannelServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/UptimeCheckServiceStubSettings.java
  google-cloud-clients/google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4318 Regenerate bigtable client
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BaseBigtableDataClientTest.java
  google-cloud-clients/google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4314 3822: Fixed setDisableGZipContent call
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
Labels: api: storage, cla: yes

#4317 Regenerate Speech: Add multi-channel recognition
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechProto.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechRecognitionAlternative.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechRecognitionAlternativeOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechRecognitionResult.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechRecognitionResultOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognitionResult.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognitionResultOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/proto/google/cloud/speech/v1/cloud_speech.proto
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#4309 Created enum Region.java to retrieve Regions without doing request.
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/Regions.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/RegionsTest.java
Labels: api: compute, cla: yes

#4323 Bigtable: fix handling of unset rpc timeouts
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
  google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallableTest.java
Labels: api: bigtable, cla: yes, type: bug

#4321 Bigtable: Expose single row read settings
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
Labels: api: bigtable, cla: yes, type: feature request

#4327 Regenerate compute client
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Instance.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InstanceGroupManager.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InstanceGroupManagerAutoHealingPolicy.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InstanceTemplateClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InterconnectLocation.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/NodeGroupClient.java
  google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/Quota.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/InstanceClientTest.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/InterconnectLocationClientTest.java
  google-cloud-clients/google-cloud-compute/synth.metadata
Labels: cla: yes

#4328 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/proto/google/cloud/speech/v1/cloud_speech.proto
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#4322 Update README version to use bom version
  README.md
Labels: cla: yes

#4338 BigQuery: Fix NPE for null table schema fields
  google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Schema.java
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/SchemaTest.java
Labels: cla: yes

#4339 Cloud Bigtable: HelloWorld sample updates
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigtable/HelloWorld.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigtable/ITHelloWorld.java
Labels: api: bigtable, cla: yes

#4346 Cloud Bigtable: InstanceAdmin sample update
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigtable/ITInstanceAdminExample.java
Labels: cla: yes

#4350 Pub/Sub: default values in batch settings comments
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/PublisherSnippets.java
Labels: cla: yes

#4344 Update maven-surefire-plugin to 3.0.0-M3 to fix Java 8 classloader
  google-cloud-clients/google-cloud-bigtable/pom.xml
  google-cloud-clients/google-cloud-logging/pom.xml
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/pom.xml
  google-cloud-examples/pom.xml
  google-cloud-testing/google-cloud-bigtable-emulator/pom.xml
  google-cloud-util/pom.xml
Labels: cla: yes

#4342 Bigtable: Fixing a typo for KeyOffSet#geyKey to getKey
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/KeyOffset.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
Labels: cla: yes

#4332 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#4334 Spanner: remove junit from compile dependencies
  google-cloud-clients/google-cloud-spanner/pom.xml
Labels: cla: yes

#4353 Firestore: Change timestampsInSnapshots default to true.
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/CollectionReferenceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/DocumentReferenceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/QueryTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/WatchTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/WriteBatchTest.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java
Labels: cla: yes

#4313 Cloud Bigtable: tableAdmin sample
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigtable/TableAdminExample.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigtable/ITTableAdminExample.java
Labels: api: bigtable, cla: yes

#4294 Regenerate scheduler client
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/SchedulerProto.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/cloudscheduler.proto
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClient.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/package-info.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClientTest.java
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4388 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/package-info.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/DatabaseAdminStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/DatabaseAdminStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/GrpcDatabaseAdminCallableFactory.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/GrpcDatabaseAdminStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/package-info.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/stub/GrpcInstanceAdminCallableFactory.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/stub/GrpcInstanceAdminStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/stub/InstanceAdminStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/stub/InstanceAdminStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerSettings.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/package-info.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/GrpcSpannerCallableFactory.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/GrpcSpannerStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStub.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClientTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/database/v1/MockDatabaseAdmin.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/database/v1/MockDatabaseAdminImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClientTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/instance/v1/MockInstanceAdmin.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/instance/v1/MockInstanceAdminImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/MockSpanner.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/MockSpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/SpannerClientTest.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#4395 Regenerate asset client
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/Asset.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/AssetOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/AssetServiceProto.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/BatchGetAssetsHistoryRequest.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/BatchGetAssetsHistoryRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ExportAssetsRequest.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/ExportAssetsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/GcsDestination.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/GcsDestinationOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/TimeWindow.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/TimeWindowOrBuilder.java
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/proto/google/cloud/asset/v1beta1/asset_service.proto
  google-api-grpc/proto-google-cloud-asset-v1beta1/src/main/proto/google/cloud/asset/v1beta1/assets.proto
  google-cloud-clients/google-cloud-asset/synth.metadata
Labels: cla: yes

#4396 Regenerate scheduler client
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineHttpTarget.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineHttpTargetOrBuilder.java
  google-api-grpc/proto-google-cloud-scheduler-v1beta1/src/main/proto/google/cloud/scheduler/v1beta1/target.proto
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClient.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerSettings.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/package-info.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStub.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStubSettings.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/GrpcCloudSchedulerCallableFactory.java
  google-cloud-clients/google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/GrpcCloudSchedulerStub.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClientTest.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/MockCloudScheduler.java
  google-cloud-clients/google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/MockCloudSchedulerImpl.java
  google-cloud-clients/google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4352 Firestore: Include a trailing /documents on root resource paths
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/ResourcePath.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java
Labels: cla: yes

#4385 Removing some unused dependencies
  google-cloud-clients/google-cloud-asset/pom.xml
  google-cloud-clients/google-cloud-bigquery/pom.xml
  google-cloud-clients/google-cloud-bigquerydatatransfer/pom.xml
  google-cloud-clients/google-cloud-core-http/pom.xml
  google-cloud-clients/google-cloud-dataproc/pom.xml
  google-cloud-clients/google-cloud-dns/pom.xml
  google-cloud-clients/google-cloud-firestore/pom.xml
  google-cloud-clients/google-cloud-pubsub/pom.xml
  google-cloud-clients/google-cloud-redis/pom.xml
  google-cloud-clients/google-cloud-scheduler/pom.xml
  google-cloud-clients/google-cloud-spanner/pom.xml
  google-cloud-clients/google-cloud-speech/pom.xml
  google-cloud-clients/google-cloud-tasks/pom.xml
  google-cloud-clients/google-cloud-trace/pom.xml
  google-cloud-clients/google-cloud-video-intelligence/pom.xml
  google-cloud-clients/google-cloud-vision/pom.xml
Labels: cla: yes

#4406 fix shading
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/pom.xml
Labels: cla: yes

#4408 [Storage] Bucket Policy Only samples
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITStorageSnippets.java
Labels: api: storage, cla: yes
