Repository googleapis/google-cloud-java, pull requests merged in 2019-06, with the labels that each got.

#5188 Spanner: PartitionedDML transaction does not need a prepared session
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Labels: cla: yes

#5228 Firestore conformance tests refactor
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceConversions.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/ConformanceTest.java
  google-cloud-clients/google-cloud-firestore/src/test/resources/com/google/cloud/firestore/conformance/test-suite.binproto
Labels: cla: yes

#5283 Spanner: Fix incompatibility with Gax 1.45
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
Labels: cla: yes

#5247 FireStore:deprecated warnings removed
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpc.java
Labels: api: firestore, cla: yes

#5230 Regenerate securitycenter client
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/RunAssetDiscoveryResponseOuterClass.java
  google-api-grpc/proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/run_asset_discovery_response.proto
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterSettings.java
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/stub/GrpcSecurityCenterStub.java
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/stub/SecurityCenterStub.java
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/stub/SecurityCenterStubSettings.java
  google-cloud-clients/google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClient.java
  google-cloud-clients/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/SecurityCenterClientTest.java
  google-cloud-clients/google-cloud-securitycenter/synth.metadata
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/AssetSnippets.java
Labels: cla: yes

#5303 Moving google-cloud-notification to -contrib
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/README.md
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/pom.xml
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/src/main/java/com/google/cloud/notification/Notification.java
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/src/main/java/com/google/cloud/notification/NotificationImpl.java
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/src/main/java/com/google/cloud/notification/NotificationInfo.java
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/src/test/java/com/google/cloud/notification/NotificationInfoTest.java
  google-cloud-clients/google-cloud-contrib/google-cloud-notification/src/test/java/com/google/cloud/notification/it/ITSystemTest.java
  google-cloud-clients/google-cloud-contrib/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#5306 Import google-oauth-client-bom and google-api-client-bom.
  google-cloud-clients/pom.xml
Labels: cla: yes

#5242 Add integration tests for snapshot read and resuming.
  google-cloud-clients/google-cloud-bigquerystorage/pom.xml
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/it/ITBigQueryStorageTest.java
Labels: api: bigquery, cla: yes

#5307 Configure renovate to group grpc, protobuf, opencensus updates together
  renovate.json
Labels: cla: yes

#5309 Spanner: Properly end span for ResumableStreamIterator.
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResumableStreamIteratorTest.java
Labels: cla: yes

#5406 Datastore:deprecated warnings removed
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/Blob.java
Labels: cla: yes

#5409 Updating GAX in clients to 1.45.0 for docs.
  google-cloud-clients/pom.xml
Labels: cla: yes

#5411 Changed title on readme to match external-facing client library name …
  google-cloud-clients/google-cloud-bigtable/README.md
Labels: cla: yes

#5363 Cloud Scheduler GA
  README.md
  versions.txt
Labels: cla: yes

#5401 Regenerate video-intelligence client
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/LabelDetectionConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/LabelDetectionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/ObjectTrackingConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/ObjectTrackingConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/TextDetectionConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/TextDetectionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoContext.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoContextOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/java/com/google/cloud/videointelligence/v1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1/src/main/proto/google/cloud/videointelligence/v1/video_intelligence.proto
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/DetectedAttribute.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/DetectedAttributeOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/Feature.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/LabelDetectionConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/LabelDetectionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/LogoRecognitionAnnotation.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/LogoRecognitionAnnotationOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/ObjectTrackingConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/ObjectTrackingConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/SpeechContext.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/SpeechContextOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/SpeechRecognitionAlternative.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/SpeechRecognitionAlternativeOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/SpeechTranscription.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/SpeechTranscriptionConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/SpeechTranscriptionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/SpeechTranscriptionOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingAnnotateVideoRequest.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingAnnotateVideoRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingAnnotateVideoResponse.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingAnnotateVideoResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingVideoAnnotationResults.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingVideoAnnotationResultsOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingVideoConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingVideoConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/TextDetectionConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/TextDetectionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/TimestampedObject.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/TimestampedObjectOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/Track.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/TrackOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/VideoAnnotationResults.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/VideoAnnotationResultsOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/VideoContext.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/VideoContextOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/WordInfo.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/WordInfoOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/proto/google/cloud/videointelligence/v1p3beta1/video_intelligence.proto
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#5417 Regenerate pubsub client - increase publish timeout
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  google-cloud-clients/google-cloud-pubsub/synth.metadata
Labels: cla: yes

#5419 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechContext.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechContextOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#5432 Regenerate dlp client
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/Action.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpProto.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpStorage.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InspectJobConfig.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/InspectJobConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/LargeCustomDictionaryStats.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/LargeCustomDictionaryStatsOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListDlpJobsRequest.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ListDlpJobsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/StoredInfoTypeStats.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/StoredInfoTypeStatsOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/StoredInfoTypeVersion.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/StoredInfoTypeVersionOrBuilder.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/dlp.proto
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/storage.proto
  google-cloud-clients/google-cloud-dlp/synth.metadata
Labels: cla: yes

#5405 Logging:deprecated warnings removed
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java
  google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/spi/v2/GrpcLoggingRpc.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingImplTest.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/v2/testing/LocalLoggingHelper.java
Labels: cla: yes

#5364 Add Container Analysis v1 service
  google-api-grpc/grpc-google-cloud-containeranalysis-v1/pom.xml
  google-api-grpc/grpc-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/ContainerAnalysisGrpc.java
  google-api-grpc/pom.xml
  google-api-grpc/proto-google-cloud-containeranalysis-v1/pom.xml
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/Containeranalysis.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/IamResourceName.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/IamResourceNames.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/NoteName.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/OccurrenceName.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/ProjectName.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/UntypedIamResourceName.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/proto/google/devtools/containeranalysis/v1/containeranalysis.proto
  google-cloud-bom/pom.xml
  google-cloud-clients/google-cloud-containeranalysis/pom.xml
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/ContainerAnalysisClient.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/ContainerAnalysisSettings.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/package-info.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/ContainerAnalysisStub.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/ContainerAnalysisStubSettings.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/GrpcContainerAnalysisCallableFactory.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/GrpcContainerAnalysisStub.java
  google-cloud-clients/google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1/ContainerAnalysisClientTest.java
  google-cloud-clients/google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1/MockContainerAnalysis.java
  google-cloud-clients/google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1/MockContainerAnalysisImpl.java
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
  google-cloud-clients/google-cloud-containeranalysis/synth.py
  versions.txt
Labels: cla: yes

#5443 Enable autorelease
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  RELEASING.md
  pom.xml
Labels: cla: yes

#5448 Clean up Spanner README.md
  google-cloud-clients/google-cloud-spanner/README.md
Labels: cla: yes

#5407 Core-http:deprecated warnings removed
  google-cloud-clients/google-cloud-core-http/src/test/java/com/google/cloud/http/CensusHttpModuleTest.java
Labels: cla: yes

#5439 Add integration tests for partitioning.
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/it/ITBigQueryStorageTest.java
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/it/SimpleRowReader.java
Labels: cla: yes

#5185 Fix FakeStorageRpc that doesn't set the blob size when returning blobs from the list method
  google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
Labels: :rotating_light:, cla: yes

#5449 Use maven's parallel mode to improve test time. Use 1 thread per core
  .kokoro/build.sh
  .kokoro/release/publish_javadoc.sh
Labels: cla: yes

#5413 Update google-auth-library to 0.16.1 and import using new bom
  google-cloud-clients/google-cloud-storage/pom.xml
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
  google-cloud-clients/pom.xml
Labels: cla: yes

#5450 Use grpc-netty-shaded for the compat-checker
  google-cloud-util/google-cloud-compat-checker/pom.xml
  google-cloud-util/google-cloud-compat-checker/src/main/java/com/google/cloud/compatchecker/GoogleCloudCompatChecker.java
Labels: cla: yes

#5454 Regenerate translate client
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/BatchTranslateMetadata.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/BatchTranslateMetadataOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/BatchTranslateTextRequest.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/BatchTranslateTextRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/CreateGlossaryMetadata.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/DeleteGlossaryMetadata.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/DetectLanguageRequest.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/DetectLanguageRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/GcsDestination.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/GcsDestinationOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/GcsSource.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/GetSupportedLanguagesRequest.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/GetSupportedLanguagesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/Glossary.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/GlossaryInputConfig.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/GlossaryInputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/GlossaryOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/InputConfig.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/InputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/ListGlossariesRequest.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/ListGlossariesRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/OutputConfig.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/OutputConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/TranslateTextGlossaryConfig.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/TranslateTextGlossaryConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/TranslateTextRequest.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/TranslateTextRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/TranslateTextResponse.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/TranslateTextResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/Translation.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/TranslationOrBuilder.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceProto.java
  google-api-grpc/proto-google-cloud-translate-v3beta1/src/main/proto/google/cloud/translate/v3beta1/translation_service.proto
  google-cloud-clients/google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceClient.java
  google-cloud-clients/google-cloud-translate/synth.metadata
Labels: cla: yes

#5458 Regenerate bigquerydatatransfer client - minor comment changes
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CreateTransferConfigRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CreateTransferConfigRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/UpdateTransferConfigRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/UpdateTransferConfigRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/proto/google/cloud/bigquery/datatransfer/v1/datatransfer.proto
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
Labels: cla: yes

#5460 Cloud-examples:deprecated warnings removed
  google-cloud-examples/src/test/java/com/google/cloud/examples/pubsub/snippets/ITPubSubSnippets.java
Labels: cla: yes, kokoro:force-run

#5456 Fix docs linking between service stubs and request proto types
  .kokoro/release/publish_javadoc.sh
  google-api-grpc/pom.xml
  google-api-grpc/src/site/site.xml
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
  google-cloud-clients/src/site/site.xml
Labels: cla: yes

#5459 Firestore:deprecated warnings removed
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/CollectionReference.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/DocumentReference.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Transaction.java
  google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UpdateBuilder.java
  google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/conformance/TestDefinition.java
Labels: cla: yes

#5463 Regenerate containeranalysis client
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/Containeranalysis.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/proto/google/devtools/containeranalysis/v1/containeranalysis.proto
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
Labels: cla: yes

#5470 Regenerate datacatalog client
  google-api-grpc/grpc-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/DataCatalogGrpc.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/CreateTagRequest.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/CreateTagRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/CreateTagTemplateFieldRequest.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/CreateTagTemplateFieldRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/CreateTagTemplateRequest.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/CreateTagTemplateRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/Entry.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/EntryOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/SearchCatalogRequest.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/SearchCatalogRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/Tag.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/TagOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/TagTemplate.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/TagTemplateOrBuilder.java
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/proto/google/cloud/datacatalog/v1beta1/datacatalog.proto
  google-api-grpc/proto-google-cloud-datacatalog-v1beta1/src/main/proto/google/cloud/datacatalog/v1beta1/tags.proto
  google-cloud-clients/google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/DataCatalogClient.java
  google-cloud-clients/google-cloud-datacatalog/synth.metadata
Labels: cla: yes

#5452 Make getProperties method public in BaseEntity
  google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/BaseEntity.java
Labels: cla: yes

#5475 bigquery: address snippet feedback.
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITBigQuerySnippets.java
Labels: cla: yes

#5494 Regenerate video-intelligence client
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta1/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta1/package-info.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta2/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1beta2/package-info.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p1beta1/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p1beta1/package-info.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p2beta1/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p2beta1/package-info.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/VideoIntelligenceServiceClient.java
  google-cloud-clients/google-cloud-video-intelligence/src/main/java/com/google/cloud/videointelligence/v1p3beta1/package-info.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1beta1/VideoIntelligenceServiceClientTest.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1beta2/VideoIntelligenceServiceClientTest.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p1beta1/VideoIntelligenceServiceClientTest.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p1beta1/VideoIntelligenceServiceSmokeTest.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p2beta1/VideoIntelligenceServiceClientTest.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p2beta1/VideoIntelligenceServiceSmokeTest.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p3beta1/VideoIntelligenceServiceClientTest.java
  google-cloud-clients/google-cloud-video-intelligence/src/test/java/com/google/cloud/videointelligence/v1p3beta1/VideoIntelligenceServiceSmokeTest.java
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#5468 Pub/Sub: Shutting down Subscriber executor
  google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-clients/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
Labels: cla: yes

#5479 Disable doclint on when attaching javadocs at release time
  google-cloud-clients/pom.xml
Labels: cla: yes, release blocking

#5469 Update Bigtable README.md.
  google-cloud-clients/google-cloud-bigtable/README.md
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/package-info.java
Labels: cla: yes

#5501 Bigtable: remove all deprecated methods
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
Labels: cla: yes

#5473 Updated `UnsafeByteOperations.unsafeWrap` to `ByteString.copyFrom`
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Range.java
Labels: cla: yes

#5476 Add integration tests for BigQuery SQL types.
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/it/ITBigQueryStorageTest.java
Labels: cla: yes

#5507 Regenerate dlp client
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/ByteContentItem.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpProto.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/DlpStorage.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/java/com/google/privacy/dlp/v2/FileType.java
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/dlp.proto
  google-api-grpc/proto-google-cloud-dlp-v2/src/main/proto/google/privacy/dlp/v2/storage.proto
  google-cloud-clients/google-cloud-dlp/synth.metadata
Labels: cla: yes

#5506 Regenerate bigquerydatatransfer client
  google-api-grpc/grpc-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceGrpc.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSource.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceParameter.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceParameterOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferProto.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/EnableDataTransferServiceRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/EnableDataTransferServiceRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/IsDataTransferServiceEnabledRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/IsDataTransferServiceEnabledRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/IsDataTransferServiceEnabledResponse.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/IsDataTransferServiceEnabledResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ResourceStateProto.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ScheduleTransferRunsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ScheduleTransferRunsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/StartManualTransferRunsRequest.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/StartManualTransferRunsRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferConfig.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferMessage.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferProto.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferRun.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferRunOrBuilder.java
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/proto/google/cloud/bigquery/datatransfer/v1/datatransfer.proto
  google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/proto/google/cloud/bigquery/datatransfer/v1/transfer.proto
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClient.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceSettings.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/DataTransferServiceStub.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/DataTransferServiceStubSettings.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/GrpcDataTransferServiceStub.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/test/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClientTest.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/test/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceSmokeTest.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/src/test/java/com/google/cloud/bigquery/datatransfer/v1/MockDataTransferServiceImpl.java
  google-cloud-clients/google-cloud-bigquerydatatransfer/synth.metadata
Labels: cla: yes

#5509 Cleanup contrib README.md.
  google-cloud-clients/google-cloud-contrib/README.md
Labels: cla: yes

#5510 Preparing Easymock for a future upgrade.
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryOptionsTest.java
  google-cloud-clients/google-cloud-compute/src/test/java/com/google/cloud/compute/deprecated/ComputeOptionsTest.java
  google-cloud-clients/google-cloud-datastore/src/test/java/com/google/cloud/datastore/DatastoreOptionsTest.java
  google-cloud-clients/google-cloud-dns/src/test/java/com/google/cloud/dns/DnsOptionsTest.java
  google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingOptionsTest.java
  google-cloud-clients/google-cloud-resourcemanager/src/test/java/com/google/cloud/resourcemanager/ResourceManagerOptionsTest.java
  google-cloud-clients/google-cloud-storage/src/test/java/com/google/cloud/storage/StorageOptionsTest.java
  google-cloud-clients/google-cloud-translate/src/test/java/com/google/cloud/translate/TranslateOptionsTest.java
Labels: cla: yes

#5511 Bigtable: Remove and inline internal class DummyBatchingDescriptor.
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/DummyBatchingDescriptor.java
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
Labels: cla: yes

#5512 Prep Bigtable Beta release.
  README.md
  google-cloud-clients/google-cloud-bigtable/README.md
  versions.txt
Labels: cla: yes

#5126 [Bigtable] Documented defaults timeout values in the EnhancedBigtableStubSettings
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
Labels: :rotating_light:, api: bigtable, cla: yes

#5515 Storage: remove reflection to get raw input stream
  google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
Labels: cla: yes

#5433 Spanner: Use generic retry helper for transaction retries
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerRetryHelper.java
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerRetryHelperTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
Labels: :rotating_light:, cla: yes

#5526 Upgrade gax to 1.46.1.
  google-cloud-bom/pom.xml
  google-cloud-clients/pom.xml
Labels: cla: yes

#5527 Adding linkage monitor Kokoro config
  .kokoro/linkage-monitor.sh
  .kokoro/presubmit/linkage-monitor.cfg
Labels: cla: yes

#5535 Regenerate dialogflow client
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/AgentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/EntityTypeProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/Intent.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/WebhookProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/WebhookResponse.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/WebhookResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/agent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/entity_type.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/intent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/webhook.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/EntityTypeProto.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/Intent.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/WebhookResponse.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/WebhookResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/agent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/entity_type.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/intent.proto
  google-api-grpc/proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/webhook.proto
  google-cloud-clients/google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#5514 Regenerate containeranalysis client
  google-api-grpc/grpc-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/ContainerAnalysisGrpc.java
  google-api-grpc/proto-google-cloud-containeranalysis-v1/src/main/proto/google/devtools/containeranalysis/v1/containeranalysis.proto
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/ContainerAnalysisClient.java
  google-cloud-clients/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/package-info.java
  google-cloud-clients/google-cloud-containeranalysis/synth.metadata
Labels: cla: yes

#5412 Spanner: Retry aborted partitioned dml transactions
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
Labels: :rotating_light:, cla: yes

#5516 Regenerate video-intelligence client
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingAutomlClassificationConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingAutomlClassificationConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingAutomlObjectTrackingConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingAutomlObjectTrackingConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingFeature.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingVideoConfig.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/StreamingVideoConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/java/com/google/cloud/videointelligence/v1p3beta1/VideoIntelligenceServiceProto.java
  google-api-grpc/proto-google-cloud-video-intelligence-v1p3beta1/src/main/proto/google/cloud/videointelligence/v1p3beta1/video_intelligence.proto
  google-cloud-clients/google-cloud-video-intelligence/synth.metadata
Labels: cla: yes

#5558 Spanner - Respect RetryInfo returned by server error
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerRetryHelper.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerRetryHelperTest.java
Labels: cla: yes

#5523 Regenerate spanner client
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-clients/google-cloud-spanner/synth.metadata
Labels: cla: yes

#5559 Logback:Fix null check in LoggingAppender when copies values from MDC to LogEntry labels
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
  google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
Labels: cla: yes

#5562 Spanner: Throw more descriptive error message on cancelled exception.
  google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerExceptionFactoryTest.java
Labels: cla: yes

#5552 Translate : Cleanup dependency translate 4383
  google-cloud-clients/google-cloud-translate/pom.xml
Labels: cla: yes

#5567 Add Kokoro test config for clients that have smoke tests to run
  .kokoro/continuous/container-it.cfg
  .kokoro/continuous/dataproc-it.cfg
  .kokoro/continuous/errorreporting-it.cfg
  .kokoro/continuous/iot-it.cfg
  .kokoro/continuous/language-it.cfg
  .kokoro/continuous/monitoring-it.cfg
  .kokoro/continuous/texttospeech-it.cfg
  .kokoro/continuous/trace-it.cfg
  .kokoro/continuous/video-intelligence-it.cfg
  .kokoro/continuous/vision-it.cfg
  .kokoro/nightly/container-it.cfg
  .kokoro/nightly/dataproc-it.cfg
  .kokoro/nightly/errorreporting-it.cfg
  .kokoro/nightly/iot-it.cfg
  .kokoro/nightly/language-it.cfg
  .kokoro/nightly/monitoring-it.cfg
  .kokoro/nightly/texttospeech-it.cfg
  .kokoro/nightly/trace-it.cfg
  .kokoro/nightly/video-intelligence-it.cfg
  .kokoro/nightly/vision-it.cfg
  .kokoro/presubmit/container-it.cfg
  .kokoro/presubmit/dataproc-it.cfg
  .kokoro/presubmit/errorreporting-it.cfg
  .kokoro/presubmit/iot-it.cfg
  .kokoro/presubmit/language-it.cfg
  .kokoro/presubmit/monitoring-it.cfg
  .kokoro/presubmit/texttospeech-it.cfg
  .kokoro/presubmit/trace-it.cfg
  .kokoro/presubmit/video-intelligence-it.cfg
  .kokoro/presubmit/vision-it.cfg
Labels: cla: yes

#5532 Fix autorelease to actually autorelease after staging
  .kokoro/release/stage.sh
Labels: cla: yes

#5576 Regenerate speech client
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1/src/main/proto/google/cloud/speech/v1/cloud_speech.proto
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfig.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfigOrBuilder.java
  google-api-grpc/proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
  google-cloud-clients/google-cloud-speech/synth.metadata
Labels: cla: yes

#5574 Regenerate automl client
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/AnnotationPayloadOuterClass.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/AnnotationSpecOuterClass.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/AutoMlProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ClassificationProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ColumnSpecOuterClass.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DataItems.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DataStatsOuterClass.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DataTypes.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DatasetOuterClass.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Detection.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Geometry.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ImageProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Io.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ModelEvaluationOuterClass.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ModelOuterClass.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Operations.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictionServiceProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/RangesProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/RegressionProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TableSpecOuterClass.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Tables.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Temporal.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextExtraction.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextSegmentProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextSentimentProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TranslationProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/VideoProto.java
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/annotation_payload.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/annotation_spec.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/classification.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/column_spec.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/data_items.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/data_stats.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/data_types.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/dataset.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/detection.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/geometry.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/image.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/io.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/model.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/model_evaluation.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/operations.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/prediction_service.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/ranges.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/regression.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/service.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/table_spec.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/tables.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/temporal.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/text.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/text_extraction.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/text_segment.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/text_sentiment.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/translation.proto
  google-api-grpc/proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/video.proto
  google-cloud-clients/google-cloud-automl/synth.metadata
Labels: cla: yes

#5573 Upgrading Truth dependency to 0.46
  google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResultSetsTest.java
  google-cloud-clients/pom.xml
  google-cloud-testing/google-cloud-bigtable-emulator/pom.xml
  google-cloud-testing/pom.xml
Labels: cla: yes

#5568 [Bigtable] minor Javadoc clean up for ModifyColumnFamiliesRequest
  google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/ModifyColumnFamiliesRequest.java
Labels: cla: yes

#5578 Cleanup dependency vision 4383
  google-cloud-clients/google-cloud-vision/pom.xml
Labels: cla: yes

#5577 ResourceManager: Fix Project properties.
  google-cloud-clients/google-cloud-resourcemanager/src/main/java/com/google/cloud/resourcemanager/Project.java
  google-cloud-clients/google-cloud-resourcemanager/src/main/java/com/google/cloud/resourcemanager/ProjectInfo.java
Labels: cla: yes

#5538 Add a long running BQ Storage API integration test for nightly builds.
  .kokoro/nightly/bigquery-storage-it.cfg
  google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/it/ITBigQueryStorageLongRunningTest.java
Labels: cla: yes

#5584 removed duplicate dependency
  google-cloud-clients/google-cloud-bigquerystorage/pom.xml
Labels: cla: yes

#5587 Webrisk : Cleanup dependency
  google-cloud-clients/google-cloud-webrisk/pom.xml
Labels: cla: yes

#5589 Automl : Cleanup dependency
  google-cloud-clients/google-cloud-automl/pom.xml
Labels: cla: yes

#5588 Asset : Cleanup dependency
  google-cloud-clients/google-cloud-asset/pom.xml
Labels: cla: yes

#5586 Websecurityscanner : Cleanup dependency
  google-cloud-clients/google-cloud-websecurityscanner/pom.xml
Labels: cla: yes

#5585 Video intelligence : Cleanup dependency
  google-cloud-clients/google-cloud-video-intelligence/pom.xml
Labels: cla: yes

#5540 Create new google-cloud-conformance-tests module
  google-cloud-clients/pom.xml
  google-cloud-testing/google-cloud-conformance-tests/pom.xml
  google-cloud-testing/google-cloud-conformance-tests/src/main/java/com/google/cloud/conformance/ConformanceTestLocator.java
  google-cloud-testing/google-cloud-conformance-tests/src/test/java/com/google/cloud/conformance/ConformanceTestLocatorTest.java
  google-cloud-testing/google-cloud-conformance-tests/src/test/resources/junit/runner/next-2019-hashtag.gif
  google-cloud-testing/google-cloud-conformance-tests/src/test/resources/junit/runner/next-2019-hashtag_readme.md
  google-cloud-testing/pom.xml
Labels: cla: yes

#5575 Regenerate iamcredentials client
  google-api-grpc/grpc-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/IAMCredentialsGrpc.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdentityBindingAccessTokenRequest.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdentityBindingAccessTokenRequestOrBuilder.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdentityBindingAccessTokenResponse.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdentityBindingAccessTokenResponseOrBuilder.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/IAMCredentialsCommonProto.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/IAMCredentialsProto.java
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/proto/google/iam/credentials/v1/common.proto
  google-api-grpc/proto-google-cloud-iamcredentials-v1/src/main/proto/google/iam/credentials/v1/iamcredentials.proto
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/IamCredentialsClient.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/IamCredentialsSettings.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/stub/GrpcIamCredentialsStub.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStub.java
  google-cloud-clients/google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStubSettings.java
  google-cloud-clients/google-cloud-iamcredentials/src/test/java/com/google/cloud/iam/credentials/v1/IamCredentialsClientTest.java
  google-cloud-clients/google-cloud-iamcredentials/src/test/java/com/google/cloud/iam/credentials/v1/MockIAMCredentialsImpl.java
  google-cloud-clients/google-cloud-iamcredentials/synth.metadata
Labels: cla: yes

#5592 bigquery: reduce test flakiness in testCancelJob integration test.
  google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Labels: cla: yes
