Repository googleapis/google-cloud-java, pull requests merged in 2020-08, with the labels that each got.

#7280 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7303 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7305 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7308 docs(samples): cleanup bigquery samples
  google-cloud-examples/README.md
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/BigQueryExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/CloudSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/CreateTableAndLoadData.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/DatasetInfoSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/DatasetSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/InsertDataAndQueryTable.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/JobSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/TableSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITBigQuerySnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITCloudSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITDatasetInfoSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITDatasetSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITJobSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/bigquery/snippets/ITTableSnippets.java
  google-cloud-examples/src/test/resources/bigquery/test_write_and_list_table_data.csv
Labels: cla: yes

#7309 deps: libraries-bom 9.0.0
  TROUBLESHOOTING.md
Labels: cla: yes

#7307 Add compose object sample
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/ComposeObject.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITBlobSnippets.java
Labels: cla: yes

#7278 chore: update deprecated snippets for compute client
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateAddressDiskAndInstance.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateInstance.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateSnapshot.java
Labels: cla: yes

#7316 Fix region tag
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/ComposeObject.java
Labels: cla: yes

#7321 chore: regenerate client list
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7325 docs: latest libraries-bom and linkage checker
  TROUBLESHOOTING.md
Labels: cla: yes
