Repository googleapis/google-cloud-java, pull requests merged in 2020-12, with the labels that each got.

#7397 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7411 docs: add section about long running operations
  README.md
Labels: cla: yes

#7409 docs: update README to reflect Alpine compatibility
  README.md
Labels: cla: yes

#7412 docs: add link to libraries-bom documentation
  README.md
Labels: automerge, cla: yes

#7417 docs: add disclaimer to generate encryption key sample
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/GenerateEncryptionKey.java
Labels: cla: yes, samples

#7413 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7426 docs: libraries-bom 16.2.0
  TROUBLESHOOTING.md
Labels: cla: yes

#7427 feat: add google-java-formatter action
  actions/formatter/Dockerfile
  actions/formatter/action.yaml
  actions/formatter/cloudbuild.yaml
  actions/formatter/entrypoint.sh
Labels: cla: yes
