Repository googleapis/google-cloud-java, pull requests merged in 2020-05, with the labels that each got.

#7220 docs: update bom version
  TROUBLESHOOTING.md
Labels: cla: yes

#7217 chore: regenerate client list in README
  README.md
  synth.metadata
Labels: cla: yes

#7226 Add copyright and region tags to v4 post policy sample
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/GenerateSignedPostPolicyV4.java
Labels: cla: yes

#7229 chore: adding Storage team to CODEOWNERS for samples
  .github/CODEOWNERS
Labels: automerge, cla: yes

#7244 docs: update versions
  TROUBLESHOOTING.md
Labels: cla: yes

#7223 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none
