Repository googleapis/google-cloud-java, pull requests merged in 2020-06, with the labels that each got.

#7247 chore: ignore common-protos/iam repos for client list
  synth.py
Labels: cla: yes

#7246 docs: expand annotation explanations in README
  README.md
Labels: cla: yes

#7248 chore: regenerate client list in README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7260 docs: update versions
  TROUBLESHOOTING.md
Labels: cla: yes

#7264 chore: regenerate client list in README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7253 chore: add example for configuring proxy for gRPC client
  README.md
Labels: cla: yes

#7266 chore: lock google-java-format version
  google-api-grpc/pom.xml
  google-cloud-clients/pom.xml
  google-cloud-examples/pom.xml
  google-cloud-testing/pom.xml
  google-cloud-util/pom.xml
Labels: cla: yes

#7265 pub/sub: cleanup migrated samples and update region tag
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/CreateSubscriptionAndConsumeMessages.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/CreateTopicAndPublishMessages.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/MessageReceiverSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/PublisherSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/SubscriberSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/SubscriptionAdminClientSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/TopicAdminClientSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/UsePubSubEmulatorSnippet.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/pubsub/snippets/Cleanup.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/pubsub/snippets/ITPubSubSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/pubsub/snippets/ITSubscriptionAdminClientSnippets.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/pubsub/snippets/ITTopicAdminClientSnippets.java
Labels: cla: yes

#7254 chore: README cleanup
  README.md
Labels: cla: yes

#7268 nit: remove outdated region tag
  google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/UsePubSubEmulatorSnippet.java
Labels: cla: yes

#7272 chore(docs): libraries-bom 7.0.0
  TROUBLESHOOTING.md
Labels: cla: yes

#7270 chore: regenerate client list in README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7276 chore: regenerate client list in README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7285 chore(docs): libraries-bom 8.0.0
  TROUBLESHOOTING.md
Labels: cla: yes
