Repository googleapis/google-cloud-java, pull requests merged in 2020-09, with the labels that each got.

#7327 Add custom time to metadata sample
  google-cloud-examples/pom.xml
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/GetObjectMetadata.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITBlobSnippets.java
Labels: cla: yes

#7329 libraries-bom 10.1.0
  TROUBLESHOOTING.md
Labels: cla: yes

#7330 (feat) storage: use String instead of Path in download sample
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/DownloadObject.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITBlobSnippets.java
Labels: cla: yes, samples

#7334 chore: set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
Labels: cla: yes

#7335 chore: manage repo settings
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#7337 fix: modify move object java sample to better match other languages
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/MoveObject.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITBlobSnippets.java
Labels: cla: yes

#7343 chore: fix sync-repo-settings syntax
  .github/sync-repo-settings.yaml
Labels: cla: yes
