Repository googleapis/google-cloud-java, pull requests merged in 2021-07, with the labels that each got.

#7590 chore: update README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7604 chore: update README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7606 chore: update README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7607 chore: update README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7612 chore: update README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7613 chore(test): fixing google-cloud-compute code snippet for the Libraries BOM 20.8.0
  google-cloud-examples/pom.xml
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/deprecated/ComputeExample.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateAddressDiskAndInstance.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateInstance.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateSnapshot.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/v1/ComputeExample.java
  google-cloud-testing/spanner-benchwrapper/pom.xml
Labels: cla: yes

#7611 chore(deps): libraries-bom 20.8.0 release
  TROUBLESHOOTING.md
Labels: cla: yes

#7619 docs: libraries-bom 20.9.0
  TROUBLESHOOTING.md
Labels: cla: yes

#7615 chore: update README
  README.md
  synth.metadata
Labels: cla: yes, context: none
