Repository googleapis/google-cloud-java, pull requests merged in 2021-03, with the labels that each got.

#7489 docs: libraries-bom 19.0.0
  TROUBLESHOOTING.md
Labels: cla: yes

#7490 docs: add Artifact Registry to Readme
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7493 doc: add new libraries to README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7499 docs: stop requesting bucket metadata when listing objects
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/ListObjects.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/ListObjectsWithPrefix.java
Labels: cla: yes

#7481 samples(securitycenter): remove unused region tags
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/AssetSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/FindingSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/OrganizationSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/SecurityMarkSnippets.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/securitycenter/snippets/SourceSnippets.java
Labels: api: securitycenter, automerge, cla: yes, samples

#7507 chore(deps): libraries-bom 19.2.1
  TROUBLESHOOTING.md
Labels: cla: yes

#7473 deps: update Guava
  google-cloud-util/google-cloud-compat-checker/pom.xml
Labels: cla: yes

#7498 chore: regenerate client list
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
