Repository googleapis/google-cloud-java, pull requests merged in 2021-05, with the labels that each got.

#7538 build(java): switch to release-please for release tagging
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none, kokoro:force-run

#7542 build(java): switch to release-please for release tagging
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7548 docs: libraries-bom 20.3.0
  TROUBLESHOOTING.md
Labels: cla: yes

#7550 chore: update README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7555 chore: update README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#7565 docs: libraries-bom 20.5.0
  TROUBLESHOOTING.md
Labels: cla: yes
