Repository googleapis/google-cloud-java, pull requests merged in 2021-09, with the labels that each got.

#7657 chore: Update CODEOWNERS for @googleapis/cloud-storage-dpe
  .github/CODEOWNERS
Labels: cla: yes

#7654 chore(deps): libraries-bom 23.0.0
  TROUBLESHOOTING.md
Labels: cla: yes

#7656 chore: re-generated to pick up changes from self
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7668 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#7675 build: move readme generation to GitHub action
  .github/workflows/readme.yaml
  generate-readme.py
  synth.metadata
Labels: cla: yes, automerge

#7681 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge

#7683 chore: change branch master to main in github configurations
  .github/workflows/readme.yaml
  README.md
Labels: cla: yes, automerge
