Repository googleapis/google-cloud-java, pull requests merged in 2022-10, with the labels that each got.

#8524 chore: limit renovate packages
  renovate.json
Labels: automerge

#8526 ci: release please config sync check job
  .github/workflows/generated_files_sync.yaml
Labels: automerge

#8516 chore: update CodeCoverage pom.xml by running the script
  .github/workflows/bootstrap.yaml
  .github/workflows/generated_files_sync.yaml
  CoverageAggregator/pom.xml
  generation/generate_coverage_aggregator.sh
Labels: automerge

#8517 chore: script to create a new module
  .gitignore
  generation/new_client/README.md
  generation/new_client/new-client.py
  generation/new_client/requirements.in
  generation/new_client/requirements.txt
  generation/new_client/templates.py
  generation/new_client/templates/owlbot.py.j2
  generation/new_client/templates/owlbot.yaml.monorepo.j2
Labels: automerge

#8553 test: disable flaky ITAddressesTest in java-compute
  java-compute/README.md
  java-compute/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/ITAddressesTest.java
Labels: automerge

#8558 build: [new client] module name in deep_remove_regex
  generation/new_client/templates/owlbot.yaml.monorepo.j2
Labels: automerge

#8557 feat: [publicca] new module for publicca
  .release-please-manifest.json
  CoverageAggregator/pom.xml
  java-publicca/.OwlBot.yaml
  java-publicca/.repo-metadata.json
  java-publicca/README.md
  java-publicca/google-cloud-publicca-bom/pom.xml
  java-publicca/google-cloud-publicca/pom.xml
  java-publicca/google-cloud-publicca/src/main/java/com/google/cloud/security/publicca/v1beta1/PublicCertificateAuthorityServiceClient.java
  java-publicca/google-cloud-publicca/src/main/java/com/google/cloud/security/publicca/v1beta1/PublicCertificateAuthorityServiceSettings.java
  java-publicca/google-cloud-publicca/src/main/java/com/google/cloud/security/publicca/v1beta1/gapic_metadata.json
  java-publicca/google-cloud-publicca/src/main/java/com/google/cloud/security/publicca/v1beta1/package-info.java
  java-publicca/google-cloud-publicca/src/main/java/com/google/cloud/security/publicca/v1beta1/stub/GrpcPublicCertificateAuthorityServiceCallableFactory.java
  java-publicca/google-cloud-publicca/src/main/java/com/google/cloud/security/publicca/v1beta1/stub/GrpcPublicCertificateAuthorityServiceStub.java
  java-publicca/google-cloud-publicca/src/main/java/com/google/cloud/security/publicca/v1beta1/stub/HttpJsonPublicCertificateAuthorityServiceCallableFactory.java
  java-publicca/google-cloud-publicca/src/main/java/com/google/cloud/security/publicca/v1beta1/stub/HttpJsonPublicCertificateAuthorityServiceStub.java
  java-publicca/google-cloud-publicca/src/main/java/com/google/cloud/security/publicca/v1beta1/stub/PublicCertificateAuthorityServiceStub.java
  java-publicca/google-cloud-publicca/src/main/java/com/google/cloud/security/publicca/v1beta1/stub/PublicCertificateAuthorityServiceStubSettings.java
  java-publicca/google-cloud-publicca/src/test/java/com/google/cloud/security/publicca/v1beta1/MockPublicCertificateAuthorityService.java
  java-publicca/google-cloud-publicca/src/test/java/com/google/cloud/security/publicca/v1beta1/MockPublicCertificateAuthorityServiceImpl.java
  java-publicca/google-cloud-publicca/src/test/java/com/google/cloud/security/publicca/v1beta1/PublicCertificateAuthorityServiceClientHttpJsonTest.java
  java-publicca/google-cloud-publicca/src/test/java/com/google/cloud/security/publicca/v1beta1/PublicCertificateAuthorityServiceClientTest.java
  java-publicca/grpc-google-cloud-publicca-v1beta1/pom.xml
  java-publicca/grpc-google-cloud-publicca-v1beta1/src/main/java/com/google/cloud/security/publicca/v1beta1/PublicCertificateAuthorityServiceGrpc.java
  java-publicca/owlbot.py
  java-publicca/pom.xml
  java-publicca/proto-google-cloud-publicca-v1beta1/clirr-ignored-differences.xml
  java-publicca/proto-google-cloud-publicca-v1beta1/pom.xml
  java-publicca/proto-google-cloud-publicca-v1beta1/src/main/java/com/google/cloud/security/publicca/v1beta1/CreateExternalAccountKeyRequest.java
  java-publicca/proto-google-cloud-publicca-v1beta1/src/main/java/com/google/cloud/security/publicca/v1beta1/CreateExternalAccountKeyRequestOrBuilder.java
  java-publicca/proto-google-cloud-publicca-v1beta1/src/main/java/com/google/cloud/security/publicca/v1beta1/ExternalAccountKey.java
  java-publicca/proto-google-cloud-publicca-v1beta1/src/main/java/com/google/cloud/security/publicca/v1beta1/ExternalAccountKeyName.java
  java-publicca/proto-google-cloud-publicca-v1beta1/src/main/java/com/google/cloud/security/publicca/v1beta1/ExternalAccountKeyOrBuilder.java
  java-publicca/proto-google-cloud-publicca-v1beta1/src/main/java/com/google/cloud/security/publicca/v1beta1/LocationName.java
  java-publicca/proto-google-cloud-publicca-v1beta1/src/main/java/com/google/cloud/security/publicca/v1beta1/ResourcesProto.java
  java-publicca/proto-google-cloud-publicca-v1beta1/src/main/java/com/google/cloud/security/publicca/v1beta1/ServiceProto.java
  java-publicca/proto-google-cloud-publicca-v1beta1/src/main/proto/google/cloud/security/publicca/v1beta1/resources.proto
  java-publicca/proto-google-cloud-publicca-v1beta1/src/main/proto/google/cloud/security/publicca/v1beta1/service.proto
  java-publicca/versions.txt
  pom.xml
  release-please-config.json
Labels: automerge

#8560 ci: adding gitignore check
  .github/workflows/generated_files_sync.yaml
  .gitignore
Labels: automerge

#8488 chore: Add .java and .proto files to same diff branch
  .github/workflows/generate_diffs.yaml
  generation/generate_diff.sh
Labels: automerge

#8563 feat: [bigquerydatapolicy] new module for bigquerydatapolicy
  .release-please-manifest.json
  CoverageAggregator/pom.xml
  java-bigquerydatapolicy/.OwlBot.yaml
  java-bigquerydatapolicy/.repo-metadata.json
  java-bigquerydatapolicy/README.md
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy-bom/pom.xml
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/pom.xml
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataPolicyServiceClient.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataPolicyServiceSettings.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/gapic_metadata.json
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/package-info.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/stub/DataPolicyServiceStub.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/stub/DataPolicyServiceStubSettings.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/stub/GrpcDataPolicyServiceCallableFactory.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/stub/GrpcDataPolicyServiceStub.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/stub/HttpJsonDataPolicyServiceCallableFactory.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/stub/HttpJsonDataPolicyServiceStub.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/test/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataPolicyServiceClientHttpJsonTest.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/test/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataPolicyServiceClientTest.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/test/java/com/google/cloud/bigquery/datapolicies/v1beta1/MockDataPolicyService.java
  java-bigquerydatapolicy/google-cloud-bigquerydatapolicy/src/test/java/com/google/cloud/bigquery/datapolicies/v1beta1/MockDataPolicyServiceImpl.java
  java-bigquerydatapolicy/grpc-google-cloud-bigquerydatapolicy-v1beta1/pom.xml
  java-bigquerydatapolicy/grpc-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataPolicyServiceGrpc.java
  java-bigquerydatapolicy/owlbot.py
  java-bigquerydatapolicy/pom.xml
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/clirr-ignored-differences.xml
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/pom.xml
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/CreateDataPolicyRequest.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/CreateDataPolicyRequestOrBuilder.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataMaskingPolicy.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataMaskingPolicyOrBuilder.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataPolicy.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataPolicyName.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataPolicyOrBuilder.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DataPolicyProto.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DeleteDataPolicyRequest.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/DeleteDataPolicyRequestOrBuilder.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/GetDataPolicyRequest.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/GetDataPolicyRequestOrBuilder.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/ListDataPoliciesRequest.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/ListDataPoliciesRequestOrBuilder.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/ListDataPoliciesResponse.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/ListDataPoliciesResponseOrBuilder.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/LocationName.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/UpdateDataPolicyRequest.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/java/com/google/cloud/bigquery/datapolicies/v1beta1/UpdateDataPolicyRequestOrBuilder.java
  java-bigquerydatapolicy/proto-google-cloud-bigquerydatapolicy-v1beta1/src/main/proto/google/cloud/bigquery/datapolicies/v1beta1/datapolicy.proto
  java-bigquerydatapolicy/versions.txt
  pom.xml
  release-please-config.json
Labels: automerge

#8569 docs: regenerating java-gke-connect-gateway generated samples
  java-assured-workloads/samples/install-without-bom/pom.xml
  java-assured-workloads/samples/pom.xml
  java-assured-workloads/samples/snapshot/pom.xml
  java-assured-workloads/samples/snippets/pom.xml
  java-gke-connect-gateway/README.md
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/create/SyncCreateSetCredentialsProvider.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/create/SyncCreateSetEndpoint.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/deleteresource/AsyncDeleteResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/deleteresource/SyncDeleteResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/getresource/AsyncGetResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/getresource/SyncGetResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/patchresource/AsyncPatchResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/patchresource/SyncPatchResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/postresource/AsyncPostResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/postresource/SyncPostResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/putresource/AsyncPutResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayserviceclient/putresource/SyncPutResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/gatewayservicesettings/getresource/SyncGetResource.java
  java-gke-connect-gateway/samples/snippets/generated/com/google/cloud/gkeconnect/gateway/v1beta1/stub/gatewayservicestubsettings/getresource/SyncGetResource.java
  java-grafeas/samples/install-without-bom/pom.xml
  java-grafeas/samples/pom.xml
  java-grafeas/samples/snapshot/pom.xml
  java-grafeas/samples/snippets/pom.xml
  java-speech/samples/install-without-bom/pom.xml
  java-speech/samples/pom.xml
  java-speech/samples/snapshot/pom.xml
  java-speech/samples/snippets/pom.xml
Labels: automerge, samples

#8561 chore: new-client.py not to take boilerplate args
  generation/new_client/README.md
  generation/new_client/new-client.py
Labels: automerge

#8573 chore: Add GraalVM checks as required
  .github/sync-repo-settings.yaml
Labels: automerge

#8584 chore: Ignore bom and jar parent for Cloud RAD
  .kokoro/common.sh
  .kokoro/release/publish_javadoc11.sh
Labels: automerge

#8585 chore: Install modules
  .kokoro/release/publish_javadoc11.sh
Labels: automerge

#8590 Revert "fix(deprecate): removed older version of Compute client library samples"
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/README.md
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateAddressDiskAndInstance.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateInstance.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateSnapshot.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/v1/ComputeExample.java
Labels: samples

#8591 build: new-client.py to call consolidate_config and set_parent
  generation/new_client/new-client.py
Labels: automerge

#8594 chore: update pom parent versions.txt
  versions.txt
Labels: automerge

#8586 chore: Use requirements.txt for CloudRAD
  .kokoro/release/publish_javadoc11.sh
  .kokoro/requirements.in
  .kokoro/requirements.txt
  java-compute/google-cloud-compute/src/test/java/com/google/cloud/compute/v1/integration/Util.java
  java-notebooks/google-cloud-notebooks/src/test/java/com/google/cloud/notebooks/v1beta1/it/Util.java
Labels: automerge

#8602 chore: Set doclet_version and module_list as env_vars
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
Labels: automerge

#8606 chore: Fixing root pom
  generation/parent.pom.xml
  pom.xml
Labels: automerge

#8603 chore: deploy to production environment
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/stage.sh
  generation/generate_release_please_config.sh
  release-please-config.json
Labels: automerge

#8622 chore: fix release-please config generation sync
  .github/workflows/generated_files_sync.yaml
  generation/release_please_config_raw.json
  release-please-config.json
Labels: automerge

#8619 chore: Fix update_versions.sh to include beyondcorp
  .release-please-manifest.json
  generation/update_versions.sh
  java-beyondcorp-appconnections/google-cloud-beyondcorp-appconnections-bom/pom.xml
  java-beyondcorp-appconnections/google-cloud-beyondcorp-appconnections/pom.xml
  java-beyondcorp-appconnections/grpc-google-cloud-beyondcorp-appconnections-v1/pom.xml
  java-beyondcorp-appconnections/pom.xml
  java-beyondcorp-appconnections/proto-google-cloud-beyondcorp-appconnections-v1/pom.xml
  java-beyondcorp-appconnections/versions.txt
  java-beyondcorp-appconnectors/google-cloud-beyondcorp-appconnectors-bom/pom.xml
  java-beyondcorp-appconnectors/google-cloud-beyondcorp-appconnectors/pom.xml
  java-beyondcorp-appconnectors/grpc-google-cloud-beyondcorp-appconnectors-v1/pom.xml
  java-beyondcorp-appconnectors/pom.xml
  java-beyondcorp-appconnectors/proto-google-cloud-beyondcorp-appconnectors-v1/pom.xml
  java-beyondcorp-appconnectors/versions.txt
  java-beyondcorp-appgateways/google-cloud-beyondcorp-appgateways-bom/pom.xml
  java-beyondcorp-appgateways/google-cloud-beyondcorp-appgateways/pom.xml
  java-beyondcorp-appgateways/grpc-google-cloud-beyondcorp-appgateways-v1/pom.xml
  java-beyondcorp-appgateways/pom.xml
  java-beyondcorp-appgateways/proto-google-cloud-beyondcorp-appgateways-v1/pom.xml
  java-beyondcorp-appgateways/versions.txt
  java-beyondcorp-clientconnectorservices/google-cloud-beyondcorp-clientconnectorservices-bom/pom.xml
  java-beyondcorp-clientconnectorservices/google-cloud-beyondcorp-clientconnectorservices/pom.xml
  java-beyondcorp-clientconnectorservices/grpc-google-cloud-beyondcorp-clientconnectorservices-v1/pom.xml
  java-beyondcorp-clientconnectorservices/pom.xml
  java-beyondcorp-clientconnectorservices/proto-google-cloud-beyondcorp-clientconnectorservices-v1/pom.xml
  java-beyondcorp-clientconnectorservices/versions.txt
  java-beyondcorp-clientgateways/google-cloud-beyondcorp-clientgateways-bom/pom.xml
  java-beyondcorp-clientgateways/google-cloud-beyondcorp-clientgateways/pom.xml
  java-beyondcorp-clientgateways/grpc-google-cloud-beyondcorp-clientgateways-v1/pom.xml
  java-beyondcorp-clientgateways/pom.xml
  java-beyondcorp-clientgateways/proto-google-cloud-beyondcorp-clientgateways-v1/pom.xml
  java-beyondcorp-clientgateways/versions.txt
Labels: automerge

#8631 fix: fixed non-GA logic for gapic-bom
  gapic-libraries-bom/pom.xml
  generation/generate_gapic_bom.sh
Labels: automerge

#8633 chore: stop diff generation jobs
  .github/workflows/generate_diffs.yaml
  generation/generate_diff.sh
Labels: automerge

#8641 chore: Run ITs on diffs between latest and the branching commit
  .kokoro/build.sh
  .kokoro/common.sh
  .kokoro/release/publish_javadoc11.sh
Labels: automerge

#8607 chore: use requirements.txt in readme and staging jobs
  .github/requirements.in
  .github/requirements.txt
  .github/workflows/readme.yaml
  .kokoro/release/stage.sh
Labels: automerge

#8657 build: OwlBot.yaml to have api-name.
  generation/new_client/templates/owlbot.yaml.monorepo.j2
  java-analyticshub/.OwlBot.yaml
  java-apikeys/.OwlBot.yaml
  java-bigquerydatapolicy/.OwlBot.yaml
  java-distributedcloudedge/.OwlBot.yaml
  java-publicca/.OwlBot.yaml
Labels: automerge

#8658 chore: Add java-speech META-INF/* config for GraalVM
  java-speech/.OwlBot.yaml
  java-speech/google-cloud-speech/src/test/resources/META-INF/native-image/com.google.cloud/google-cloud-speech/resource-config.json
Labels: automerge

#8653 chore: allow new-client.py to run directly without workspace
  generation/new_client/README.md
  generation/new_client/new-client.py
Labels: automerge

#8685 chore: Run on diffs only from PR branch
  .kokoro/common.sh
Labels: automerge

#8691 chore: .release-please-manifest.json to have released version
  .release-please-manifest.json
  generation/generate_release_please_config.sh
Labels: automerge

#8695 chore: upgrading owlbot-java sha256 to latest
  .github/.OwlBot.lock.yaml
  java-dialogflow/.gitignore
  java-discoveryengine/.gitignore
  java-monitoring-dashboards/.gitignore
  java-video-stitcher/.gitignore
Labels: automerge
