Repository googleapis/google-cloud-java, pull requests merged in 2022-02, with the labels that each got.

#7779 Adds Sample for changing the endpoint on the storage client.
  google-cloud-examples/src/main/java/com/google/cloud/examples/storage/buckets/SetClientEndpoint.java
  google-cloud-examples/src/test/java/com/google/cloud/examples/storage/snippets/ITBucketSnippets.java
Labels: api: storage, samples

#7785 chore(docs): libraries-bom 24.3.0 in google-cloud-java
  TROUBLESHOOTING.md
Labels: automerge

#7799 fix(deprecate): removed older version of Compute client library samples
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/README.md
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateAddressDiskAndInstance.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateInstance.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateSnapshot.java
  google-cloud-examples/src/main/java/com/google/cloud/examples/compute/v1/ComputeExample.java
Labels: samples
