Repository googleapis/google-cloud-java, pull requests merged in 2023-03, with the labels that each got.

#9172 ci: adding Java package name check
  .github/workflows/generated_files_sync.yaml
Labels: automerge

#9188 fix(speech): increment retry setting values and test timeout values in IT
  java-speech/README.md
  java-speech/google-cloud-speech/src/test/java/com/google/cloud/speech/v1/it/ITSpeechTest.java
Labels: api: speech

#9178 chore: Introducing release profile for non-cloud clients.
  .kokoro/release/stage_oss_sonatype_org.sh
  google-cloud-pom-parent/pom.xml
  java-bigqueryconnection/README.md
  java-bigqueryconnection/google-cloud-bigqueryconnection/src/test/java/com/google/cloud/bigqueryconnection/v1/it/ITSystemTest.java
  pom.xml
Labels: autorelease: published

#9238 ci: owlbot update lock job not to use gcloud
  .github/workflows/owlbot_sha256.yaml
Labels: automerge

#9246 ci: avoid version check on autorelease snapshot
  .github/workflows/versions.yaml
Labels: automerge

#9250 chore: Add .repo-metadata.json file for java-core
  .kokoro/release/publish_javadoc11.sh
  java-core/.repo-metadata.json
Labels: automerge
